folio-org/stripes-core

src/configureStore.js
This is a quick set up for enabling the redux-devtools extenstion without any additional packages installed.
To test this we should install either the browser or non-browser Redux DevTools extenstion.For more details below are few references.
https://github.com/zalmoxisus/redux-devtools-extension
https://medium.com/@zalmoxis/using-redux-devtools-in-production-4c5b56c5600f 
Also If you feel like playing with it more with some complex objects .Try logging into slack.com in browser with the extension installed.
@skomorokh
=> redux dev tools extension

src/components/MainNav/MainNav.js
The top navigation bar is populated via the automatically discovered list of applications. However, in addition to those, there is a list of six navigation buttons that don't appear to serve any purpose other than to demonstrate the visual style. For someone using the system this can be confusing since it immediately raises the question "should this do something?", or "should it go somewhere?"
This removes those questions by removing those buttons.
=> Remove unused nav buttons

src/Root.js, src/components/Front.js
The landing page of a stripes application is the first thing that a user sees when they navigate to it. At the moment, there is a placeholder text there, but you can't customize that text.
This change adds a new type of plugin "frontpage" which, if present will be presented to the user.
Implementation Notes
====================
- if a plugged-in component is rendered in a stripes connected environment, the `Pluggable` component will attempt to connect the component that it wraps. However, if we're rendering outside the context of an app (as in the case of the frontpage), then the `connect()` method is not present on the stripes context. This adds a default `connect()` which passes through the original component without any decoration
- The `Front` component needed to be extended because …
=> [STCOR-46] Make Front page component pluggable.

src/Root.js
Popular test runners like [Karma][1] and [Testem][2] allow you to run your test suite against multiple browsers. In order to do this, they invert control so that a browser is driving the test suite, and not that the test suite is driving a browser.
However, this creates a problem in certain scenarios because in order for the browser to "capture" an application, it can't have the URL _actually_ changing as the test navigates around the application. As a result, in order to use one of these runners with react router, it needs to use an instance of `MemoryHistory` and not `BrowserHistory`. That way, the URL changes only from the perspective of the application, but not from the perspective of the actual browser.
This change allows the `Root` component to accept a `history` property, which …
=> Allow pluggable history interface in stripes router.

src/AddContext.js, src/Root.js, src/components/About.js, src/components/Login/Login.js, src/components/Login/LoginCtrl.js, src/components/MainContainer/MainContainer.js, src/components/MainNav/Breadcrumbs/Breadcrumbs.js, src/components/MainNav/MainNav.js, src/components/MainNav/NavButton/NavButton.js, src/components/MainNav/NavDivider/NavDivider.js, src/components/MainNav/NavDropdownMenu/NavDropdownMenu.js, src/components/MainNav/NavGroup/NavGroup.js, src/components/MainNav/NavIcon/NavIcon.js, src/components/ModuleContainer/ModuleContainer.js, src/components/Notification/Toast.js, src/components/Notification/ToastNotification.js, src/components/Settings/NavList/NavList.js, src/components/Settings/NavListSection/NavListSection.js, src/components/Settings/Settings.js
This removes warnings generated like the following:
>Accessing PropTypes via the main React package is deprecated, and will be removed in  React v16.0. Use the latest available v15.* prop-types package from npm instead. For info on usage, compatibility, migration and more, see https://fb.me/prop-types-docs
=> Clean up prop-types related deprecations

index.html
Currently, opening a FOLIO application on a mobile browser will usually result in the page width being calculated as much wider than the device's screen (and zoomed out):
Instead, by default we can set the width of the page to equal the width of the device, with the zoom at 100%. Users can then zoom in more if needed. https://developer.mozilla.org/en-US/docs/Mozilla/Mobile/Viewport_meta_tag
=> Set initial viewport state with meta tag

src/Root.js
Because of automatic merging, the `Root.defaultProps` were specified twice, which caused the default browser history not to get created.
Sounds like we need some sore of automated sanity testing to catch integration issues like this one.
=> [STCOR-47] Don't specify defaultProps twice.

src/Root.js
If the Root component were to be mounted and unmounted any reducers
previously added would remain in the reducers object and so new
reducers with the same key would never be overridden.
This can be problematic during testing when you want a new app (and store)
instance for each test case. In those instances the new store reducers
are never added to the new store because their keys would be present
in the already existing reducers hash.
This change simply moves the reducers reference to be instance
specific. So when new instances of the Root component are created the
reducers hash is set to it's initial value.
=> Move root component reducers reference to be instance specific

src/components/SSOLanding.js, src/loginServices.js
The /_self endpoint should be used for retrieving the current user instead of the /bl-users/by-id/{userId} endpoint from mod-users-bl. If the latter is used the user is required to have a permission for retrieving the user.
=> STCOR-61 Update user retrieval after SSO login.

src/RootWithIntl.js, src/components/SSORedirect.js, src/loginServices.js
A new component was created to redirect the user from the /sso-landing page after login to the original url. Also the path of the original login request is preserved (in loginServices).
=> STCOR-62 Redirect user to original url after SSO authentication

src/Root.js, src/configureEpics.js, src/configureStore.js, src/index.js
As an application container, Stripes cannot know ahead of time which epics will be installed into its Redux middleware. Because of that, if apps or extensions are going to use epics, then they will need to have a way to add them from within their own lifecycle. E.g. when the application component mounts, it can communicate which epics it contains.
Furthermore, it is a possibility that a stripes application contained by the platform will be mounted and unmounted several times, and so the extension mechanism must not "overinstall" epics as the user navigates to and from an application so that they end up being run in duplicate, triplicate, etc...
This change contains two enhancements. First, the epics Redux middleware was removed from being held as a static constant in the `src/epics` …
=> Allow for contextual epics

src/configureStore.js
The previous method of composing the middleware would call the middleware initializers twice, and so a side-effect of this was that epics would receive double the actions.
This changes the compose method to use redux devtool's own compose (according to [their docs](https://github.com/zalmoxisus/redux-devtools-extension#12-advanced-store-setup)) and thus fixes the double epic calls.
This also fixes the logger logging itself (the `PERFORM_ACTION` action in the first gif below).
=> Fix redux devtools compose

.babelrc, examples/trivial/package.json, package.json, webpack.config.base.js
By default, `babel-preset-env` will continue to have the same behavior we had with `babel-preset-es2015`. It has additional options for delivering more modern JavaScript, depending on the browser configuration provided.
Switching will eliminate this warning:
`We're super 😸  excited that you're trying to use ES2015 syntax, but instead of continuing yearly presets 😭 , we recommend using babel-preset-env: npm install babel-preset-env. preset-env without options will compile ES2015+ down to ES5. And by targeting specific browsers, Babel can do less work and you can ship native ES2015+ to users 😎 ! Also, we are in the process of releasing v7, so give http://babeljs.io/blog/2017/09/12/planning-for-7.0 a read and test it! Thanks so much for using Babel 🙏 , please give us a follow @babeljs for …
=> Switch to babel-preset-env

package.json
Latest commits are needed to resolve babel preset errors from recent detangling work until new releases are available.
=> Point to latest commits of dependencies

package.json
We can't point stripes-core to a specific commit of stripes-loader becuase of dependency on prepublish.  This depends on stripes-loader PR 4 being merged.
=> Use next version of stripes-loader

src/moduleRoutes.js
The `getModuleRoutes` method appears to generate a routing entry for all loaded stripes modules.  It then maps those routes to a container node that sort of functions as a namespace for the different UI modules installed in the Folio instance.
We were using spans here, but it's probably better to use divs to avoid nesting block-level elements inside inline elements.  This isn't blocking anything that we know of, but we stumbled across it while doing some layout work and figured it was worthy of a quick patch.
=> Use <div> instead of <span> when dynamically generating module routes and containers

package.json
"serialize-javascript" and "webpack-virtual-modules" both need to be listed as dependencies rather than devDependencies in order to be available when building a platform from stripes-core
=> Move necessary devDependencies to dependencies

stripes.js
Builds with webpack compilation errors were passing CI because of a missing exit code.  Fixes STCOR-85
=> Stcor 85 exit code

package.json, stripes.js
This allows direct requests to routes such as /users to fallback to webpack's built version of index.html.  The previous res.sendFile() is no longer sufficient because we need the copy of index that webpack has in memory and not the version on disk.  Fixes STCOR-86
=> STCOR-86 Add connect-history-api-fallback to stripes dev server

src/Stripes.js
Fixes padded-block violation.
*before*
```
$ yarn lint                                                                           
yarn lint v1.0.2
$ eslint src || true
/Code/stripes-core/src/Stripes.js
64:1  error  Block must not be padded by blank lines  padded-blocks
✖ 1 problem (1 error, 0 warnings)
1 error, 0 warnings potentially fixable with the `--fix` option.
✨  Done in 3.27s.
```
*after*
```
$ yarn lint                                                                           
yarn lint v1.0.2
$ eslint src || true
✨  Done in 3.19s.
```
=> Delint padded block

src/components/MainContainer/global.css
Basic fill-in to ease the brunt of some changes due to removal of bootstrap.css here: https://github.com/folio-org/stripes-core/pull/61
=> fill in global styles to facilitate deprecation of bootstrap styles

src/Root.js, src/RootWithIntl.js, src/discoverServices.js
Application modules can be rendered before the services that they depend on have been discovered. The `discoverServices` thunk can potentially dispatch multiple `DISCOVERY_SUCCESS` and `DISCOVERY_FAILURE` actions while discovery is happening, but there is no action to mark when the discovery process is fully complete. Without this capability, it is possible for an application to render without knowing if its dependencies are satisfied on the backend.
This ensures that whenever a promise is generated inside the discovery process, it is returned so that it can be used for sequencing further promises. Then, once the discovery process is complete, a final `DISCOVERY_COMPLETE` is dispatched. Because individual discovery errors are caught, this will happen regardless of whether the discovery …
=> Wait until discovery is finished before rendering the module container

webpack.config.cli.dev.js, webpack.config.cli.prod.js
Source mapping will make CSS debugging much easier.
- Set `sourceMap` to true for each of the webpack style loaders in a dev environment.
- Do not deliver source maps in a production build.
https://github.com/postcss/postcss-loader#sourcemap
=> Turn on CSS source maps

src/discoverServices.js
When you catch a promise, it does not stop the propagation of a chain. This allows you to handle errors before continuing the chain.
So when the discovery promises were failing and getting caught, the following `.then` chains were still called, except with the argument returned from the catch statement. Since the catch statements do not return anything, the resulting `response` is `undefined`. So properties like `response.status` throw errors.
This simply moves those catch statements to be at the end of their respective chains so when a failure occurs it does not continue. If the promise is rejected before a preceding `then` block, that block will be skipped and the promise will immediately call the first `catch` statement it sees.
[MDN - Using Promises (Chaining after a …
=> Fix promise catch order

CHANGELOG.md, src/RootWithIntl.js, src/components/About.js, src/components/AboutEnabledModules.js
In order to label a tenant's disabled modules, we need to be able to
query Okapi from within stripes-core, but `stripes.connect()`, which is
actually the result of calling `connectFor('@folio/some-module')` for
each dynamically-loaded module, wasn't available within stripes-core.
The approach taken here was to hard-code a call to
`connectFor('@folio/core')` on `RootWithIntl` and to replace the dummy
version of `stripes.connect` with the result of that call, as is done in
`moduleRoutes.js::getModuleRoutes()` for dynamically loaded modules.
This is in contrast to the approach taken in PR #81 where `connect` was
placed in the context rather than directly on the cloned stripes object.
=> Label a tenant's disabled modules on `/about`. Fixes STCOR-69

stripes.js, webpack/build.js, webpack/serve.js, webpack/stripes-node-api.js
Stripes.js now focuses on command and config file input only.  This allows build logic to more readily be reused outside of a CLI. Related to STCOR-29 and prep for FOLIO-852
=> STCOR-29 move build logic

webpack/build.js, webpack/serve.js
This looks to still be necessary for locating loaders in certain build scenarios
=> Restore resolveLoaders config omitted from previous refactor

src/components/MainNav/MainNav.css, src/components/ModuleContainer/ModuleContainer.css
When a module used a layout without a parent `Paneset`, the `MainNav` would collapse. This ensures the `MainNav` maintains its height with or without a `Paneset`.
=> Adjust MainNav flex behavior

src/components/MainContainer/global.css
Another thing that will further shore things up for removal of bootstrap styles... with an actually useful utility class that's used to hide would-be-redundant labels from sighted users, leaving them available to screen readers.
=> Add sr-only class to global.css. Fixes STCOR-99

package.json, stripes.js, webpack.config.cli.prod.js, webpack/build.js
- New `--sourcemap` option for builds (STCOR-64)
- Re-enables javascript minification using the ES6 compatible version of UglifyJS (STRIPES-102)
- Put React in production mode via EnvironmentPlugin (set`NODE_ENV=production` to enable)
=> Webpack build enhancements

stripes.js, webpack/build.js, webpack/serve.js
This will facilitate usage in consumers like stripes-cli by knowing when webpack has finished its initial build.
=> Return promise for build() and serve()

CHANGELOG.md, src/components/MainNav/MainNav.js
Assignment to special parameter `_path` within the anointed
stripes-connect resource will change the URL path.
Fixes STCOR-105.
=> Support "_path" within anointed stripes-connect resource.

.stylelintrc, package.json, src/components/Login/Login.css, src/components/MainContainer/MainContainer.css, src/components/MainNav/Breadcrumbs/Breadcrumbs.css, src/components/MainNav/MainNav.css, src/components/MainNav/NavButton/NavButton.css, src/components/MainNav/NavDivider/NavDivider.css, src/components/MainNav/NavDropdownMenu/NavDropdownMenu.css, src/components/MainNav/NavGroup/NavGroup.css, src/components/MainNav/Notifications/NotificationMenu.css, src/components/ModuleContainer/ModuleContainer.css, src/components/Notification/Toast.css, src/components/Root/Root.css, src/components/Settings/NavListSection/NavListSection.css, src/components/Settings/Settings.css, src/components/variables.css
We'd like to treat our CSS as a first-class citizen with our JavaScript. Part of that means sticking to reasonable, consistent conventions. `stylelint` can give us the same anti-bikeshedding and bug prevention in CSS we already have with `eslint` in JS.
`stylelint` will now run with `eslint` as part of `yarn lint`.
Developers can install a `stylelint` plugin in their editor for faster iteration: https://github.com/stylelint/stylelint/blob/master/docs/user-guide/complementary-tools.md#editor-plugins
Several of the errors would never have been checked in if `.editorconfig` was being followed by the editor: http://editorconfig.org/#download
I started to make a `stylelint-config-stripes`, so that FOLIO Stripes apps could have a shared config like `eslint-config-stripes`. Unfortunately, …
=> Set up stylelint

src/components/MainNav/Notifications/NotificationsMenu.js, src/mapDomains.js, src/uuidRe.js
Use a single constant for the regular expression responsible for finding
UUIDs in the text, and import a function to handle the mapping from a
note's link's domain attribute to a URL so that it can easily be
replaced with something that reads from an application registry once we
finally write an application registry.
You may note that there are many UUID regular expression packages out
there in NPM land. All of them return an actual RegEx object, but in
this case we need the string that we can construct our own RegEx object
around.
=> DRY out notification text parsing. Fixes STCOR-104

CHANGELOG.md, doc/adding-permissions.md
Also add a ToC to the relevant document, which is no longer quite
short enough to be trivial.
Fixes STCOR-112.
=> Documentation on how to add a perms to users from the CLI

webpack.config.base.js, webpack.config.cli.prod.js
This moves the webpack EnvironmentPlugin to the base config so NODE_ENV is available in both dev and prod builds.
=> Always set EnvironmentPlugin for NODE_ENV

index.html, webpack/stripes-config-plugin.js
The virtual module, `stripes-config`, created by stripes-config-plugin does not appear to pass through Babel and therefore the arrow functions for each `getModule()` are left in the code which IE cannot deal with. 
The solution using `new Function()` appears to negate the need for `eval()` due to the similar nature in parsing.   For reference, `eval()` did not want to accept a function expression without the arrow syntax, thus the use of `new Function()` constructor.  Such parsing is needed with `getModule` for feeding app entry points to webpack via require.  This approach may change when we introduce code-splitting.
This issue could also be solved by determining how to pass the `stripes-config` virtual module through the Babel loader.  However, adjusting the one line in …
=> UIEH-107 ie11

CHANGELOG.md, src/discoverServices.js, src/index.js
Previously, `discoverServices()` retrieved the list of globally-available modules rather than those enabled only for the current tenant. On a system with a large number of modules, or with many versions of modules, this led to horrible performance on login while waiting for 1000+ requests to complete as each module was inspected.
=> in discovery, retrieve modules per-tenant. Fixes STCOR-114

src/RootWithIntl.js, src/components/MainNav/MainNav.js, src/components/Root/Root.js, src/index.js
If you don't provide an Okapi section in your Stripes configuration this allows Stripes to continue building. Useful for demoing with the trivial app or building a fully FOLIO front-end that can also work standalone with the same code base. 
Currently requires hasAllPerms and disableAuth in config as we haven't made auth modular yet.
=> Allow use of Stripes without Okapi

CHANGELOG.md, test/webpack/babel-loader-rule.spec.js, webpack.config.base.js, webpack/babel-loader-rule.js
Our fork of `react-githubish-mentions` is under the `@folio` scope and therefore stripes-core attempts to transpile it based on the current babel-loader test condition.  This results in a build error for a missing es2015 preset which Stripes does not use.  
This fix updates the current babel loader test condition to exclude specific folio-scoped modules from selection.  Tests were added before this change to ensure we continue to capture the various desired use cases.
Fixes STRIPES-499.
=> Update babel loader test condition

src/components/MainNav/NavButton/NavButton.css, src/components/MainNav/NavButton/NavButton.js
The id's were missing on nav buttons as mentioned here: https://issues.folio.org/browse/STCOR-132
This fixes that issue by padding the prop down to the button element.
I also added so that the element is changed to an anchor tag if a href-prop is provided. This enables right-click to open in new tab/window.
=> Passing missing id prop to NavButton

CHANGELOG.md, util/link-stripes, util/pull-stripes
=> `link-stripes -i` skips platform packages, quietly re-links already-linked packages, and exits when done. 

webpack/module-paths.js, webpack/stripes-build-error.js, webpack/stripes-translations-plugin.js
This is necessary because stripes-core (where the code is current running) will not be a folio-scoped dependency path.
This was an issue in some environments when looking for /translations within stripes-core.
Fixes STCOR-143 and related to STCOR-49.
=> Add proper path for stripes-core when looking for "@folio/stripe-core"

util/link-stripes
Because we don't want to encourage people to use `yarn link`.
=> Refuse to run unless '--really' is specified as 1st arg

package.json, webpack/serve.js
The main cause of the noise is that when any one warning is present, webpack-dev-server will [output all stats as a warning](https://github.com/webpack/webpack-dev-middleware/blob/236afb1c28e443e4fd9cddff9973e8edfe9e5f0b/lib/reporter.js#L10-L16), rather than output only the warnings themselves.  The same is true for errors.
As a quick solution, the `minimal` stats preset is sufficient to quiet the output.  Warnings and errors will still show.  We always can opt for more [fine-grained control](https://webpack.js.org/configuration/stats/#stats) of stats options or [write our own reporter](https://github.com/webpack/webpack-dev-middleware#reporter) if so desired.
Builds will continue to receive the default output.
Fixes STCOR-144
=> Specify 'minimal' preset and upgrade webpack-dev-middleware

default-assets/branding.js, test/webpack/stripes-branding-plugin.spec.js, webpack/stripes-branding-plugin.js
This enables us to once again list a relative path for a module in a Stripes config and launch stripes.js from within core. Very helpful for integration testing of stripes-core as we can just check in some mocked modules and refer to them with little fuss.
=> Avoid module name for local files and allow absolute paths for branding

src/components/Login/Login.js, src/components/Notification/ToastNotification.js, src/components/SSOLogin/SSOLogin.js
Follow-up to https://github.com/folio-org/stripes-components/pull/209.
1. `transparent` is no longer an available button style; replaced with `link`
2. Now that `primary` is no longer the default button style (now `default` is), the primary action buttons on login pages needed that style applied.
=> Improve button style consistency 

CHANGELOG.md, util/pull-stripes
Fixes [STCOR-156](https://issues.folio.org/browse/STCOR-156).
=> remove ui-okapi-console from pull-stripes; it's deprecated. Fixes STCOR-156

src/components/MainNav/MainNav.js
This is the default behaviour until the active menu item to the left becomes a dropdown in the future.
=> Removed href from active menu button when on settings.

package.json
`@folio/ui-eholdings` is failing to create a production build in CI:
There's a bug in `uglify-es` causing the failure (https://github.com/mishoo/UglifyJS2/issues/2896), and a new version hasn't been cut yet. This will lock in `uglify-es` (needed by `uglify-webpack-plugin`) to 3.3.9, before the bug was introduced.
=> Lock in uglify-es version because of bug on 3.3.10

src/components/Settings/Settings.js
https://issues.folio.org/browse/STRIPES-505
The bug is that _eHoldings_ is the last item, after _Users_.
With this PR, _eHoldings_ is after _Developer_ and before _Organization_
=> STRIPES-505: Settings Pane Should List Items Alphabetically

test/webpack/stripes-branding-plugin.spec.js, test/webpack/stripes-config-plugin.spec.js, test/webpack/stripes-module-parser.spec.js, test/webpack/stripes-serialize.spec.js, webpack/module-paths.js, webpack/stripes-branding-plugin.js, webpack/stripes-config-plugin.js, webpack/stripes-module-parser.js, webpack/stripes-serialize.js
There is a bit going on here. Much of the change results from a refactor to better share and test existing stripes-config logic. A quick summary:
**Changes to existing:**
* Move module parsing out of `stripes-config-plugin` and into new `stripes-module-parser` to make it more extensible
* Move serialization logic out of `stripes-branding-plugin` and into new `stripes-serialization` to reuse it with new icon metadata
* Consolidate on try/parse logic for locating modules from `module-paths`
* Add tests for `stripes-config-plugin` and new modules
**New functionality:**
* Add module's metadata as an export of `stripes-config` based on spec
* Icons are pulled in via require during serialization process like branding icons
* Build-time validation and warnings for icon metadata
**Example icon …
=> STCOR-139 metadata

src/components/MainNav/CurrentApp/CurrentApp.css, src/components/MainNav/CurrentApp/CurrentApp.js, src/components/MainNav/MainNav.js
As part of a continuing effort to improve the accessibility of STRIPES UI, this PR is an initial step in giving FOLIO modules a mark-up structure that outlines nicely so that assistive technologies can have a clean way to navigate the page via its heading tags.
Ideally, pages have a structure that flows in a hierarchical fashion - 
```
<h1>
<h2>
<h3>
<h2>
<h3>
<h4>
<h2>
```
It's best for pages to have only a single `<h1>` tag followed by `<h2-6>` tags arranged as seen in the example.
This GREATLY eases navigation for those using assistive technologies to perceive page content (and is a low-hanging fruit on the accessibility tree that sites can sometimes miss.)
There will be future PR's in other modules to set up a hierarchical flow to the headers used in an app. Much can be handled at the …
=> STCOR-159 Render current app as h1, setup default display

CHANGELOG.md, src/components/Root/Root.js, src/loginServices.js, src/okapiActions.js, src/okapiReducer.js
This turned out to be much more than the trivial fix I'd imagined, since Stripes was making no distinction between "I don't have a response to my first call _yet_" and "My first call failed". I had to add a new bit of state, `serverDown`, to the Redux store – which, as always, involved touching a whole bunch of files: `okapiActions.js` to define the `setServerDown` function that makes an action, `okapiReducer.js` to recognise that action and set the bit of state, `loginServices.js` to invoke that action when the initial call fails, and finally `Root.js` to emit the error message when this has failed. Oh, and the `CHANGELOG.md` of course.
Fixes STCOR-164.
=> When server is absent, say so instead of displaying nothing.

doc/adding-permissions.md
`curl` is much faster than installing Ruby and the Okapi CLI
=> add curl command

src/components/MainNav/CurrentApp/CurrentApp.css, src/components/MainNav/NavButton/NavButton.css
This minor update removes the NavButton labels on smaller screens. This isn't a perfect solution but it will do for now.
=> Minor tweak to hide NavButton labels on mobile

package.json
I was running into a very strange ESLint error:
```
import {
page
} from '@bigtest/interaction';
```
was throwing `Error while running ESLint: Cannot read property 'type' of undefined.`.
Upgrading `babel-eslint` fixed it, so there's no longer an error being improperly thrown.
=> Upgrade babel-eslint to 8.x

CHANGELOG.md, package.json
Eliminates a duplicate-package warning from WebPack.
Fixes part of STCOR-167.
=> Update react-cookie dependency

webpack/module-paths.js
Add another entry to the tryPath list to help locate modules in a yarn workspace
Fixes STCOR-170
=> STCOR-170 StripesBuildError with Yarn workspaces

src/index.js
stripes-cli will create an okapi key in the config with an empty object even if it was omitted from the configuration passed to it.
=> Consider empty okapi config as no okapi

src/index.js
`ui-eholdings` is broken on the latest `stripes-core`. Before starting up, `ui-eholdings` GETs `/eholdings/status` to verify it has an appropriate back-module in the Okapi cluster. Instead, it now GETs `/undefined/eholdings/status`.
The Okapi config was being blown away by https://github.com/folio-org/stripes-core/pull/239.
`Object.keys()` returns an array, so `Object.keys(anyObject) > 0` should always evaluate to `false`. Instead we want to be checking the length of `Object.keys()`.
=> Fix okapiConfig logic

doc/dev-guide.md
To help future developers to avoid my mistake. I tried to test connection between a back-end module in development and relative ui module without run all others back-end services up.
=> mandatory back-end services for stripes-core

webpack.config.cli.dev.js, webpack.config.cli.prod.js
The `importLoaders` property makes css-loader use the previous loaders in the webpack config's build chain when handling css files that are brought in within css files (via `@import` or use of the `compose` functionality between files)
This will allow for greater style re-use among components, since centralized style sheets can use some of the nice features (nesting, css-variables, etc) that `postcss` gives us. Component styles can use the `composes` command for cross-file style composition as follows.
```
.newTextFieldClass {
composes: sharedTextFieldClass from "../sharedStyles/centralizedStyles.css";
color: #fff;
}
```
This will automatically stack classes in the DOM so that `<tag class="newTextField---h^$# sharedTextFieldClass---h^$2 ">` affectively combining styles from both classes …
=> set importLoaders property in webpack config

CHANGELOG.md, package.json, webpack/apply-webpack-overrides.js, webpack/build.js, webpack/logger.js, webpack/module-paths.js, webpack/serve.js, webpack/stripes-branding-plugin.js, webpack/stripes-config-plugin.js, webpack/stripes-module-parser.js, webpack/stripes-translations-plugin.js
This adds the "debug" package, also used in the CLI, to provide better visibility into Stripes builds.  By default no additional output is given.  Output is enabled by setting the `DEBUG` environment variable and specifying a wildcard on the "stripes" namespace to get both stripes-cli and stripes-core logs.  
For example: `DEBUG=stripes* stripes build stripes.config.js`
STCOR-141
=> STCOR-141 instrument build with debug

CHANGELOG.md, package.json, src/components/GlobalErrorBoundary/GlobalErrorBoundary.js, src/components/GlobalErrorBoundary/index.js, src/components/Root/Root.js, src/connectErrorEpic.js
STCON-67 turns off the `alert()` box when [using the `throwErrors` prop implemented here](https://github.com/folio-org/stripes-connect/pull/44). 
STCOM-150 adds [an Error Boundary at the top-level of the application.](https://reactjs.org/docs/error-boundaries.html). Error boundaries let us catch errors thrown _only_ in render() or lifecycle methods. 
React 16 unmounts the component tree when errors are thrown rather than operating in an unstable state, so error boundaries give us the opportunity to introduce a fallback UI. Contrary to what I initially thought, they are not intended to be used as a mechanism to trap errors and return to a stable state. That's why `GlobalErrorBoundary` is fairly dumb and just reports the error and doesn't do anything interesting.
=> STCON-67 && STCOM-150 Error Boundary

src/components/OverlayContainer/OverlayContainer.css
OverlayContainer's children were stealing all pointer-events. This made us unable to interact with the page at all, giving the impression that the page had frozen.
This wasn't manifesting in (my) local builds, only on folio-testing. In local builds, `.callout`'s `pointer-events: none` rule won out while in folio-testing `overlayContainer>*`'s `pointer-events:all` rule won out. 
I can't say for certain why the rules were non-deterministic, but my best guess is that since the specificity was the same, the order that the rules were squashed together by Webpack was the deciding factor. I confirmed that the `style.{...}.css` bundle created for folio-testing _did_ have the `:all` rule later in the file so that's the explanation I'm rolling with.
=> STRIPES-528 OverlayContainer: removed enabling of pointer-events for children

CHANGELOG.md, package.json, src/discoverServices.js
Retrieve module info in one request, instead of one request per module.
This is vastly more performant.
Fixes [STCOR-200](https://issues.folio.org/browse/STCOR-200).
=> retrieve module info in a single request

doc/i18n.md
For most of the project, we use `this.props.stripes.intl`. It's much more versatile to retrieve `intl` from context, which is what `react-intl` components do (like [`<FormattedMessage>`](https://github.com/yahoo/react-intl/blob/f82383e02cb0d38dfd28649dc2442a2ea2796a44/src/components/message.js#L19)).
=> doc: intl from context

CHANGELOG.md, util/pull-stripes
Is `ui-vendors` enough of a core repository that we should include it in `pull-stripes`? Seems like "yes" to me.
=> include ui-vendors in pull-stripes

CHANGELOG.md, src/RootWithIntl.js, src/components/Login/Login.js, src/components/Login/LoginCtrl.js, translations/en.json
Thread the `stripes` object through to the login page so we can
translate its embedded strings.
Fixes [STCOR-213](https://issues.folio.org/browse/STCOR-213).
=> translate login page

CHANGELOG.md, package.json
This is merely follow through for work done in [UIU-495](https://issues.folio.org/browse/UIU-495), which allowed a deprecated field to be removed.
=> update Okapi deps WRT proxy.meta deprecation

src/components/About/About.js, translations/de.json, translations/en.json
Addressing Julian's [comment](https://issues.folio.org/browse/STCOR-196?focusedCommentId=30143&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-30143) to translate the module types (_app_, _settings_, and _plugin_)
=> translate module types on About page

src/locationService.js
Fixes https://issues.folio.org/browse/STCOR-220
When `dataKey` is used for given `module` all resources in redux store are prefixed with `dataKey#`. For example:
`patrons#folio_users_records`
The previous implementation was missing `#` so it would try to retrieve a wrong key:
`patronsfolio_users_records`
=> Fix prefix when retrieving query resource key. Fixes STCOR-220

package.json, webpack.config.cli.prod.js, webpack/babel-loader-rule.js
`ui-eholdings` has been adding two babel plugins for a while in a [`.stripesclirc.js`](https://github.com/folio-org/ui-eholdings/blob/master/.stripesclirc.js):
`ui-eholdings` makes use of decorators in the "interactors" for UI tests. Example: https://github.com/folio-org/ui-eholdings/blob/master/tests/pages/datepicker.js. `ui-eholdings` only adds this plugin in the `test` environment, but I don't see any harm in adding it for all builds.
Used to remove `data-test` and `data-test-*` attributes from production builds. `ui-eholdings` relies on `data-test-*` attributes for UI testing instead of IDs (with some exceptions). There were discussions recently about taking this approach in more of the `stripes` ecosystem. This won't break any existing tests using IDs, but will make `data-test` …
=> STCOR-221 Add babel plugins

src/locationService.js
https://issues.folio.org/browse/STCOR-223
@zburke and @aditya-matukumalli would you mind taking quick look at this? Also if you could checkout that branch and test it out that would be great! 
@aditya-matukumalli you should be able to remove `query=` from https://github.com/folio-org/ui-checkout/blob/master/lib/ViewItem/ViewItem.js#L126 and https://github.com/folio-org/ui-checkout/blob/master/lib/ViewItem/ViewItem.js#L133 and ideally everything should still work.
=> Remove empty params during transitioning. Fixes STCOR-223

index.html, src/loginServices.js
So that assistive technology can pick up on which language the document should be read in, the language code should be indicated in the html as a `lang` attribute on the `<html>` tag.
https://www.w3.org/International/questions/qa-html-language-declarations
This is set to "en" as default in the base index.html of stripes-core, which is updated later once the locale information loads from okapi. 
Corresponds with another PR on `ui-org` for when the locale is changed. https://github.com/folio-org/ui-organization/pull/72
=> STCOR-207 Set document lang attribute for assistive technology

doc/i18n.md
Three key things:
1. Updates the translation file paths.
2. Makes it clear that it's up to individual module developers to follow the pattern of exchanging date/times with the server only in UTC.
3. "Retrieving the `intl` object from `this.context.intl` or `this.context.stripes.intl` is a deprecated pattern." Most of the edits revolve around encouraging direct use of `react-intl` components and API, instead of being filtered through the `stripes` object.
Best practices for time zones.
=> Update i18n docs

src/StripesContext.js
`props` is undefined in class `render` methods so using `withStripes` stripes all props from the wrapped component currently. This correctly passes them along.
=> StripesContext: Pass along this.props

doc/app-metadata.md, doc/dev-guide.md, src/ModulesContext.js, src/RootWithIntl.js, src/components/About/About.js, src/components/MainNav/CurrentApp/CurrentApp.js, src/components/MainNav/MainNav.js, src/components/ModuleTranslator/ModuleTranslator.js, src/components/ModuleTranslator/index.js, src/components/Modules/index.js, src/components/Modules/withModule.js, src/components/Modules/withModules.js, src/components/Root/Root.js, src/components/Settings/Settings.js, src/components/TitledRoute/TitledRoute.js, src/gatherActions.js, src/loginServices.js, src/moduleRoutes.js, translations/stripes-core/de.json, translations/stripes-core/en.json, webpack/stripes-config-plugin.js
**Updated**
- ModulesContext.js creates a React Context of modules. The modules are originally pulled from the `stripes-config` virtual module and then translated by `RootWithIntl`. In the future, the actual translation work can get pulled out into another component but I'm tempted to leave it as-is atm because the translation of icons and permission sets may change where/how we want to do it.
- `stripes-core` now provides `withModule` and `withModules` HOCs. The latter provides all the translated modules, while the former takes either a module name or a `mapStateToProps`-y callback (with props as the arg) that returns the module name, and returns just that module.
- `SearchAndSort` is an example of an app that makes us of that mSTP format.
- Various pages updated to remove their …
=> STCOR-226: Add ModuleContext which stores i18n'd module metadata

src/loginServices.js
Previously wasn't including the new info in the Okapi session that gets persisted to local storage. This fixes that.
=> Include user id/name in the session object

webpack.config.base.js
After merging https://github.com/folio-org/ui-organization/pull/88, the deprecated `ui-okapi-console` is the only `folio-org` repo still using `stripes-loader` instead of `stripes-config`.
=> Remove stripes-loader alias

src/components/MainNav/MainNav.js, src/components/Root/Root.js, src/locationActions.js, src/locationService.js
This PR takes `modules.settings` into consideration when searching for correct/current module. This together with: 
https://github.com/folio-org/stripes-core/pull/350
is a part of the work needed in order to support anointed resources on settings pages.
=> Add support for anointed resource in settings. Part of STCOR-231

package.json
Follow-up to https://github.com/folio-org/stripes-core/pull/353: we shouldn't have any more surprise rule changes with `eslint-config-stripes`, thanks to https://github.com/folio-org/eslint-config-stripes/pull/33
=> Upgrade to eslint-config-stripes 2.0.3

CHANGELOG.md, test/webpack/stripes-branding-plugin.spec.js, webpack/stripes-branding-plugin.js, webpack/stripes-webpack-plugin.js
The favicons-webpack-plugin introduced during the Webpack 4 upgrade has contributed to increased build times due to the large number of icons it generates by default.
With this change, a minimum configuration is passed to favicons-webpack-plugin during non-production builds reducing build time by approximately 10%.   Production builds continue to receive the default settings, which are now explicitly defined.
See STCOR-232 for more details.
=> STCOR-232 Change favicon settings to reduce dev build time

CHANGELOG.md, package.json
Update react-intl-safe-html version to make sure the latest patch release is included in platform builds.  Related to STRIPES-545
=> STRIPES-545 Update react-intl-safe-html version

src/components/MainNav/MainNav.css
The MainNav is on top of all other content but because the BG color had opacity it was looking a bit odd when the backdrop of e.g. a Modal is visible:
I updated the BG color to it's HEX equivalent to make it look right:
**Note:** Currently the color is "hardcoded". We would probably need to change it to a variable instead. This is the only place we use this color.
=> Changed MainNav bg color to HEX instead of RGBA

src/components/Settings/Settings.js, src/components/TitledRoute/TitledRoute.js
@doytch this PR moves the `connect` in `<Settings/>` from render into constructor. Also while chasing multiple re-mounting I noticed that switching from `component` to `render` in `TitledRoute` limits it to a single remount.
=> Fix re-mounting in settings

src/components/Settings/Settings.css, src/components/Settings/Settings.js
This margin matches the rest of the settings panes which uses the `<Settings>`-component from stripes-components.
=> Replaced <br>'s with margin-bottom in Settings

examples/trivial-okapi/TenantList.js, src/StripesContext.js
While writing tests for the `<AppIcon />` component I needed to pass a mock stripes object to the component in order to achieve 100% test coverage.
This was not possible because it got overwritten in the StripesContext HOC and set to `undefined` because of the missing context in the tests/storybook environments.
This PR adds a simple change that allows for passing the stripes-prop manually in cases where the context isn't available.
=> Prefer stripes prop if provided in StripesContext

src/loginServices.js
I'll explain this backwards:
- Translation strings weren't being shown for non-English languages. We'd either show the label ID (`ui-users.meta.title`) or the original English string. These are the fallback strings.
- The fallback strings were showing because `react-intl` was giving us an empty `messages` array [at this line](https://github.com/yahoo/react-intl/blob/763f3fcbf87abc1a2a1021f684217f56bf8d4581/src/components/provider.js#L134).
- Scroll up from that line and you'll see it was giving us an empty `messages` array because it didn't have locale data for the currently selected locale.
- So why don't we have all the locales loaded into react-intl when we clearly call `addLocaleData` at loginServices.js:36? `import` returns a `Module` object, not the default export. It's behaving …
=> FOLIO-1422 i18n: Index into locale-data module for locales array

test/webpack/stripes-module-parser.spec.js, webpack/stripes-module-parser.js
That allows having 'settings' type modules without app which is vital for testing settings type modules with BigTest.
=> STCLI-91: Add default default value for app modules in allModuleConfigs.

src/Pluggable.js
`Pluggable` doesn't meet the definition of a purely presentational component (https://issues.folio.org/browse/STCOM-298), since it's coupled to `stripes-config`. Its most logical new home is in `stripes-core`.
https://issues.folio.org/browse/STCOM-331
Used `git-subtree` to preserve as much git history for these files as possible from `stripes-components`.
=> STCOM-331 Move Pluggable

CHANGELOG.md, package.json, src/components/HandlerManager/HandlerManager.js, src/events.js, src/loginServices.js, src/okapiActions.js, src/okapiReducer.js
This is needed for UIU-551. 
We want to show the `ServicePointsModal` from `ui-servicepoints` whenever a user edits themselves in the Users app. This required a few changes:
- New actions/reducers in Redux.
- Exposing those via `loginServices`
- Passing props to a handler component returned from `HandlerManager`.
=> UIU-551: Added actions/reducers to set the current user's service points

CHANGELOG.md, src/events.js
The reason for using strings instead of numbers is because we use strings here:
https://github.com/folio-org/ui-servicepoints/blob/master/package.json#L20
=> Refactor handler events to strings. Part of UIU-551.

CHANGELOG.md, package.json
mod-login-saml has been updated to require the new authtoken interface,
but mod-login has not. Thus, we need to support both interfaces.
Refs [STCOR-76](https://issues.folio.org/browse/STCOR-76)
=> support old and new authtoken interfaces

CHANGELOG.md, package.json, src/components/Root/Root.js, util/dateUtil.js
With `react-intl@2.5.0`, the `<IntlProvider>` can now accept a `timeZone` prop.
Part of https://issues.folio.org/browse/STCOM-344
- The `stripes-components` `<Datepicker>` and `<Timepicker>` will no longer need to use `withStripes` - instead they can get `timeZone` directly from the `intl` object.
- I updated a few utils to camel case `timeZone`, but left alone the places where it would be a breaking change.
- Accessing `stripes.timezone` still works for modules consuming it that way.
=> STCOM-344 Expose timeZone through react-intl provider

CHANGELOG.md, index.js
I poked around the `folio-org` to see what other repos are importing from `stripes-core`. Those have been added here.
Putting these in an index forces us to think about `stripes-core`'s external API.
Encourages:
```
import { TitleManager } from '@folio/stripes-core';
```
instead of 
```
import TitleManager from '@folio/stripes-core/src/components/TitleManager';
```
Consumers of `stripes-core` APIs shouldn't need to know the directory structure.
=> Start exporting things

CHANGELOG.md, package.json, src/components/LastVisited/LastVisitedContext.js, src/components/LastVisited/index.js, src/components/LastVisited/withLastVisited.js, src/components/MainContainer/MainContainer.js, src/components/MainNav/MainNav.js
@zburke and @MikeTaylor this is another attempt to solve [STCOR-254](https://issues.folio.org/browse/STCOR-254) by extracting `lastVisited` into a separate HOC module and make it available via react context. This would allow us to update the `lastVisited` from stripes-form which is illustrated here:
https://github.com/folio-org/stripes-form/pull/32/files
I'm still not sure about some of the naming conventions. For example the context is exposing `goBack` but we are not really going back when we call it. We are just updating `lastVisited` for the current module to the previous path.
=> Extract lastVisited into a separate higher order component. Part of STCOR-254

index.js
This missing export was found while consuming `stripes-*` modules via `stripes` (the framework) from within `ui-users`.  Related to STRIPES-547
=> Add HandlerManager to exports

.circleci/config.yml, CHANGELOG.md, karma.conf.js, package.json, src/AppContainer.js, src/HotApp.js, src/RootWithIntl.js, src/components/MainNav/MainNav.js, src/index.js, webpack/babel-loader-rule.js
With the setup changes from https://github.com/folio-org/stripes-core/pull/430, we can now use [`react-hot-loader`](https://github.com/gaearon/react-hot-loader) when running `yarn start` with `stripes-core`:
A three line-change in each UI module will activate their ability to take advantage of hot reloading too (I'll open some PRs to demonstrate after this merge).
=> Turn on react-hot-loader

doc/release-procedure.md
New modules should not start with a 0.x.y version because it causes
confusion. Confusion is bad.
Refs [STCLI-105](https://issues.folio.org/browse/STCLI-105)
=> add "start at 1.0.0, not 0.1.0" explanation

src/HotApp.js, src/components/Root/index.js, src/index.js
Moved the `hot()` down the component stack a little.
These calls would fire on every hot reload:
https://issues.folio.org/browse/STCOR-257 will take of the notifications calls. Looks like the tenant modules call might need to be pulled higher up in the component hierarchy.
=> Slim down hot reloading server calls

test/bigtest/helpers/setup-application.js, test/bigtest/network/boot.js, test/bigtest/network/index.js, test/bigtest/network/start.js
This makes it so other modules can utilize the `setupApplication` helper and provide their own mirage configuration that would extend the core mirage configuration.
With this change, modules can just use the `setupApplication` helper directly to setup a full stripes app in testing. If the module needs to setup it's own mirage configuration, it can be provided to the `setupApplication` helper as `mirageOptions`.
```js
import setupStripesCore from '@folio/stripes-core/test/bigtest/helpers/setup-application';
import mirageOptions from '../network';
export default function setupApplication({
scenarios
} = {}) {
setupStripesCore({
mirageOptions,
scenarios
});
}
```
The new `network/start` merges additional options into the core config options. This is so modules do not have to repeat any …
=> Extend mirage start helper to allow additional options

CHANGELOG.md, package.json, src/components/Front.css, src/components/MainNav/CurrentApp/CurrentApp.css, src/components/MainNav/NavButton/NavButton.css, src/components/MainNav/NavDropdownMenu/NavDropdownMenu.css
Adopts the type variables introduced in https://github.com/folio-org/stripes-components/pull/627
=> Use new type stack

src/RootWithIntl.js
`key={Math.random()}` was preventing this from appearing in the console: `Warning: You cannot change <Router history>`; but that warning does not appear to actually affect any functionality.
=> Remove HMR router hack

src/App.js, test/bigtest/helpers/setup-application.js
https://github.com/folio-org/ui-myprofile/pull/31 encountered an error where a component was attempting to access `stripes.user.user.username` when `stripes.user.user` was undefined.
This stripes property is populated via  the `Login` component either automatically or when manually logging in. When using `disableAuth` the `\login` route and `Login` component is never mounted, so the store's `currentUser` always ends up empty.
Instead of using `disableAuth`, supply the initial state of the store with fake user data, including a fake token, and `perms.all`.
I assume `perms.all` should be the only permission necessary, but looking at dev and production admin accounts shows a lot more perms. Do I need to include any other permissions?
=> Fix currentUser error in tests

test/bigtest/network/start.js
While `ui-eholdings` was being upgraded with the new `stripes-core` test helpers, it was discovered that all fixtures were being loaded when they previously weren't.
We manually load factories because Mirage only loads them conditionally. By not providing mirage with any factories, it defaulted to auto-loading all fixtures.
Omit fixtures from Mirage initialization and manually add them afterwards. This prevents them from being automatically loaded by mirage.
=> Prevent mirage from auto-loading fixtures

src/components/MainNav/MainNav.css, src/components/MainNav/MainNav.js
On small screens there's white space to the right of the layout:
Upon investigation, it was an `<h2>` only meant for screen reader consumption:
It still had some layout, so it pushed out the width of the page.
I tried a different CSS approach for hiding the "Main Navigation" headline while keeping it in the screen reader context. It also didn't need to use the `stripes-components` `<Headline>`.
=> Update CSS for hidden navigation headline

util/dateUtil.js
Instead of constructing our own datetime string with a whitespace character, rely on `react-intl`'s construction with `<FormattedTime>`.
For US English, it will add a comma as a separator.
=> STCOR-267 Lean on react-intl FormattedTime for datetime construction

CHANGELOG.md, src/components/Login/Login.js
When typing in a username on iOS, it would automatically capitalize the first letter:
`autoCapitalize="none"` turned that off.
=> Turn off autoCapitalize on login form

CHANGELOG.md, util/dateUtil.js
The `stripes` god object duplicates functionality that can be used directly from `react-intl`. We should lean on the community-supported solution instead of our own tunnel of it.
=> STCOR-267 Deprecate stripes intl utilities

webpack/babel-loader-rule.js
This excludes folio/react-big-calendar from being transpiled during a platform build, like we do with folio/react-githubish-mentions.
=> FOLIO-1570 exclude folio/react-big-calendar

webpack/babel-loader-rule.js
Reverts folio-org/stripes-core#468
We need more information before implementing this. See UICAL-46
=> Revert "FOLIO-1570 exclude folio/react-big-calendar"

test/bigtest/network/patch-response-url.js, test/bigtest/network/start.js
`stripes-connect` uses `response.url` to validate requests. Pretender, which is used by Mirage, does not add the `responseURL` property so that the fetch polyfill works correctly.
The previous workaround was to use the `X-Request-URL` header in the response, this patch makes it so that is no longer necessary.
Took @cowboyd's work over on `ui-inventory` to patch this property and included it here so all modules can use it until [these changes](https://github.com/pretenderjs/FakeXMLHttpRequest/pull/43) make it back to `bigtest/mirage`.
=> Patch response url in mirage for stripes-connect

src/components/MainNav/AppList/AppList.css, src/components/MainNav/AppList/AppList.js
Regarding [STCOR-269](https://issues.folio.org/browse/STCOR-269) the dropdown with possible applications should not have a scroll till its height equals screen's height, the scroll should appear only if the dropdown's height more than screen's.
- Remove set max-height, redefine paddings for the dropdown.
- Add constraints to tether props for fixing position of the dropdown.
=> [STCOR-269] Fix dropdown behavior

CHANGELOG.md, package.json
* Turn off autoCapitalize on login form
* Deprecate stripes intl utilities, STCOR-267
* Set alt="" on app icons in MainNav (STCOR-274)
* Updated color of text in profile dropdown (STCOM-377)
* Patch response url in mirage for stripes-connect
=> Release v2.15.5

CHANGELOG.md, src/components/Root/Root.js
By setting the `textComponent` prop on the `IntlProvider` to `Fragment`, internationalized strings using `<FormattedMessage>`, etc. will render as `<Fragment>` instead of `<span>`. Should make for much easier DOM to work with (and make passing a `<FormattedMessage />` to an `<option />` possible).
=> Set textComponent on IntlProvider

CHANGELOG.md, src/components/MainNav/MainNav.js
In certain cases, `.startsWith` wasn't accurate enough to determine what app was open. 
- `ui-erm` is defined with its `route` as `/erm`. 
- `ui-erm-usage` is defined with its route as `/ermusage`
- When `ui-erm-usage` is opened, the code would check that the current pathname (`/ermusage/...`) started with the various app's routes to check which one was now open.
- Both `ui-erm` and `ui-erm-usage` will be marked as `active` when we loop through the modules.
- Strictly compare the second token of the `.split('/')` pathname.
- Note that even when we load the root page (e.g., `localhost:3000`), the pathname will be `/`, and `'/'.split('/')` _does_ return an array of size two, so that `[1]` indexing will not fail and doesn't need to be checked. Perhaps, dear reader, you already knew this, but …
=> ManNav: Fixed bug where multiple apps could be selected

src/components/MainNav/MainNav.js, test/bigtest/helpers/setup-application.js
[UIEH-570](https://issues.folio.org/browse/UIEH-570) - eHoldings tests are flakey due to memory issues.
After some investigating, this turned out to be caused by a few different things each retaining some amount of memory.
1. The biggest memory leak which contributed the most was due to redux `store` subscribers not being properly cleaned up. This caused a _significant_ amount of memory to leak, as each subscriber held a reference to the component, which holds a reference to the entire react tree it is mounted in. So in turn, each call of this subscriber was leaking the entire stripes application including all submodules.
The subscriber in `MainNav.js` was the location of the biggest leak. [Over in `stripes-connect` there is a similar …
=> Fix memory leaks

CHANGELOG.md, src/RootWithIntl.js
https://issues.folio.org/browse/STRIPES-578
It looks like based on the work in STCOR-273 (https://github.com/folio-org/stripes-core/commit/fed3d67d888160016aaaea1dcab00d5dd438a316#diff-88ca151ca66140fa7627a68e749b47e6) 
the `stripes` has been moved to the constructor.  Unfortunately `RootWithIntl` is being constructed before the user and permissions are available so the `this.stripes` ends up without them in `render`. 
This PR clones the `user` from current `stripes` object in `componentDidUpdate ` in order to fix it. 
@OleksandrAntonenko1 apologies for stepping on your toes here. We can improve this later but we want to cut a new release of stripes-core today with some other fixes in place.
=> Keep stripes user up to date. Fixes STRIPES-578

src/RootWithIntl.js
The refactoring in #480 means the `this.stripes` object may not be fully
populated. This adds `discovery`, but a larger refactoring may be in
order here.
Refs [UIU-712](https://issues.folio.org/browse/UIU-712)
=> add missing discovery attribute to stripes

src/components/MainNav/AppList/AppList.css, src/components/MainNav/AppList/List.js
According to [STCOR-277](https://issues.folio.org/browse/STCOR-277), descriptions in app header dropdown do not provide a vague explanation of the app, therefore they should be removed, taking into account the dropdown still should stay responsive.
=> STCOR-277: Remove description from App header dropdown

CHANGELOG.md, src/RootWithIntl.js, src/components/CreateResetPassword/CreateResetPasswordControlWrapper.js, src/components/CreateResetPassword/index.js
The work done in support of STCOR-273 refactored how the `stripes`
object available in `render()` was initialized. By moving the
initialization and cloning up to the constructor, it wasn't updated when
user permissions, among other attributes, were added to the object.
Previously, because the object was cloned in `render()`, these
attributes were always available, but relocating the clone operation to
the constructor means these updates never trickled down.
This problem was captured in STRIPES-578 and patched, but there were
lingering issues as noted in STCOR-283. So _this_ refactor restores the
clone operation to `render()`, ensuring that all and any important
attributes, not just those called out in `componentDidUpdate()`, trickle
down to the `stripes` object used there.
It works by …
=> keep stripes object up to date after login

src/components/Notification/ToastNotification.js
SonarCloud scan picked this up as a "bug".
The ternary was returning the exact same thing in both conditions.
=> Remove unnecessary typeof check

CHANGELOG.md, src/loginServices.js
react-intl expects locales to look like `pt-BR`, i.e. a locale, a hyphen,
and a region code. lokalise.com provides translation files with names
like `pt_BR.json`, i.e. a locale, an underscore, and a region code. In
other words, the two systems we use for managing translations DON'T KNOW
HOW TO TALK TO EACH OTHER. For reals.
Regardless, the old code threw away region codes altogether, so it
didn't really matter that they couldn't talk because they weren't even
trying. Now, we translate the dash to an underscore in order to look up
the locale + region and use that if available, and fall back to the
locale-only, which is what we used to do, otherwise.
Fixes [STCOR-261](https://issues.folio.org/browse/STCOR-261)
=> load region-specific translations if available

CHANGELOG.md, webpack.config.cli.dev.js, webpack.config.cli.prod.js
**Issue:** https://issues.folio.org/browse/STCOR-260
CSS variables were preserved in the CSS output which was causing issues with CSS variables that were using color-functions since these aren't supported in browsers natively and it would overwrite with invalid values.
Setting `preserve: false` in the config of PostCSS plugin `postcss-custom-properties` we only get the transpiled output.
This would need to be turned on again if/when we, later on, want to introduce theming using CSS variables. 
For this to work, however, we would either need to stop using color functions in our CSS _or_ update the webpack setup to make sure that the values of CSS variables that are using the color functions are transpiled.
=> STCOR-260: Disable css variable preservation

test/bigtest/tests/forgotPassword-test.js
`ForgotPassword` defines `ForgotPasswordInteractor`, not
`ForgotUsernameInteractor`.
=> fix the import classname

src/components/Login/Login.js
Use `to` to generate a `<Link>`; `href` generates an `<a>` wrapper that
treats the target as an external link, refreshing the entire page.
=> prefer to over href in button links

src/components/MainNav/AppList/AppList.css, src/components/MainNav/AppList/AppList.js
I noticed that the app list dropdown had a bit too much padding, it was cropping active/focus styles and it would scroll the inner element instead of the outer element. In this PR I fixed that.
=> Minor app list dropdown update

package.json, test/bigtest/helpers/setup-application.js, webpack.config.base.js
Since `typeface-source-sans-pro` package is not used after [this merge](https://github.com/folio-org/stripes-components/pull/765), it should be removed from our webpack config.
[Related story](https://issues.folio.org/browse/STCOR-299)
=> STCOR-299: remove typeface-source-sans-pro from webpack config

src/components/CheckEmailStatusPage/CheckEmailStatusPage.js, src/helpers/hideEmail/hideEmail.js, src/helpers/hideEmail/index.js, src/helpers/index.js, translations/stripes-core/en.json
<li>To hide an email presented on Check email screen</li>
<h1>Approach</h1>
<li>To create a helper function which replaces all the required symbols with a default '*' sign</li>
<h1>Screenshots</h1>
<li>Expected behavior</li>
=> STCOR-305: email hidden on Check email screen

index.js, src/components/IntlConsumer/IntlConsumer.js, src/components/IntlConsumer/index.js
There are still some cases where `intl.formatMessage()` is necessary for translating strings. in-step with react-intl's hopeful transition to React's updated context API, we can make things a bit cleaner for parts of our UI to access intl in a declarative way without having to dress up in the injectIntl HOC. MCL Column mapping is the primary use-case where `<FormattedMessage>` leaves us hanging since multiple strings are necessary.
The `<IntlConsumer>` component helps with this issue. ex: 
```
import { IntlConsumer } from '@folio/stripes/core';
<IntlConsumer>
{ intl => (
<MultiColumnList
{ ...other }
columnMapping={{
status: intl.formatMessage({ id: 'ui-users.active' }),
name: intl.formatMessage({ id: 'ui-users.information.name' }),
barcode: intl.formatMessage({ id: …
```
=> STCOM-399 Intl approach

src/components/About/AboutEnabledModules.js
The missing space between the server-side module names and their
versions was a cause of great pain and suffering unlike the world has
ever known, a plague upon the landscape, a pox upon the screen. Children
wept when reading the 'Software versions' page. Animals cowered. A
maple outside my window dropped its leaves in August, and an evergreen
shed its needles.
You think you're hot stuff, ESLint, but I have only one word for you and
it's this: "open-curly-single-quote-space-single-quote-space-close-curly"
is not clearer than "space" and if you think it is then you better not
be bothered that this was more than one word.
=> restore one missing space

CHANGELOG.md, webpack/stripes-translations-plugin.js
Include `en.json` as the base for all translations so that keys missing
from a locale file but present in the `en.json` file will show the value
from the `en.json` file rather than the key. This will allow developers
to add pairs to the `en.json` file and have the values immediately show
up in the UI regardless of locale.
Fixes [STCOR-310](https://issues.folio.org/browse/STCOR-310)
=> provide default translations from en.json

CHANGELOG.md, webpack/stripes-translations-plugin.js
Reverts folio-org/stripes-core#559
I'm not yet sure how, but this PR seems to have caused a tiny little itty bitty problem with the UI where translation values for all locales were written out in Chinese. All of them. ALL OF THEM. 
Maybe this was array iteration goof with the final element, zh_CN, overwriting the rest? I can't see how that happened, and yet:
=> Revert "provide default translations from en.json"

src/components/About/About.js
This looks like another victim of ESLint appeasement where something
totally reasonable like
return (<li>{foo} ({bar})</li>)
got mangled trying to appease ESLint. If bar is a FormattedMessage and
the string got changed to `<li>${foo} (${bar})</li>` then bar would
appear as `[object Object]` because it's a FormattedMessage object, not
a string. YAY ESLint you stupid little something something.
=> don't interpolate FormattedMessage

CHANGELOG.md, webpack/module-paths.js
The previous work for STCOR-304 did not consider the need to locate Stripes framework in a workspace preventing some `stripes-*` modules from being located if yarn did not happen to hoist them.  This resulted in things like translations for stripes-smart-components not being found.
This solution extends the previous work by also considering the framework's node_modules path starting from one level up (in the workspace).  The whole path logic is due for review as a few issues brought about by workspaces and/or hoisting have come up recently.  Fortunately such path needs should already be funneled through this file simplifying a future refactor.
=> STCOR-323 workspace node_modules fallback

index.js, src/components/index.js
Public exports need to happen at the top level of the package.
#567 added `<AppIcon>` but only exports it within `src/components`. It needs to be a top-level export, like `<IfInterface>`, `<IfPermission>`, and `<Pluggable>` to be importable like 
```
import { AppIcon } from '@folio/stripes/core';
```
as suggested in folio-org/stripes-components/pull/826.
=> correctly export AppIcon

src/components/MainNav/AppList/AppList.css
After an update in stripes-components the padding inside the app list dropdown was a bit off.
=> Minor padding adjustment for app list dropdown

CHANGELOG.md, src/components/MainNav/MainNav.js, src/locationService.js
This PR fixes the issue described in https://issues.folio.org/browse/STCOR-339:
It looks like every time we open FOLIO via direct link to any settings form and we try to cancel the form the navigation is not responding.
Steps to reproduce:
1. Open any form directly in the browser. For example: http://folio-testing.aws.indexdata.com/settings/organization/servicePoints?layer=add
2. Click 'X' to close the form 
3. The form stays open until second click on 'X'
=> Set current query to a correct value during initial page load. Fixes STCOR-339.

src/locationService.js
I discovered this bug while working on https://github.com/folio-org/stripes-smart-components/pull/429
In some cases the navigation would end up in the infinite loop causing rendering to completely hanged.
=> Fix updateLocation's return statement. Part of STCOM-302

test/bigtest/helpers/setup-application.js
In UICHKIN-53 I need to be able to switch between different service points as a logged in user. This PR allows for extending currentUser object by passing it to BigTest's `setupApplication` as a param.
=> Add ability to configure current user. Refs UICHKIN-53.

webpack/stripes-duplicate-plugin.js
This configures the `stripes-duplicate-plugin` to error when duplicate `stripes-*` modules are present in a bundle.  Doing so, for `stripes-components` at least, should catch one source of rendering errors before they make it into a bundle.  This has been run locally with success on `platform-core` and `platform-complete`.
=> STCOR-222 error on stripes duplicates

CHANGELOG.md, src/components/MainNav/AppList/AppList.css, src/components/MainNav/AppList/AppList.js
This PR fixes an odd issue of horizontal/vertical scrollbars appearing unnecessarily when opening the app list dropdown in browsers on Windows.
The issue turned out to be a bit of missing CSS in the class name that was responsible for hiding the focus traps (inputs) while still making them able to catch the focus.
I replaced the class with the global "sr-only" (screen reader only) class which offers the same functionality but slightly better and that fixed the issue.
=> STCOM-461: Fixing app dropdown "jitter"

CHANGELOG.md, package.json
Caret dependencies are too loose in the context of releasing a platform
and allow new minor release to "leak" up into a platform where the
differing versions can cause duplication errors.
Refs [STRIPES-608](https://issues.folio.org/browse/STRIPES-608)
=> make stripes dependencies more strict

package.json
The version on master must always be >= that of the version on a branch.
Otherwise, repos that update to a patch release (from a branch) may be
prevent from using the tip-of-master version provided in their
workspace.
=> sync master version with releases from branches

src/components/MainNav/MainNav.js
`context.router` doesn't exist and apparently it was meant to be a private API so we shouldn't have ever been using it.
Instead, use `props.history` provided by [`withRouter`](https://reacttraining.com/react-router/web/api/withRouter)
=> STRIPES-614: Fixed logout throwing errors

CHANGELOG.md, src/components/MainNav/ProfileDropdown/ProfileDropdown.js
Pulling `router.history` off `context` is a bad idea. As noted at
https://github.com/ReactTraining/react-router/issues/6630#issuecomment-473946064,
that's the internal API, not intended for public consumption, and it
caused Nightmare 3.x to barf.
Refs [STCOR-355](https://issues.folio.org/browse/STCOR-355)
=> don't use react-router's private API

src/components/Root/Root.js
This addresses this warning:
```
Warning: Please use `require("history").createBrowserHistory` instead of `require("history/createBrowserHistory")`. Support for the latter will be removed in the next major release.
```
=> Update import of createBrowserHistory to avoid deprecation

index.js, package.json, src/components/Root/Root.js, src/components/Root/RootContext.js
We don't like circ-deps. The changes in this PR are much smaller than that of #644 But the downside is the necessity that only one `stripes-connect` exist in a bundle.
On the stripes-core side, this merely means importing the ConnectContext from `stripes-connect`, and using its `Provider` in place of its own `RootContext.Provider`.
=> STCON-76 Option #2 - use ConnectContext Provider

webpack/stripes-module-parser.js
This is some temporary hardcoding until we have STRIPES-148 providing
this in general for all modules.
=> Load @folio/notes as both app and plugin STCOR-357

src/stripesConnect.js
`stripesConnect` would be really useful if this worked: 
```
export default stripesConnect(Container, { dataKey: "search_items" });
```
but the `options` object passed in gets ignored.
This PR puts us in business there.
=> `stripesConnect` HOC missing options parameter :O

.babelrc, .gitignore, CHANGELOG.md, package.json, src/components/Root/Root.js, src/loginServices.js, test/bigtest/helpers/setup-application.js
- Fulfills [STRIPES-564](https://issues.folio.org/browse/STRIPES-564) and [STRIPES-581](https://issues.folio.org/browse/STRIPES-581).
- Turned off sideEffects for all non-CSS files and switched bundle output from commonJS to ES Modules to support tree-shaking.
- Since ES Modules don't allow overriding or stubbing imports, added `defaultTranslations` as a prop to allow BigTests to continue to pass.
- Added /dist directory to .gitignore.
- Ran bundle analyzer on a hello world UI app to compare bundle sizes.
Before:
After:
=> Stripes 564 verify tree shaking

package.json, src/StripesContext.js, src/components/LastVisited/withLastVisited.js, src/components/MainNav/CurrentApp/AppCtxMenuContext.js, src/components/Modules/withModule.js, src/components/Modules/withModules.js, src/stripesConnect.js
Hoist static assignments from the wrapped component to the exported one.
Huh? Hoist the whatnow? Now hear this:
https://reactjs.org/docs/higher-order-components.html#static-methods-must-be-copied-over
> Sometimes it’s useful to define a static method on a React component. For example, Relay containers expose a static method getFragment to facilitate the composition of GraphQL fragments.
> 
> When you apply a HOC to a component, though, the original component is wrapped with a container component. That means the new component does not have any of the static methods of the original component.…
>
> You can use [hoist-non-react-statics](https://github.com/mridgway/hoist-non-react-statics) to automatically copy all non-React static methods:
Refs …
=> heave ho! hoist non-react statics

src/components/AppIcon/AppIcon.css
I noticed that the AppIcon would shrink/crop when placed among other elements with a lot of content and therefore competing for space. The AppIcon should never shrink in size so I added flex-shrink: 0; and that fixed it!
=> Prevent <AppIcon> from shrinking

webpack/stripes-module-parser.js
Reverts folio-org/stripes-core#656
According to @Godlevskyi, the functionality planned for the plugin is instead being implemented via stripes-smart-components. This means we don't want this code that specifically looks for -- and cannot find -- the plugin directory in ui-notes.
=> Revert "Load @folio/notes as both app and plugin STCOR-357"

src/components/AppIcon/AppIcon.css
Moved flex-shrink: 0; to the icon itself instead of the wrapper element in AppIcon. 
This fixes a bug where long texts would stay on one line instead of expanding to multiple lines. This issue was apparent in the results list in various UI modules where text would cut off.
=> Minor AppIcon fix

CHANGELOG.md, src/Pluggable.js, src/components/HandlerManager/HandlerManager.js, src/components/Settings/Settings.js, src/moduleRoutes.js, test/webpack/stripes-module-parser.spec.js, webpack/stripes-module-parser.js
Allow modules to be ingested by stripes-core as more than one type -- the `type` property of the `stripes` section is now replaced by `actsAs` which can be a module type string or an array of them. Also removes redundant copies of the icons, Okapi interfaces, and permissions in the `modules.<type>` structure exposed by the `ModulesContext` as they are kept elsewhere.
=> Allow modules to be of more than one type. (STCOR-148)

webpack/stripes-module-parser.js
This PR should fix the issue found in STRIPES-634. It looks like `okapiInterfaces` was filtered out from stripes config for each module.
https://issues.folio.org/browse/STRIPES-634
=> Include okapiInterfaces in stripes config. Part of STRIPES-634

CHANGELOG.md, src/components/Front.js
You do this by setting `config.welcomeMessage` in your Stripes configuration, e.g. the `stripes.config.js` file. The value of this setting is the name of a translation tag, which is looked up and translated as usual.
In the absence of this setting, the old behaviour remains.
=> Allow home-page welcome message to be customised

CHANGELOG.md, package.json
We should only provide react in one place (stripes) and every other
library and app built with stripes should recieve it as a peer. This
reduces the chance of different modules using different minor version of
react with a `~` dependency and pulling multiple versions of it into the
bundle. Multiple versions of React === Bad Things.
Refs [UIIN-678](https://issues.folio.org/browse/UIIN-678)
=> UIIN-678 receive react via peerDependencies

CHANGELOG.md, package.json
Here's the thing: if React isn't a direct dependency, then it needs to
be provided as a devDependency so we can actually run tests. Duh.
Refs [UIIN-678](https://issues.folio.org/browse/UIIN-678)
=> UIIN-678 provide React as devDependency

.eslintignore, CHANGELOG.md, src/components/MainNav/AppList/AppList.css, src/components/MainNav/AppList/AppList.js, src/components/MainNav/CurrentApp/CurrentApp.css, src/components/MainNav/CurrentApp/CurrentApp.js, src/components/MainNav/MainNav.css, src/components/MainNav/NavButton/NavButton.css, src/components/MainNav/NavButton/NavButton.js, src/components/MainNav/NavDivider/NavDivider.css, src/components/MainNav/ProfileDropdown/ProfileDropdown.css, src/components/MainNav/ProfileDropdown/ProfileDropdown.js, src/components/SystemSkeleton/SystemSkeleton.css, translations/stripes-core/en.json
https://issues.folio.org/browse/STRIPES-641
Additional information here:
https://issues.folio.org/browse/UX-328
- Updated `<MainNav>` styling
- Updated `<NavButton>` styling
- New active style
- Larger font size
- Updated `<CurrentApp>` styling
- Larger and bold font
- Added aria-label for `<ProfileDropdown>`
- Added `dist`-folder to .eslintignore (if present, the contents of the folder can make the linting process stall)
=> STRIPES-641: MainNav updates

src/components/MainNav/CurrentApp/CurrentApp.js, src/components/MainNav/CurrentApp/CurrentAppGroup.js, src/components/MainNav/MainNav.js
Fixes STCOR-385.
If the `stripes.congig.js` file's `config` section contains `platformName` or `platformDescription`, then the corresponding values will be used for the name and description of the top-level caption.
If these values are not provided, the code defaults to the old behaviour of using a hardwired "FOLIO" caption and "FOLIO Platform" description (i.e. this change is backwards-compatible).
--
Note that I had to set "Fix version" for https://issues.folio.org/browse/STCOR-385 to 3.8.0, since there is no 3.9.0 currently configured in Jira and it seems I have lost the ability to create new versions. Arguably this should have been created when the version-number in the package-file was bumped in d5614bcb. When it is created, could whoever does this please update STCOR-385 …
=> Allow top-left "FOLIO" caption to be configured

src/components/TitleManager/TitleManager.js
Fixes STCOR-386.
If the `stripes.config.js` file's `config` section contains `platformName`, then its will be used for the name in the HTML `<title>`.
If this value us not provided, the code defaults to the old behaviour of using a hardwired "FOLIO" title (i.e. this change is backwards-compatible).
=> Page title use configured platformName instead of hardwired "FOLIO"

src/RootWithIntl.js, src/components/LastVisited/withLastVisited.js
whenever switching modules so that application doesn't continuously fill the store (which can lead to eventual degraded performance).
This is to address https://issues.folio.org/browse/UIIN-687 where performance slowly degrades over long periods of time.
NOTE: this PR relies on https://github.com/folio-org/stripes-connect/pull/102 being merged first.
The approach here is to reset stored records when moving between modules since they do take up space in memory and can grow unbounded as you visit more modules and run additional searches. By calling PRUNE whenever switching modules, we ensure that at most only 1 set of records is stored in Redux at any given time, thus making memory usage more reasonable and more predictable.
We will still be retaining search queries and other light pieces …
=> Calling PRUNE Redux reducer

src/loginServices.js
Store SSO token as Okapi token and reuse token if needed. 
Fixes [STCOR-391](https://issues.folio.org/browse/STCOR-391)
=> STCOR-391 Keep and use existing token

CHANGELOG.md, package.json
Exactly the same as `v3.10.1`, _exactly_, but we published a bug-fix
release in the `v3.7` line after we published `v3.10.1` and that seems
to have gotten npm's `latest` dist-tag. This is causing repositories
that have `^` dependencies to pull that non-latest "latest" release in
addition to the actual latest release that is included in the
`@folio/stripes` package with a `~` dependency.
So really this is just a retag of the existing `v3.10.1` release so that
tools like npm, yarn, and Jenkins will see the semantically-latest
release as the actual latest release. It sorta makes you wonder what the
point of semantic versioning is if `yarn` is going to ignore that in
favor of the `latest` dist-tag, doesn't it?
=> Release v3.10.2

src/components/AppIcon/AppIcon.css, src/components/AppIcon/AppIcon.js, src/components/AppIcon/readme.md
Added `iconAlignment`-prop for `<AppIcon>` which makes it possible to control the alignment of the icon relative to the label.
This change was originally requested in [UIIN-719](https://issues.folio.org/browse/UIIN-719) but I decided to update the `<AppIcon>` so that other modules can benefit from this update as well.
This is how iconAlignment="center" aligns the icon (default).
This is how iconAlignment="baseline" aligns the icon.
=> Added 'iconAlignment'-prop for <AppIcon>

src/RootWithIntl.js
This is necessary to avoid a console error on the login page, where `user.id` (which is marked as required in stripesShape) is not defined.
The explicit propTypes list contains those three stripes-object properties that are necessary for stripes-core to continue linting cleanly.
=> Replace use of stripesShape with explicit propTypes list

CHANGELOG.md, package.json, test/bigtest/helpers/setup-application.js
https://issues.folio.org/browse/STRIPES-659
Please refer to https://github.com/folio-org/stripes-connect/pull/107 for more details about it. 
This PR will keep failing until 107 is merged in stripes-connect.
=> Clear registered epics during BigTest app teardown. Part of STRIPES-659

package.json, webpack.config.cli.dev.js
As we approach solutions on treatment of global styles within the system, this will be a great upgrade with its treatment of the API (much nicer than pre-1.0.0)
Our current webpack.config.cli.dev.js sets a `sourcemaps: true` option for the `style-loader` entry. This has been removed. We've narrowly used the API for this thus far, github search says the `!loader` statements present among the modules leave it at standard usage (no options)
=> Upgrade style-loader to 1.0.0

src/components/MainNav/AppList/AppList.js, src/components/MainNav/AppList/components/ResizeContainer/ResizeContainer.js, test/bigtest/tests/ResizeContainer/ResizeContainer-test.js
Updated `<ResizeContainer>` to receive an array of items and return an object of refs mapped by ID which is then applied on the items to determine the widths of the items.
This fixes an issue where the "last visited" app states weren't being preserved because the items were cached by `<ResizeContainer>`. Instead, the original array will be used to map out the items so that any changes to that array will be rendered out.
Updated the tests to work with the new changes.
=> STCOR-398: Fixed "last visited" state for apps in nav bar

package.json
I previously assumed this was not necessary, as the dependency on the WebPack loaded `handlebars-loader` would transitively pull in `handlebars` itself.
It turns out that the loader has the templating engine only as a peer-dependency, not a full dependency, which means that building stripes-core in the absence of a module that has its own full dependency on `handlebars` will fail due to the unfulfilled peer-dependency.
This will fix a persistent and mysterious build problem first encountered in ReShare, but which is sure to crop up again in other contexts if not addressed.
=> Add explicit dependency on handlebars

CHANGELOG.md, package.json
Handle the issue with tests upon the loading of translations by downgrading the [fake-xml-http-request](https://github.com/pretenderjs/FakeXMLHttpRequest) which updated [recently](https://github.com/pretenderjs/FakeXMLHttpRequest/releases/tag/v2.1.1) in the scope of [FOLIO-2369](https://issues.folio.org/browse/FOLIO-2369).
=> FOLIO-2369: Handle the issue with tests upon the loading of translations

src/components/MainNav/ProfileDropdown/ProfileDropdown.js
When the `showHomeLink` configuration item is set, as is often the
case in development setups, the top right menu with the "Logout" link
also has a "Home" link that goes back to the FOLIO home page. This
link works, but a while back developed the wrinkle that clicking it
did not dismiss the dropdown menu that the link is on. The present
one-line commit fixes that by having the navigate-to-home function
also toggle the menu.
=> onHome function calls toggleDropdown

CHANGELOG.md, package.json
Versions of `serialize-javascript` prior to `v2.1.1` suffer from an XSS
vulnerability related to their encoding of regular expressions.
[Details](https://github.com/yahoo/serialize-javascript/security/advisories/GHSA-h9rv-jmmf-4pgx).
Fixes [STCOR-401](https://issues.folio.org/browse/STCOR-401?jql=text%20~%20%22serialize%22)
Despite the major version bump, I believe this is a low-risk upgrade. The bump from v1 to v2 was really only because v1.something inadvertently changed a behavior, and they realized that, and saw fit to bump the major when they changed it back.
=> STCOR-401 bump serialize-javascript

CHANGELOG.md, package.json, test/bigtest/helpers/setup-application.js, test/bigtest/helpers/setup-core-application.js, test/bigtest/network/config.js, test/bigtest/network/index.js, test/bigtest/network/start.js, test/bigtest/tests/about-test.js, test/bigtest/tests/createResetPassword-test.js, test/bigtest/tests/forgotPassword-test.js, test/bigtest/tests/forgotUsername-test.js, test/bigtest/tests/login-test.js, test/bigtest/tests/nav-test.js, test/bigtest/tests/statusPage-test.js
This PR adds a new `miragejs` dependency and introduces a new `mirageOptions` option called `serverType` which allows for configuring which mirage server implementation will be used. The default implementation will be set to BigTest mirage for backwards compatibility (the current testing setup for existing ui modules will work as is - it's not a breaking change).
This PR also migrates `stripes-core` tests to `miragejs`.
In order to opt-in for the new miragejs implementation the `serverType` can be set to `miragejs` via `setupApplication` for example:  
https://github.com/folio-org/ui-users/pull/1127/files#diff-afc65168f7c0334e511aba82e26e9977R4
1.  `import { ... } from '@bigtest/mirage'` becomes `import { ...} from 'miragejs'`
2. The `faker` has to be installed as a separate dependency …
=> STCOR-407: Add miragejs dep and ability to choose mirage server implementation

test/bigtest/network/start.js
It looks like for some reason when the UI module removes dependency on the old mirage from bigtest we are seeing these errors:
` "message": "Uncaught Error: Cannot find module '@bigtest/mirage'\nat test/bigtest/index.js:58918:163\n\nError: Cannot find module '@bigtest/mirage'\n    at webpackMissingModule (test/bigtest/index.js:58918:83)\n    at Module.<anonymous> `
I'm not entirely sure why we would see these errors since `@bigtest/mirage` is still listed as a dependency in `stripes-core`.
This PR changes the way the two mirage server implementations are loaded and it loads them conditionally depending on the `serverType`.
=> Include mirage server conditionally. Part of STCOR-407

package.json
So it's kind of complicated but since we want to provide backwards compatibility with the previous version of mirage we need to make sure both of them are included in each build.
We are currently seeing these errors from UI modules which are using the old version of mirage (from bigtest):
```
ERROR in ./node_modules/@folio/stripes-core/test/bigtest/network/start.js
Module not found: Error: Can't resolve 'miragejs' in '/home/jenkins/workspace/olio-org_ui-local-kb-admin_PR-69/project/node_modules/@folio/stripes-core/test/bigtest/network'
```
By moving both `@bigtest/mirage` and `miragejs` from `devDependencies`  to `dependencies` we hope we can resolve it (Thank you @zburke for your help with this!).
=> STCOR-407: Move mirage deps to dependencies from devDependencies. 

src/configureEpics.js, src/mainActions.js
It turned out that some of the side effects would still be executing causing to trigger actual fetches even after the app has been unmounted. This PR should prevent that.
=> FOLIO-2097: Stop side effects from executing on unmount

CHANGELOG.md, src/components/NestedRouter.js
Adjust Route propTypes to accept lazy-loaded components in the scope of [STCOR-408](https://issues.folio.org/browse/STCOR-408).
=> STCOR-408: Adjust Route propTypes to accept lazy loaded components

webpack/babel-loader-rule.js
Resolution of the plugin via the standard definition (eg, as used by the various other `@babel/...` plugins in this file) sometimes fails during BigTest runs in an isolated UI module.
This seems to be due to a combination how deeply nested the RHL dependency is in node_modules and that the plugin is not the library itself, but nested within the library.
To sidestep this, we resolve the library path ahead of time before it hits Babel.
=> Resolve RHL babel plugin ahead of time

package.json, test/webpack/stripes-branding-plugin.spec.js, webpack/stripes-branding-plugin.js
We replaced `favicons-webpack-plugin` with `webapp-webpack-plugin`
because the former had a memory leak, but the latter is now deprecated
and has been folded back into the former.
Refs [STCOR-415](https://issues.folio.org/browse/STCOR-415), [STCOR-232](https://issues.folio.org/browse/STCOR-232), [STCOR-296](https://issues.folio.org/browse/STCOR-296)
=> STCOR-415 replace deprecated webapp-webpack-plugin

package.json
since these dependencies are now provided by the platform and tests run outside that context.
=> Added react-router and react-router-dom as devDeps

util/package2md.js
This is the Stripes part of OKAPI-509, and allows a UI module to declare optional dependencies on Okapi interfaces.
=> Okapi 509  optional dependencies

CHANGELOG.md, package.json, webpack.config.base.js
In local development, the console would report the following error:
```
07:28:59.865 react-hot-loader.development.js:2375 React-Hot-Loader: react-🔥-dom patch is not detected. React 16.6+ features may not work.
AppContainer @ react-hot-loader.development.js:2375
AppContainer @ VM2755:14
constructClassInstance @ react-dom.development.js:14204
updateClassComponent @ react-dom.development.js:18413
beginWork$1 @ react-dom.development.js:20186
beginWork$$1 @ react-dom.development.js:25756
...
```
That leads to https://github.com/gaearon/react-hot-loader/issues/1227
where it is noted over a series of comments that the configuration
instrucations are rather confusing:
> The readme is confusing about this. It says a Webpack plugin is required, then recommends using the Babel plugin instead. The …
=> correctly configure react-hot-loader

src/components/AppIcon/AppIcon.css
We are currently in the process of checking up on all things accessibility related in FOLIO apps and we noticed that the WCAG Color Checker (a great tool for detecting color contrast ratio issues) was reporting that app icons had poor color contrast ratio.
This is a false negative because the icon itself doesn't contain text – only an icon as an image. And since there are a lot of AppIcon's in a FOLIO app it can lead to unnecessary noise when checking for color contrast issues.
A simple fix for this is to add a color of #FFF to the .icon element to make WCAG ignore this false negative. Nothing changes visually with this fix.
=> Minor fix for <AppIcon> to prevent WCAG Color Checker from reporting a false negative

src/components/Root/Root.js
I guess this is the danger we run into when adding prop-types to satisfy ESLint: we do need to also check that the added prop-types are actually correct, otherwise we get big, ugly red messages on the JavaScript console:
> Warning: Failed prop type: Invalid prop `history.location` of type `object` supplied to `Root`, expected `string`.
=> history location is PropTypes.object, not PropTypes.string

src/components/MainNav/AppList/AppList.css, src/components/MainNav/AppList/components/AppListDropdown/AppListDropdown.js, src/components/Settings/Settings.css, src/components/Settings/Settings.js
This is a follow-up PR for the changes I made in:
https://github.com/folio-org/stripes-components/pull/1209
- Updated `<NavList>`-implementation for settings
- Removed extra margin from `<NavList>`'s
- Added aria-label for `<NavList>`'s
- Updated app list dropdown to use `<NavListSection>` and striped styles
=> Adjustments for settings <NavList>'s and apps dropdown

src/components/Root/Root.js
As part of https://github.com/folio-org/ui-users/pull/1240, we've introduced an unavoidable amount of console errors by default. This PR suppresses those errors.
This PR is intended to be reverted by May 15 as per [STCOR-424](https://issues.folio.org/browse/STCOR-424).
=> Suppress react-intl errors for unset permissions

src/components/Settings/Settings.js, src/moduleRoutes.js
This PR logs the errors that are caught when parsing a module during `getModule()`. In tandem with https://github.com/folio-org/stripes-connect/pull/141, these errors become more easily fixable.
**Before:** Useless error message that doesn't say what the issue was.
**After:** A better chance at debugging the issue based on the error message.
Throwing **and** logging seems excessive, but:
- We can't just `throw` because React swallows some of the exceptions for reasons I don't fully understand.
- We _shouldn't_ just log when there's a major problem like the module fails to parse.
=> throw and log errors that prevent module load

CHANGELOG.md, package.json
`react-intl` needs to be provided as a dev-dep since it is only listed
as a peer-dep. It isn't clear to me why this is suddenly the case when
previously releases were not, but here we are.
Refs [STRIPES-672](https://issues.folio.org/browse/STRIPES-672)
=> STRIPES-672 provide react-intl as devdep

translations/stripes-core/en.json
Add localization for password validation message
https://issues.folio.org/browse/STSMACOM-338
=> STSMACOM-338: Add localization for password validation message

CHANGELOG.md, src/RootWithIntl.js, src/components/OverlayContainer/OverlayContainer.css
https://issues.folio.org/browse/STCOR-419
Moved `<OverlayContainer>` into the main content area to fix the aXe error: `Some page content is not contained by landmarks'`
Since the `<OverlayContainer>` was rendered outside a landmark element, aXe would report an error when e.g. a dropdown was opened inside the `<OverlayContainer>`. Moving it into the the `<main>` fixes this issue since it's now inside a landmark element.
Updated position to `fixed` to ensure that the `<OverlayContainer>` covers the entire viewport.
=> STCOR-419: Fix aXe error related to <OverlayContainer>

src/components/OverlayContainer/OverlayContainer.css
Updated CSS for OverlayContainer after noticing an issue on some touch devices where the container only stretched a part of the screen.
=> Minor OverlayContainer fix

CHANGELOG.md, src/components/Root/Root.js
`react-intl` is pretty verbose about missing translation values, even
when using its own built-in system for providing default values, which
seems odd. We suppressed those warnings for permissions-related values
for a while to give folks time to update their apps and start providing
entries in their translation files, rather than just displaying the
English-only values pulled from `package.json` files as part of the
permission description. No longer.
I was supposed to do this in time for the 5.0 release on/before May 15. Alas. 
There will likely be a `v5.0.x` patch release and we should include it there. 
Refs [STCOR-424](https://issues.folio.org/browse/STCOR-424)
=> STCOR-424 stop filtering react-intl permissions warnings

CHANGELOG.md, package.json
See https://issues.folio.org/browse/STRIPES-685
For additional context, see https://issues.folio.org/browse/MODUSERBL-97, https://issues.folio.org/browse/MODLOGIN-128 and other related issues
I think we can dual-support 5.0 and 6.0 here since `?includes=credentials` isn't used here - unless I'm missing something.
=> STRIPES-685 - move to users-bl 6.0

CHANGELOG.md, src/components/Login/LoginCtrl.js, src/components/MainNav/AppList/AppList.js, src/components/MainNav/MainNav.js, src/components/MainNav/ProfileDropdown/ProfileDropdown.js
* Abandon use of React's legacy context API in favor of the currently
supported API.
* Remove unused references to the router context.
Refs [STCOR-390](https://issues.folio.org/browse/STCOR-390)
=> STCOR-390 abandon legacy context

CHANGELOG.md, src/locationService.js
Currently the [logic](https://github.com/folio-org/stripes-core/blob/master/src/locationService.js#L32) to figure out which module a [queryResource](https://github.com/folio-org/ui-erm-comparisons/blob/master/package.json#L29) belongs to, just matches on the start of the module `route` string (expressed via the stripes object in the package.json). for eg: `/erm` and `/erm-comparisons` which are top level routes to the `ui-agreements` and `ui-erm-comparisons` apps respectively would both resolve to the [agreements](https://github.com/folio-org/ui-agreements/blob/master/package.json#L107) module (If _both_ the apps were to be present in the tenants `stripes.config.js`). 
To prevent such a scenario, this PR extends the logic to match the entire `module.route` string so that the …
=> Tweak regex to match the entire module route string, refs ERM-950

CHANGELOG.md, src/locationService.js
Reverts folio-org/stripes-core#884
Reverting this PR as the fix doesnt handle the scenario when the `foo` apps `module.route` is `/foo` whereas the `home` route is `foo/bar`.
In that scenario the `location.pathname` would be `foo/bar` which we are matching with an end-of-string marker, so `/foo` in this case which fails to match and hence the query resource is not annointed to the `foo` app as expected.
I would rather wait to discuss a solution for this on the stripes-arch call before adding in some additional conditional regexes.
=> Revert "Tweak regex to match the entire module route string, refs ERM-950"

CHANGELOG.md, src/components/MainNav/MainNav.js
This PR fixes an issue with occasional double `history.push`.
While working on https://issues.folio.org/browse/UIU-1779 I noticed that sometimes the `history.push` executes twice.
Once after we apply search:
https://github.com/folio-org/ui-users/blob/0a4b7257bcbc36450955c9a88c51713c047fefba/src/routes/UserSearchContainer.js#L172
and the second time in:
https://github.com/folio-org/stripes-core/blob/master/src/locationService.js#L75
This currently happens because when the first `history.push` is executed the location is being changed which triggers resource refresh in stripes-connect:
https://github.com/folio-org/stripes-connect/blob/master/connect.js#L149
The refresh fails in:
https://github.com/folio-org/stripes-connect/blob/master/RESTResource/RESTResource.js#L654-L660 (potentially …
=> STCOR-440: Update location only if resourceQuery actually changes

test/bigtest/helpers/Harness.js, test/bigtest/tests/sso-login-test.js
Include stripes-core translations in `<Harness>` so it doesn't throw the
big nasty react-intl errors when a translation key is missing. This
helps clean up the test output.
=> better harness doesn't throw react-intl errors

CHANGELOG.md, src/loginServices.js
We added this polyfill in #876 because react-intl v4 stopped including
certain things that are now supported directly by the browser, but the
locale data for the `Intl.DisplayNames` polyfill is just huge,
ballooning our bundle from <10 MB to >40MB. It's very noticably slower
during the initial page load, so much so that tests with a 30-second
default timeout were failing just because the bundle was still
downloading.
Refs [STCOR-442](https://issues.folio.org/browse/STCOR-442), [STCOR-435](https://issues.folio.org/browse/STCOR-435), [STRIPES-672](https://issues.folio.org/browse/STRIPES-672)
=> STCOR-442 don't provide Intl.DisplayNames polyfill

CHANGELOG.md, index.js, src/loginServices.js
The list of available locales should be exported and available from one
and only one location.
Refs [STCOR-443](https://issues.folio.org/browse/STCOR-443)
=> STCOR-443 single source of truth for locales

CHANGELOG.md, src/App.js, src/loginServices.js, src/moduleRoutes.js
- Satisfies [STRIPES-671](https://issues.folio.org/browse/STRIPES-671)
- Confirmed only OKAPI call that happens before login now is /saml/check to determine SSO status, which has graceful handling for > 400 HTTP response.
- Determining locale occurs after login, so moving to config-based is out of scope for this story.
=> Moving tenant module info retrieval to post-login

CHANGELOG.md, test/bigtest/helpers/setup-application.js
There's been an update to `loginServices` on when tenant module info is received - now it's received only after login (https://github.com/folio-org/stripes-core/pull/893). After this change a lot of eHoldings tests have started failing because eHoldings doesn't mock login or okapi session before tests.
This PR is for mocking okapi session before tests.
[STCOR-444](https://issues.folio.org/browse/STCOR-444)
=> STCOR-444: eHoldings tests fail after moving discovery services to happen after login

src/loginServices.js
Include the JS polyfill for all three `@formatjs` packages
(`pluralrules`, `relativetimeformat`, `displaynames`) so browsers
without it won't barf, but only include the `en` locale data in order to
avoid bundle bloat.
Refs [STCOR-442](https://issues.folio.org/browse/STCOR-442)
=> always include @formatjs polyfills with en data

CHANGELOG.md, src/components/MainNav/NavButton/NavButton.js, src/components/Settings/Settings.js, src/components/TitledRoute/TitledRoute.js, src/moduleRoutes.js
Handle react-router-dom deprecation warnings
```
Chrome 84.0.4147 (Mac OS X 10.15.6) ERROR: 'Warning: Please use `require("react-router-dom").Route` instead of `require("react-router-dom/Route")`. Support for the latter will be removed in the next major release.'
Chrome 84.0.4147 (Mac OS X 10.15.6) ERROR: 'Warning: Please use `require("react-router-dom").Link` instead of `require("react-router-dom/Link")`. Support for the latter will be removed in the next major release.'
Chrome 84.0.4147 (Mac OS X 10.15.6) ERROR: 'Warning: Please use `require("react-router-dom").Switch` instead of `require("react-router-dom/Switch")`. Support for the latter will be removed in the next major release.'
```
=> STCOR-448: Handle `react-router-dom` deprecation warnings

CHANGELOG.md, package.json, src/components/About/About.js
Update `react-intl` from `v4` to `v5`.
Refs [STCORE-449](https://issues.folio.org/browse/STCOR-449)
=> STCOR-449 update react-intl to v5

src/discoverServices.js
- Adding Okapi Token to `/version` and `/modules` service calls.
- Since 'supertenant' is generally not associated with the token, now passing the tenant that is associated with it (call would fail otherwise).
=> Passing token in with Okapi version and modules service calls.

test/bigtest/helpers/setup-application.js
Due to the change in: https://github.com/folio-org/stripes-core/pull/893/files
The discovery part of the store is only populated after a successful login. This caused some tests to fail because the `discovery` was missing.
This PR allows for passing a customized `initialState` via `setupApplication` so we can populate the `discovery`. 
For example in `ui-users` the `setupApplication` can pass `initialState` similar to:
````js
export default function setupApplication({
scenarios,
permissions = {},
hasAllPerms = true,
modules,
translations,
currentUser,
} = {}) {
const initialState = {
discovery: {
modules: {
'mod-circulation-16.0.0-SNAPSHOT.253': 'Circulation Module',
'mod-users-16.0.1-SNAPSHOT.121': 'users',
'mod-feesfines-15.8.0-SNAPSHOT.73': 'feesfines',
},
},
};
setupStripesCore({ …
```
=> Allow for passing custom initial state to BigTest setupApplication

src/components/About/About.js
Sort the list of interfaces a module depends on, because it's much
easier to find something in a sorted list than an unsorted one.
=> sort interfaces modules depend on

package.json, webpack.config.cli.dev.js, webpack.config.cli.prod.js
https://issues.folio.org/browse/STCOR-447
- Upgraded `postcss-custom-properties` to the latest version
- Added `importFrom`-setting to `postcss-custom-properties` to both development and production webpack configs to enable auto imports of CSS variables in UI modules
With this change, you will be able to use all of the available CSS variables from `@folio/stripes-components/lib/variables.css` without manually importing them into your CSS file.
=> STCOR-447: Automatically import CSS variables from stripes-components into UI modules

CHANGELOG.md, doc/okapiKy.md, index.js, package.json, src/useOkapiKy.js, src/withOkapiKy.js
Documented in doc/okapiKy.md, these provide an especially convenient
API for when you want to send HTTP requests to Okapi rather then let
stripes-connect manage a resouce. The previous alternative was an
explicit use of window.fetch where you'll need to feed it headers from
useStripes() and handle errors in at least two places (response with an
HTTP error code and an exception). Ky is a light wrapper that cleanly
lets us inherit the headers and streamlines error handling.
=> Add okapiKy helpers

CHANGELOG.md, src/loginServices.js
The `validateUser()` function actually does three things:
* check if the given token is syntactically valid
* check whether Okapi is up
* check if the token can be used to make a request
It does this in one fell swoop by making a request, but in order for
this to function for _all_ users the endpoint it hits must be one that
does not require any permissions. `/users` is not such an endpoint, but
`/bl-users/_self` is.
Replaces #923, where I attempted to resolve the permissions problem by
checking for token validity but, ahem, also ignoring the other two tasks
this function accomplishes.
Refs [STCOM-452](https://issues.folio.org/browse/STCOR-452)
=> STCOR-452 validate token without permissions

CHANGELOG.md, package.json
Versions of `serialize-javascript` before 3.1.0 suffer from security
vulnerability CVE-2020-7660.
Refs [STCOR-467](https://issues.folio.org/browse/STCOR-467)
=> STCOR-467 update serialize-javascript

test/bigtest/network/config.js
eHoldings experiences test failures due to an update in stripes-core. These failures are caused by a PR that changed endpoint that validates a token (https://github.com/folio-org/stripes-core/pull/931).
This PR adds a new mock endpoint `bl-users/_self` so that the token validator receives a correct response
=> UIEH-976: Defined a mock for '/bl-users/_self' request

CHANGELOG.md, src/components/MainNav/ProfileDropdown/ProfileDropdown.js, src/components/TitledRoute/TitledRoute.js
* `<ProfileDropdown>` passed a `<FormattedMessage>` to `<NavButton>` which
expected a string, generating a console warning:
```
Warning: Failed prop type: Invalid prop `ariaLabel` of type `array` supplied to `ForwardRef`, expected `string`
```
* `<TitledRoute>` used `<FormattedMessage>` with renderprops to derive
the value to pass to `<TitleManager>`, but as of `react-intl` `v5`
that results in an array instead of a string, which sucks, and which
generates this console warning:
```
Warning: Failed prop type: Invalid prop `page` of type `array` supplied to `TitleManager`, expected `string`.
```
Refs [STCOR-472](https://issues.folio.org/browse/STCOR-472)
=> STCOR-472 pass correct props to NavButton

src/components/MainNav/AppList/tests/AppList-test.js
In a recent change to stripes-components' `<Dropdown>`, the focus moves into the menu only when the dropdown's trigger is in focus when the menu opens... this action isn't quite fast enough for the assertions and `click` alone doesn't appear to be setting a focus to the dropdown trigger.
=> fix tests - focus button before assertions

CHANGELOG.md, src/RootWithIntl.js, src/components/Root/Root.js
https://issues.folio.org/browse/STCOR-481
It looks like every time we change the locale the `IntlProvider` is changed causing the `RootWithIntl` to be completely recreated (a new RootWithIntl instance is being created). This also recreates the callout ref and `CalloutContext.Provider`  causing issues similar to the one described in STCOR-481
This PR moves the context and callout to `Root`. This seems to help at least with the issue described in STCOR-481.
=> STCOR-481: Move CalloutContext to Root to avoid issues with React Intl

CHANGELOG.md, test/bigtest/network/config.js, test/bigtest/network/scenarios/changePasswordSuccess.js, test/bigtest/network/scenarios/forgotPasswordSuccess.js, test/bigtest/network/scenarios/forgotUsernameSuccess.js
The [mirage documentation
notwithstanding](https://miragejs.com/docs/main-concepts/route-handlers/#status-codes-and-headers),
to actually return a custom response code you must return a
custom `Response` object with the desired code _and_ include that same
code as the third parameter to the action (`put`, `post`, etc) method.
Only doing the first (as in the documentation) or the later (as in
previous code) doesn't work correctly.
With only the former, mirage is happy but the code under test receives a
201 instead of the custom code, causing tests of code that expect
specific response codes to fail.
With only the latter, mirage spews the warning but the code under test
receives the expected response.
Refs [STCOR-483](https://issues.folio.org/browse/STCOR-483)
=> STCOR-483 use correct HTTP responses codes

CHANGELOG.md, src/components/MainNav/AppList/AppList.js, src/components/MainNav/components/SkipLink/SkipLink.js, src/components/Settings/Settings.js
Using render-props with a `<FormattedMessage>` in `react-intl` `v5`
renders as an array rather than as a string as it did in `v4`. This
causes problems for attributes such as `aria-label`, which expect
strings.
Refs [STCOR-482](https://issues.folio.org/browse/STCOR-482), [STRIPES-694](https://issues.folio.org/browse/STRIPES-694)
=> STCOR-483 avoid render-props with FormattedMessage

src/components/Root/Root.js
After some refactoring related to STCOR-481 we started to see some issues reported by @ViktorSoroka07 and @aliaksei-chumakou related to missing `intl` when using `FormattedMessage` with the `callout`.
https://github.com/folio-org/stripes-core/pull/946#issuecomment-731106017
@zburke found a good solution for it under:
https://github.com/folio-org/stripes-smart-components/pull/962
This PR is moving the `CalloutContext.Provider` back under `IntlProvider` to address similar issues in other places.
The callout ref is kept in the `Root` so the issue reported in STCOR-481 should still work.
=> STCOR-481: Move CalloutContext Provider back under IntlProvider

CHANGELOG.md, src/components/Root/Root.js
Provide default HTML-element formatters for `b`, `i`, `em`, `strong`,
`span`, `div`, `p`, `ul`, `ol`, and `li` so they can be freely used in
translation values without requiring special handling in the
`<FormattedMessage>` component or `formatMessage()` function call. This
effectively replaces `<SafeHTMLMessage>` from `react-intl-safe-html`,
which can now be deprecated.
Refs [STCOR-477](https://issues.folio.org/browse/STCOR-477)
=> STCOR-477 provide formatters to IntlProvider

webpack/build.js
@ryandberger the previous context didn't work for me correctly. I think the idea for the context is to match the paths in the dll's manifest with the paths in the folder where we run build consuming the dll.
Now when I build with `--useDll` I finally see:
````js
[0] delegated ./node_modules/react/index.js from dll-reference reactDll 42 bytes {0} [built]
[1] delegated ./node_modules/prop-types/index.js from dll-reference reactDll 42 bytes {0} [built]
````
=> STCOR-471: Adjust context in DllReferencePlugin

src/components/MainNav/CurrentApp/AppContextDropdown.js
Followed migration direction here to remove the old dropdown API:
https://github.com/folio-org/stripes-components/tree/master/lib/Dropdown#migration-from-past-versions
Refs [STCOR-491](https://issues.folio.org/browse/STCOR-491)
=> STCOR-491 Migrate AppContextDropdown away from legacy API

Jenkinsfile
Disable SonarQube per [FOLIO-2920](https://issues.folio.org/browse/FOLIO-2920), because SQ is blowing up in some weird
way that we don't understand and is preventing all PRs from merging,
which sure ain't fair to them.
Refs [STCOR-495](https://issues.folio.org/browse/STCOR-495)
=> STCOR-495 disable SonarQube

CHANGELOG.md, src/components/MainNav/AppList/AppList.js, src/components/MainNav/AppList/components/AppListDropdown/AppListDropdown.js, src/components/MainNav/CurrentApp/CurrentApp.js, src/components/Settings/Settings.js
- Fulfills [STCOR-490](https://issues.folio.org/browse/STCOR-490).
- Passing in full module name to resolve icon so that `@folio/` scope prefix is not assumed.
- Tested with a non-folio-scoped module and confirmed that icon appears properly in menu bar, app drop-down list, current app in top left, and settings. Also verified folio-scoped app icons continue to work as expected. 
- NOTE: Icons within non-folio-scoped module page must make this same change in their codebase for the icon to display, but this handles the cases managed by `stripes-core`.
=> Stcor 490 full module name

package.json
- Also updating node version runtime to v10 since that is a requirement of `postcss-custom-properties` v10: https://github.com/postcss/postcss-custom-properties/releases/tag/10.0.0
=> Updating postcss-custom-properties to v10 fixing DoS security warning

CHANGELOG.md, package.json, webpack/build.js
When building with `--useDll` option the output folder needs to also include the dll file and append it to `index.html`. This PR is trying to address that.
https://issues.folio.org/browse/STCOR-492
=> STCOR-492: Append dlls to final output during build

CHANGELOG.md, Jenkinsfile, package.json, src/App.js, src/discoverServices.js, src/loginServices.js
Backport changes from STCOR-454 (PR #893, #901) to `v5` in order to
allow operators in a multi-tenant environment to update their okapi to
v4. This means conducting module-discovery _after_ login and
authenticated as the current tenant instead of `supertenant`.
In short, this change allows `@folio/stripes` `v4`
(`@folio/stripes-core` `v5`) to be compatible with `okapi` `v4`;
previously, it was compatible only with `v3`.
Refs [STCOR-496](https://issues.folio.org/browse/STCOR-496), [STCOR-454](https://issues.folio.org/browse/STCOR-454)
=> STCOR-496 conduct discovery after login

CHANGELOG.md, src/useOkapiKy.js
Avoid retrying of HTTP requests using `useOkapiKy` hook by default in the scope of the [STCOR-500](https://issues.folio.org/browse/STCOR-500).
=> STCOR-500: Avoid retrying of http requests using `useOkapiKy` hook by default

CHANGELOG.md, index.js, src/ModulesContext.js, src/components/ModuleTranslator/ModuleTranslator.js, src/components/Modules/withModule.js, src/components/Modules/withModules.js, src/moduleRoutes.js
Exposes the module context, enabling apps to consume build-time configuration.
=> STCOR-502 Expose module context

package.json
`stripes-connect` will become compatible with `react` `v17` in `v7`, not
`v6.1`.
Refs [STCOR-501](https://issues.folio.org/browse/STCOR-501)
=> STCOR-501 bump stripes-connect for react 17 compat

src/components/MainNav/ProfileDropdown/ProfileDropdown.js, src/components/MainNav/ProfileDropdown/tests/profile-dropdown-test.js
folio-testing shows an empty screen with the following in the console:
```
Uncaught TypeError: Cannot read property 'isLocalLogin' of undefined
at ProfileDropdown.value (bundle.310dcdca34d1f4011c62.js:483)
at bundle.310dcdca34d1f4011c62.js:483
at Array.map (<anonymous>)
...
```
I can't explain why `module.getModule()` is being called in a way that
returns empty, which results in failing to be able to access
`isLocalLogin`, but that's what's happening.
Truly, I'm stumped about the root cause here, and this is clearly a
bandaid solution, but at least it restores access, hopefully, to
folio-testing.
Refs [STCOR-504](https://issues.folio.org/browse/STCOR-504)
=> STCOR-504 do not access empty object

src/components/MainNav/ProfileDropdown/ProfileDropdown.js, src/components/MainNav/ProfileDropdown/tests/profile-dropdown-test.js
Reverts #992
With react 17 in place, the change-password menu somehow triggered an
NPE that, because it fell early in the render tree, completely blocked
access to the FOLIO UI. Now that the react 17 update itself has been
reverted, this temporary hack is, too.
Refs [STCOR-505](https://issues.folio.org/browse/STCOR-505), [STRIPES-722](https://issues.folio.org/browse/STRIPES-722)
=> STCOR-505 revert #992 to restore change-password menu item

CHANGELOG.md, package.json
Reverts folio-org/stripes-core#990
In fact this was exported here but we missed it. Sorry!
=> Revert "STCOR-503 Move react-titled to peer dependency"

package.json
Reverts folio-org/stripes-core#991
Crackerjack research by @aditya-matukumalli and @mkuklis suggests [onFocus changes in React 17](https://github.com/facebook/react/issues/19743), which have caused [event handling trouble for others](https://eng.wealthfront.com/2021/01/14/upgrading-to-react-17-how-to-fix-the-issues-and-breaking-changes/), may be causing [our woes](https://issues.folio.org/browse/STCOR-504) too. 
Because we reverted the react-17 update all the way down the stack, [the `stripes-connect` version bump was also reverted](https://github.com/folio-org/stripes-connect/pull/168) and thus the desired version remains `6.1`.
Refs [STRIPES-722](https://issues.folio.org/browse/STRIPES-722)
=> Revert "STCOR-501 bump stripes-connect for react 17 compat"

CHANGELOG.md, package.json, src/components/Root/Root.js, src/createReactQueryClient.js
Following the decision during the stripes-architecture meeting, the purpose of this PR is to setup [react-query](https://react-query.tanstack.com/) in the scope of the [STCOR-508](https://issues.folio.org/browse/STCOR-508).
`react-query` is a library for fetching, caching, and updating data in React applications without touching any "global state". This PR also provides [default options](https://react-query.tanstack.com/guides/important-defaults) so individual applications will not need to override them every time. The library provides handy hooks such as `useQuery`, `useQueries`, `useQueryClient`, etc to work with queries and `useMutation` to work with mutations. This library can be treated as an alternative to `stripes-connect` for developers who want to write the code using hooks for …
=> STCOR-508: Setup react-query

package.json
Added a missing `rtl-detect` dependency that was recently removed, but is still imported in `loginServices`.
This causes test failures in `ui-inventory` module https://jenkins-aws.indexdata.com/job/folio-org/job/ui-inventory/job/UIIN-1407/3/console
=> Added missing rtl-detect dependency

CHANGELOG.md, src/discoverServices.js, src/loginServices.js
https://issues.folio.org/browse/STCOR-506
The issue described in STCOR-506 was related to the fact that the `setOkapiReady` was dispatched inside `getBindings`:
https://github.com/folio-org/stripes-core/compare/STCOR-506?expand=1#diff-c9d695b1d57404dfed01196c8cf479c0e4cd48583f6c78e7db23402582846864L182
This would incorrectly mark okapi as ready causing `Root` to rerender before all other resources were loaded:
https://github.com/folio-org/stripes-core/blob/master/src/components/Root/Root.js#L83
This PR is changing the time when the  `setOkapiReady` is dispatched. It will happen only after all requests to resources are fetched and processed.
=> STCOR-506: Dispatch setOkapiReady only after all resources are loaded

CHANGELOG.md, src/RootWithIntl.js, src/components/Root/Root.js
Reverts folio-org/stripes-core#1018
Unfortunately, this causes "Action" menus to render incorrectly. One step forward, two steps back. Rats.
=> Revert "STCOR-518 Callouts are not opened after page reload"

CHANGELOG.md, src/components/Login/Login.js, src/components/SSOLogin/SSOLogin.js
The SSO/SAML form was nested inside the username-and-password form, but
forms may not be nested. This generated a console warning.
Refs [STCOR-522](https://issues.folio.org/browse/STCOR-522)
=> STCOR-522 do not nest forms

CHANGELOG.md, src/components/Root/Root.js, src/loginServices.js
When restoring a session that was preserved in local-storage, as when
opening a new window when all previous windows had been closed but the
user had never logged out, check SSO/SAML. Previously, these were
handled as a disjuction (if we have a session, rehydrate it; else check
for sso). Now they are simply both handled in series.
There is no reason they need to be alternatives. You could login via
SSO, then close your window, then open a new one, then logout. At this
point, you want to see the "Login with SSO" button again, but previously
you wouldn't have because the SSO/SAML check only happened when starting
new sessions, not when rehydrating existing sessions.
Refs [STCOR-514](https://issues.folio.org/browse/STCOR-514)
=> STCOR-514 dispatch checkSSO on session hydration

src/components/Settings/Settings.js
Without a unique HTML element ID, it is not possible for end-to-end
tests to assess when the settings pane has loaded.
Refs [STCOR-526](https://issues.folio.org/browse/STCOR-526), [FOLIO-2946](https://issues.folio.org/browse/FOLIO-2946)
=> STCOR-526 provide and HTML entity id for the settings Paneset

CHANGELOG.md, src/RootWithIntl.js, src/components/Root/Root.js
This PR moves `<CalloutContext>` back to `<RootWithIntl>`. This was our original setup back in:
https://github.com/folio-org/stripes-core/commit/a2ab520d33308fd415807ab1d3ac871f8e190114
https://issues.folio.org/browse/STCOR-534
The previous setup was causing issues with the `Callout` ref being lost between re-logins since  it's only created once when the app loads initially:
https://github.com/folio-org/stripes-core/blob/master/src/components/Root/Root.js#L188
This change makes sure that:
1. Callout works when locale is changed (STCOR-481)
2. Menus and dialogs display correctly
3. Callout works during re-login and page refresh
=> STCOR-534: Move CalloutContext back to RootWithIntl

src/validators/validatePhoneNumber/validatePhoneNumber.js
Regular expression denial of service (ReDoS) in [validatePhoneNumber.js](https://github.com/folio-org/stripes-core/blob/v7.1.0/src/validators/validatePhoneNumber/validatePhoneNumber.js):
`^(\d+[.-]*)+\d+$`
* Open "Forget username" form, for example https://folio-snapshot.dev.folio.org/forgot-username
* Paste `1234567890123456788901234567890@mail`
* Press enter or click "Continue"
Error message saying "Please enter a valid email address."
Nothing. Console shows "Uncaught (in promise) InternalError: too much recursion" after 6 seconds.
The issue exists in stripes-core in all versions >= 2.17.0. Commit that has introduced the issue: https://github.com/folio-org/stripes-core/commit/d51ea404280d57e974aa296d57e08d92a5a40a4e
Replacing
`^(\d+[.-]*)+\d+$`
by
`^\d+([.-]+\d+)*$`
matches the same but …
=> STCOR-535: Regexp denial of service (ReDoS) in validatePhoneNumber

CHANGELOG.md, src/components/MainNav/MainNav.js, test/bigtest/interactors/app.js, test/bigtest/tests/nav-test.js
https://issues.folio.org/browse/STCOR-531
As a staff person
I want to access the FOLIO help site via a ? help icon from the upper right hand side of the universal header
So that I have ready access to help documentation
**Current situation or problem:** There is no way to access the help site from the UI of FOLIO
**Requirement:** To open the FOLIO UI and have access to a button on the top menu bar that launches https://docs.folio.org/docs/ in a new browser tab/window.
**Mockups**
=> STCOR-531 Add help button

CHANGELOG.md, src/components/MainNav/AppList/AppList.js
`<Dropdown>` no longer uses the `dropdownClass` prop (so it should
really be labeled as deprecated there in order to avoid this particular
console warning, though replacing one console warning with another does
seem kind of lame).
@JohnC-80, I don't see any use of this prop in `<Dropdown>` except in the [proptypes list](https://github.com/folio-org/stripes-components/blame/fcccc3af706a75b0777f1ebd05785f19907ecfd4/lib/Dropdown/Dropdown.js#L20). I think it was removed in https://github.com/folio-org/stripes-components/pull/283 (maybe?) and because of how props are destructured elsewhere, we now get a console warning. 
Refs [STCOR-539](https://issues.folio.org/browse/STCOR-539)
=> STCOR-539 clean up props to Dropdown

CHANGELOG.md, index.js, src/constants/delimiters.js, src/constants/index.js, src/hooks/useNamespace.js, test/bigtest/interactors/Namespace.js, test/bigtest/tests/use-namespace-test.js
https://issues.folio.org/browse/STCOR-537
This PR introduces a `useNamespace` hook described by @skomorokh and outlined by @doytch under [STCOR-537](https://issues.folio.org/browse/STCOR-537).
The signature currently looks like this:
````js
const [namespace, getNamespace] = useNamespace(options);
````
The `namespace` represents a namespace as a string. The `getNamespace` is a function which can be used to retrieve a namespace with a different set of options:
````js
const ns = getNamepace({ key: 'test-key' });
````
Possible options:
- key - a string which will be appended to the given namespace
- ignoreParents - a boolean which can be used to ignore the parents part from a module hierarchy. For example when `useNamespace` is executed from a plugin embedded in app module (e.g. …
=> STCOR-537: Introduce useNamespace hook

CHANGELOG.md, src/components/MainNav/ProfileDropdown/ProfileDropdown.js, translations/stripes-core/en.json, translations/stripes-core/en_US.json
Removing FOLIO's auth token from the browser does not have any effect on
an SSO token that may remain cached in the browser. In order to make
this clear, the user/service-point menu now reads,
```
Log out from FOLIO, keep SSO session
```
when SSO is configured.
Refs [STCOR-532](https://issues.folio.org/browse/STCOR-532)
=> STCOR-532 indicate that logging out of FOLIO will not end SSO session

translations/stripes-core/ko.json
Most corrupt translation strings introduced in
a793957d5c78c6b23838963f3c02b598398abd01 were repaired in
02aada3871fccace74430c42681b98d555e10d88, but not all.
=> remove corrupt korean translation

CHANGELOG.md, karma.conf.js, package.json
There are some overlapping things going on here.
* `stripes-webpack` supports the new JSX transform that means we
shouldn't have to `import React ...` any longer, but BigTest tests
fail without it when using `karma` `v4` (from `stripes-cli` `v1.2`).
* when using `karma` `v6` (from `stripes-cli` `v1.3`), the karma config
directives `files` and `preprocessors` cause test files not be found
at all.
Bumping the `stripes-cli` dep (so we get `karma` `v6`) and cleaning up
`karma.config.js` (so it is `v6` compatible, and more aligned with
configs in other repos) allows tests to run as they always did. Phew.
Refs [STCOR-551](https://issues.folio.org/browse/STCOR-551)
=> STCOR-551 configure karma for v6 compatibility

CHANGELOG.md, src/components/MainNav/ProfileDropdown/ProfileDropdown.js, translations/stripes-core/en.json
Correctly localize ProfileDropdown elements.
Fixes [STCOR-554](https://issues.folio.org/browse/STCOR-554)
=> STCOR-554 localize ProfileDropdown content

CHANGELOG.md, src/components/MainNav/MainNav.css
White-on-white does not meet the 4.5:1 color contrast threshold
standard.
Fixes [STCOR-553](https://issues.folio.org/browse/STCOR-553)
=> STCOR-553 increase ProfileDropdown color contrast

src/components/HandlerManager/HandlerManager.js
Originally, the loop at the end was just
this.components.map(Component => (
<Component key={Component.name} {...props} />
)
But when the invocation of `<Component>` got wrapped in `<ModuleHierarchyProvider>` in commit bf282ea1, the `key` was left in the wrapped `<Component>`, so it no longer appeared directly inside the list generated by `map`.
This commit fixes this by moving the `key` up a level.
=> Fix React unique-key error

CHANGELOG.md, index.js, src/loginServices.js
Export a list of available numbering system so apps that allow for
providing a locale suffix (i.e. `-u-nu-NUMBERING_SYSTEM`) don't have to
duplicate the list locally.
Refs [STCOR-555](https://issues.folio.org/browse/STCOR-555), [FOLIO-3208](https://issues.folio.org/browse/FOLIO-3208)
=> STCOR-555 list available numbering systems

CHANGELOG.md, src/components/MainNav/CurrentApp/AppContextDropdown.js
`AppContextDropdown` mistakenly used `displayName`, a value that is
passed through translation and therefore changes when the locale
changes, instead of `module`, which is constant.
Refs [STCOR-547](https://issues.folio.org/browse/STCOR-547)
=> STCOR-547 use constant value icons in AppContextDropdown

test/bigtest/tests/forgotPassword-test.js, test/bigtest/tests/forgotUsername-test.js
Tests on `#master` suddenly started failing. Yay!!! This PR addresses
the issue by removing the destructuring of the `SubmitButton`
interactor and tests that operated on the internals there in favor of
just interacting with `SubmitButton` itself. My best guess is that
something higher in the hierarchy of stripes-components interactors is
now causing a disabled button to return `false` for `isPresent` queries,
though this doesn't really hold water because there haven't been any
recent updates there in STCOM. But I have no other better explanation.
I am not thrilled with this PR for two reasons:
1. I don't know why the `SubmitButton` was destructured to begin with,
so I am hesitant to undo it given it was probably done for a reason.
1. I don't know what changed in stripes-components (or …
=> avoid interactor destructuring

package.json
New features should land on a new minor version since the last release
so that feature work and bug-fix work can be correctly separated.
=> bump minor to 8.1

CHANGELOG.md, src/components/Login/LoginCtrl.js, test/bigtest/tests/useCustomFields-test.js
Fix "404" error message when user changes password and logs in. This happens because after changing password user is redirected to `/login` route and after successful login they are not redirected. But `/login` route doesn't exist when a user is logged in.
[STCOR-582](https://issues.folio.org/browse/STCOR-582)
=> STCOR-582 Your password changed confirmation page > Continue to Login URL goes to an error page

CHANGELOG.md, package.json
When we split `stripes-core` from `stripes-webpack`, we moved some
things we shouldn't have and kept some things we didn't need.
* handlebars is a peer-dep of handlebars-loader but is not used here
* use-deep-compare is used in the error-boundary
Refs [STCOR-584](https://issues.folio.org/browse/STCOR-584)
=> STCOR-584 dependency cleanup

test/bigtest/network/index.js
And there were developers sitting at their laptops nearby, keeping watch
over their code by night. Just then, an angel of lint stood before them,
and the glory of lint shone all around them, and they were terrified.
But the angel said unto them, "Do not be afraid! For behold! I bring you
good news of great joy that will be for all the people: Today in the
module of stripes-core, I discovered one insignificant space with no
semantic value and no visual clutter, but it really bugs me anyway. And
this will be a sign to you: you will find two complaints on every PR
about it, even when they have nothing to do with this file.
And suddenly there appeared around every stripes-core PR a great
multitude of lint complaints, saying:
```
Multiple spaces found before '/\.\/.*\.js$/'
```
When the lint …
=> the most humble offering possible to the lint gods

.gitignore, CHANGELOG.md, src/components/Settings/Settings.js
- If a user selects `Settings` from the `Apps` drop-down then move focus to the `Settings` pane.
- Add `paneTitleRef` prop to `Pane` component to manage focus automatically.
- https://issues.folio.org/browse/STRIPES-731
=> STRIPES-731: Apps > Settings > Move focus to Settings pane

src/components/Settings/Settings.js
* Apply heading level (H3) to each second pane Settings > Users section header
* Apply a heading level (H3) to the System Information section header
* Remove the H3 heading from the second pane Settings > Users section header. It appears a H2 heading is already applied.
Ref: https://issues.folio.org/browse/UIU-2037
Replaces #1159
=> STCOR-587 Apply h3 tag for System Information

package.json, src/loginServices.js
Long ago (#876) we added a bunch of polyfills to stripes-core because
react-intl stopped including them and our e2e tests need them. But those
e2e tests are gone, baby, gone, so there is no reason to balloon our
bundle with a bunch of cruft that no contemporary browser requires.
(RelativeTimeFormat has been in Chrome since 2018 and Safari since 2020; 
PluralRules since 2017 and 2019 respectively, and DisplayNames since 2020 
and early 2021 respectively.)
h/t @skomorokh for noticing this disk pollution.
Refs [STCOR-588](https://issues.folio.org/browse/STCOR-588)
=> STCOR-588 prune ancient and unnecessary react-intl polyfills

.github/workflows/build-npm.yml, src/components/About/WarningBanner.js, src/components/AppIcon/tests/appIcon-test.js, src/components/CreateResetPassword/CreateResetPassword.js, src/components/CreateResetPassword/CreateResetPasswordControl.js, src/components/CreateResetPassword/components/PasswordHasNotChanged/PasswordHasNotChanged.js, test/bigtest/network/config.js, test/bigtest/network/scenarios/changePasswordSuccess.js, test/bigtest/network/scenarios/forgotUsernameSuccess.js, test/bigtest/tests/useCustomFields-test.js
* provide missing translation to avoid console pollution
* await promises in loops. otherwise, iteration will will proceed
asynchronously and check the icon sizes incorrectly, I think.
* clean some 204 responses
* do not set deprecated props on `Headline`
* avoid `setState` in then blocks if component is unmounted
* compile translations _before_ running test to avoid console noise
=> test cleanup

CHANGELOG.md, src/components/CreateResetPassword/CreateResetPasswordControl.js, src/components/CreateResetPassword/components/PasswordHasNotChanged/PasswordHasNotChanged.js
There was general disagreement about the expected prop-types for errors
related to password reset. Generally, more things seem to expect an
array than an object, leading me to think the handling of the one-error
case, where the error is directly dispatched, was just a mistake. At
least, converting that one case resolved a litany of errors, and then
the only downstream change was fixing its message display, which, come
to think of it, was probably already broken and we just never noticed
and always accepted the default error message.
Refs [STCOR-590](https://issues.folio.org/browse/STCOR-590)
=> STCOR-590 align prop-types for password reset errors

CHANGELOG.md, src/components/Root/index.js
Whooops, it wasn't even a dev-dep but we still had it in our source.
It's no longer necessary in any case since react-refresh is totally
self-contained within stripes-webpack.
Refs [STCOR-597](https://issues.folio.org/browse/STCOR-597), [STRIPES-725](https://issues.folio.org/browse/STRIPES-725)
=> STCOR-597 remove react-hot-loader cruft

package.json
Reverts folio-org/stripes-core#1171
@BogdanDenis noted the following: 
```
Configuration error:
Could not locate module ky mapped as:
ky/umd.
Please check your configuration for these entries:
{
"moduleNameMapper": {
"/ky/": "ky/umd"
},
"resolver": undefined
}
```
=> Revert "Update ky"

CHANGELOG.md, src/moduleRoutes.js, translations/stripes-core/en.json
Reverts folio-org/stripes-core#1190
to avoid the list of messages for each no permission app.
=> Revert "STCOR-619 Add message user cannot access app"

package.json, src/AppRoutes.js, src/Pluggable.js, src/moduleRoutes.js, test/bigtest/tests/useCustomFields-test.js
https://issues.folio.org/browse/STCOR-626
It looks like the `getModule` calls are currently executed during a regular render (which happens on every route change):
https://github.com/folio-org/stripes-core/blob/97bcff4029aeec39ca9ea5b69bf6192d6458f2f2/src/moduleRoutes.js#L75
https://github.com/folio-org/stripes-core/blob/97bcff4029aeec39ca9ea5b69bf6192d6458f2f2/src/Pluggable.js#L25
This was working fine till now but I think only by accident because the calls are cached in the lower level (stripes-webpack).
Unfortunately, this breaks with the lazy-loading approach and it should be addressed in a similar fashion to what happens in `Settings` (single initialization in the constructor):
https://github.com/folio-org/stripes-core/blob/f33c8b0dc3d21a5ccd2a537956d6f8942d229120/src/components/Setti …
=> STCOR-626: Cache getModule calls

CHANGELOG.md, src/components/ModuleContainer/ModuleContainer.css
https://issues.folio.org/browse/STCOR-638
This PR relates to [#1835](https://github.com/folio-org/stripes-components/pull/1835) and makes it possible to support pane content printing. (See PR [#1835](https://github.com/folio-org/stripes-components/pull/1835) to more details)
=> STCOR-638 record detail panes are empty when print

translations/stripes-core/en.json, translations/stripes-core/fr.json, translations/stripes-core/fr_FR.json
This is consistent with the UX pattern, as described [here](https://ux.folio.org/docs/guidelines/ux-patterns/duplicate-a-record/).  Adds a centralized duplicate button key to prevent modules having to provide separate translations for this common use. 
_Je parle un peu français_, so I added translations for fr and fr_FR.
=> STCOR-640: Add `button.duplicate` translation key

CHANGELOG.md, src/components/Login/Login.js
Allow the `<Login>` component's wrapper-div to be customized via CSS attributes
provided in `stripes.config.js` via `branding.style.login`. e.g.:
```
branding: {
logo: { ... },
favicon: { ... },
style: {
login: {
backgroundColor: "#fcb"
},
...
```
Refs [STCOR-643](https://issues.folio.org/browse/STCOR-643)
=> STCOR-643 allow customization of login CSS

CHANGELOG.md, src/components/MainNav/MainNav.js
Allow customization of the navigation bar's CSS via values provided in
`stripes.config.js` in `branding.style.mainNav`. e.g.
```
okapi: { 'url':'http://localhost:9130', 'tenant':'diku' },
config: {
style: {
mainNav: {
backgroundColor: "#036",
}
},
```
Refs [STCOR-644](https://issues.folio.org/browse/STCOR-644)
=> STCOR-644 allow customization of mainnav CSS

CHANGELOG.md, jest.config.js, package.json, src/components/About/About.js, src/components/About/AboutInstallMessages.js, src/components/About/AboutInstallMessages.test.js, src/queries/index.js, src/queries/useConfigurations.js, src/queries/useConfigurations.test.js, src/queries/useOkapiEnv.js, src/queries/useOkapiEnv.test.js, test/jest/helpers/harness.js, test/jest/helpers/intl.js, test/jest/jest.setup.js, test/jest/turn-off-warnings.js
Optionally decorate the `/settings/about` (Settings: Software versions)
page with information from Okapi Environment variables,
mod-configuration values, or stripes.config, in descending order. Three
values may be displayed: a version, an install date, and a message.
The Okapi Environment keys are `ABOUT_INSTALL_DATE`,
`ABOUT_INSTALL_VERSION`, and `ABOUT_INSTALL_MESSAGE`. The mod-configuration
values all correspond to `module`: `@folio/stripes-core`, `configName`:
`aboutInstall` and the `code`s `date`, `version`, and `message`. The
`stripes.config.js` values are from the `stripes.config` object with the
keys `aboutInstallDate`, `aboutInstallVersion`, and
`aboutInstallMessage`.
Refs [STCOR-603](https://issues.folio.org/browse/STCOR-603), NH-603 (No taxes, no services! Live Free or Die!)
=> STCOR-603 show supplemental data on the /settings/about page

CHANGELOG.md, src/loginServices.js
Add `cs-CZ` (Czech, Czechia) to the list of supported locales.
Refs [STCOR-645](https://issues.folio.org/browse/STCOR-645)
=> STCOR-645 add cs_CZ to supported locales

src/components/NestedRouter.js
We are in a situation where passing information down from the top level Route is necessary, and can be accomplised y passing props to a child function, however this trips PropTypes.
Currently working around by using Route from react-router-dom, but would be nice to expand PropTypes here so we don't need a separate import for this use case
=> STCOR-652: Extend Prop-Types of Route

package.json
@apollo/client@"^3.2.1" from stripes-core@7.2.0 causes a peer-dep inconsistency
https://issues.folio.org/browse/STCOR-540
=> STCOR-540 - bump up graphql version

CHANGELOG.md, src/components/Root/Root.js
Leverage `stripes.config.suppressIntlErrors` to suppress warnings in addition to errors, now that there is FINALLY support for the [`onWarn` prop](https://github.com/formatjs/formatjs/issues/3454) as of `v5.25.1`.
See also PR #912 where we added `onError` handling.
Refs [STCOR-659](https://issues.folio.org/browse/STCOR-659)
=> STCOR-659 suppress react-intl warnings

index.js, src/init.js
https://issues.folio.org/browse/STRIPES-820
Expose `App` initialization via function so it can be consumed by other modules.
This is a temporary approach to prove that `stripes-ui` will work as expected.
The final goal will be to move the `App` component and all other required parts to `stripes-ui` out of the `stripes-core`.
The other PRs related to this work that should be merged after this one are:
https://github.com/folio-org/stripes/pull/182
https://github.com/folio-org/stripes-webpack/pull/80
=> STRIPES-820: Expose app initialization

CHANGELOG.md, src/components/CreateResetPassword/components/PasswordValidationField/PasswordValidationField.js
This PR relates to [STCOR-657](https://issues.folio.org/browse/STCOR-657)
The query was removed as it was invalid and not used by BE
=> STCOR-657 PasswordValidationField swallows error messages from API queries

CHANGELOG.md, package.json
Bump the major version to accomodate breaking changes, mostly the removal of long-deprecated props in stripes-components but also the removal of service-point handling and slicing off routing into stripes-ui here in stripes-core.
=> bump major version to 9.0

CHANGELOG.md, src/loginServices.js
The additional clause
```
(cql.allRecords=1 NOT userId="" NOT code="")
```
guarantees the response will contain only a single row. Without that clause, the clause was limited to
```
module==ORG and configName==localeSettings
```
which allowed it to be potentially be polluted by other rows that included `userId` or `code` values, meaning the result was non-deterministic.
Refs [STCOR-675](https://issues.folio.org/browse/STCOR-675)
=> STCOR-675 use stricter tenant-locale query

src/Pluggable.js
Provide `key` on children of an array during render. [It's the law](https://reactjs.org/docs/lists-and-keys.html#keys).
Refs [STCOR-684](https://issues.folio.org/browse/STCOR-684)
=> STCOR-684 list elements need a key prop. it's the law.

CHANGELOG.md, index.js, src/loginServices.js, src/loginServices.test.js, src/okapiActions.js, src/okapiReducer.js
*BREAKING*:
Remove functions related to service points. Given this repo does not have a direct dependency on the `inventory` interface, it must not contain code that relies on values provided by that interface. Handling of service point data on login moved to ui-service-points in [UISP-32](https://issues.folio.org/browse/UISP-32), hence the corresponding functions that did that work here can now be removed.
Since these functions were publicly exported, this is a breaking change.
Refs [STCOR-650](https://issues.folio.org/browse/STCOR-650)
=> STCOR-650 remove setServicePoints, setCurServicePoint

src/AppRoutes.js
Lint whines about `stripes` being declared in multiple scopes in this file. Effectively, we have three different incarnations of `stripes` here (ugh) which is still awful, but at least now they have three different names. All this change does is separate the names to avoid repeating the same name in multiple scopes; it shouldn't actually change any behavior.
We can handle this in a totally separate PR if folks think that would be better.
=> rename "stripes" in its different scopes

CHANGELOG.md, src/components/MainNav/CurrentApp/AppContextMenu.js
The app context dropdown remains open ([screencast](https://issues.folio.org/secure/attachment/56660/2023-01-23_15h04_55.mp4)) when switching from the `MARC Authority` app to `Inventory`. Because in the `Inventory` app, the [AppContextMenu](https://github.com/folio-org/ui-inventory/blob/master/src/index.js#L83) component is not rendered until the [DataProvider](https://github.com/folio-org/ui-inventory/blob/master/src/index.js#L75) has received all the requested data. Because in the [DropdownMenu](https://github.com/folio-org/stripes-components/blob/master/lib/DropdownMenu/DropdownMenu.js#L47) the [mouse listener](https://github.com/react-bootstrap/react-overlays/blob/master/src/useRootClose.ts#L111) in the `useRootClose` hook fires before the listener is …
=> STCOR-680: App context menu does not fully close after switching from "MARC Authority" app to "Inventory"

CHANGELOG.md, package.json
Align the versions of stripes-connect referred to in package.json on the version that is part of stripes v8. This will prevent a noisy yarn warning during install at the application/platform level.
Refs [STCOR-705](https://issues.folio.org/browse/STCOR-705)
=> STCOR-705 align stripes-connect's dev/peer versions

CHANGELOG.md, index.js
https://issues.folio.org/browse/STCOR-711
This PR exposes `StripesContext`, `LastVisitedContext` and `withLastVisited` so the can be accessible via `@folio/stripes/core`
=> STCOR-711: Expose additional functionality so it can be consumed via other modules

CHANGELOG.md, index.js, src/components/HandlerManager/HandlerManager.js, src/components/MainNav/ProfileDropdown/ProfileDropdown.css, src/components/MainNav/ProfileDropdown/ProfileDropdown.js, src/components/MainNav/ProfileDropdown/ProfileDropdown.test.js, src/loginServices.js, src/loginServices.test.js, src/okapiReducer.js, src/okapiReducer.test.js
https://issues.folio.org/browse/STCOR-689
https://issues.folio.org/browse/STCOR-690
As a central tenant of a consortium, it should be able to switch the current context to manage institutional tenants. Header `X-Okapi-Tenant` acts as a pointer to the current context when sending requests to the server.
---
If a user login into the consortium central tenant, he expects to see its name in the top-right corner of the screen (in the profile dropdown trigger, above a current SP name).
- Validate user based on current tenant value stored in a session (if absent - use tenant from stripes configs);
- Expose `updateTenant` service, which will update the current tenant, fetch resources (perms, SPs and etc.) and update session;
- Allow `<HandlerManager>` to invoke handlers for other module types …
=> STCOR-689 STCOR-690 Support switch consortium active affiliation

CHANGELOG.md, src/components/CreateResetPassword/CreateResetPasswordControl.js, src/components/CreateResetPassword/utils.js, src/components/CreateResetPassword/utils.test.js
purpose:
for consortia we have one UI bundle for central tenant as a result there is no way to identify correct tenant to reset password
https://issues.folio.org/browse/STCOR-724
approach:
BE defines tenant in query param that can be used in headers, in case it's not defined (old links) bundle tenant is used instead
=> STCOR-724 Use tenant query param for password reset

src/RootWithIntl.js, src/components/RegistryLoader.js, src/components/Root/Root.js, src/okapiReducer.js
Load translations when loading remote modules. 
App-icon sizing is off now. Those must load before translations are processed. 
Refs [STCOR-718](https://issues.folio.org/browse/STCOR-718), [STRIPES-861](https://issues.folio.org/browse/STRIPES-861)
=> STCOR-718 load remote translations

CHANGELOG.md, index.js, src/consortiaServices.js, src/consortiaServices.test.js
With many modules implementing Consortia features it's a good idea to move common code into shared modules
Added two functions:
- `checkIfUserInCentralTenant` checks if user is in a central tenant
- `checkIfUserInMemberTenant` checks if user is in a member tenant
We need two because in a case when we're not in a Consortia environment both will return `false`.
So code like:
```js
if (!checkIfUserInCentralTenant(stripes)) {
// do something only for member tenants
}
```
will do `something` on non-Consortia environment because `checkIfUserInCentralTenant` returns `false` when the interface is not present
[STCOR-733](https://issues.folio.org/browse/STCOR-733)
=> STCOR-733 Added new isUserInCentralTenant helper

src/loginServices.js, src/loginServices.test.js
**purpose**: after UAT it was reported that change tenant process is pretty slow, and it was found that initial implementation (https://issues.folio.org/browse/STCOR-690) is not so efficient as it could be because it loads translations etc twice, additionally related data loading triggers storage changes as a result whole page is unnecessary for "change tenant" rerendered several times
**approach**: split existing functionality into smaller pieces and reuse it in `updateTenant` method to just update `okapiSession`, in this case addition data will be loaded 1 time and without any rerenders
Note: changelog is not updated as it's just a tech adjustment of original implementation, so changelog already contains required info
=> STCOR-739 Reduce duplicated requests when changing tenant in consortium

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
In CI, bump NodeJS v16 to v18.
Refs [STCOR-738](https://issues.folio.org/browse/STCOR-738)
=> STCOR-738 use NodeJS v18 in CI

CHANGELOG.md, src/useOkapiKy.js
Based on the [STCOR-594](https://issues.folio.org/browse/STCOR-594), timout inside useOkapiKy should be configurable
=> STCOR-594 read ky timeout from stripes-config value

CHANGELOG.md, src/useOkapiKy.js
Introduce an optional `tenant` argument to `useOkapiKy` hook to be able to override headers with a provided tenant.
Refs: https://issues.folio.org/browse/STCOR-747
=> STCOR-747: Provide optional tenant argument to `useOkapiKy` hook

CHANGELOG.md, index.js
[STCOR-749](https://issues.folio.org/browse/STCOR-749)
Since `validateUser` method is used in `ui-inventory`, we need to import this one from `@folio/stripes/core` instead of `@folio/stripes/core/src/loginServices`
=> STCOR-749: Allow to import validateUser function from @folio/stripes/core

src/components/AppIcon/AppIcon.css
This ensures the wrapping element, `.appIcon`, also has minimum height/width constraints.
=> [STCOR-752]: Ensure <AppIcon> is not cut off

src/components/AppIcon/AppIcon.css
Reverts folio-org/stripes-core#1355
`<AppIcon>` may be used like `<AppIcon icon="foo">Title of an instance</AppIcon>` in SearchAndSort results lists, and this sets the width incorrectly.
=> Revert "[STCOR-752]: Ensure <AppIcon> is not cut off"

CHANGELOG.md, src/components/AppIcon/AppIcon.css
This ensures the wrapping element, `.appIcon`, also has minimum width constraints.
Unlike #1355, we've also made sure that this works both in pane headers and SearchAndSort lists:
=> [STCOR-752]: Ensure <AppIcon> is not cut off (for real this time)

CHANGELOG.md, src/service-worker.js, src/service-worker.test.js
Rotate tokens slightly before they expire. This solves a problem in ui-data-export where every-five-second polling has caused some requests to land in a gap of about three seconds between when the AT was actually minted and when we stored it on the client side. i.e. it makes it much less likely that a token will expire in flight.
Refs [STCOR-574](https://issues.folio.org/browse/STCOR-754)
=> STCOR-574 rotate tokens well before they expire

CHANGELOG.md, src/loginServices.js, src/loginServices.test.js, src/service-worker.js, src/service-worker.test.js, test/bigtest/tests/login-test.js
The most important work here is fixing the bug from #1361 that incorrectly evaluated whether a token was still valid. The original implementation shrank the total lifespan of the token rather than shrinking only the period of its lifespan in the future.
Additional improvments here include:
* evaluate `navigator.serviceWorker` more cautiously; some browsers (e.g. Firefox in Incognito) may deny access to service workers. See [STCOR-757](https://issues.folio.org/browse/STCOR-757) for additional details.
* use `{ source, type, value }` shaped messages consistently when exchanging messages with the service worker.
* shrink the tokens' validity windows when receiving the `TOKEN_EXPIRATION` message instead of calculating the shorter window each time the token is evaluated. This is more …
=> STCOR-756 correctly evaluate token lifespan

index.js, src/loginServices.js, src/loginServices.test.js, src/service-worker.js, src/service-worker.test.js, src/serviceWorkerRegistration.js, src/serviceWorkerRegistration.test.js, test/bigtest/tests/login-test.js, test/jest/__mock__/index.js, test/jest/__mock__/microStripesConfig.mock.js
A service worker's global state is reset after each sleep/wake cycle,
meaning the `okapiUrl` and `okapiTenant` values so lovingly sent to the
service worker during registration are likely to be promptly forgotten
as soon as the browser is idle for a few minutes and decides it would be
good to clean up inactive processes.
Here, those values are directly imported from a virtual module created
at build-time by stripes-webpack, which forwards the values from the
stripes-config object (most likely, the `stripes.config.js` file) and
allows them to be compiled directly into the generated
`service-worker.js` asset.
An alternative approach would be to pass in those values as URL
parameters when the service worker is registered.
h/t @mkuklis and @JohnC-80 who did the heavy lifting here, both in …
=> STCOR-759 read okapi config from micro-stripes-config

CHANGELOG.md, src/components/MainNav/MainNav.js
Normally the console is cleared on logout. This is good for security but bad for debugging in the case where a user may be automatically logged out due to RTR.
Refs [STCOR-761](https://issues.folio.org/browse/STCOR-761)
=> STCOR-761 allow console to be preserved on logout

CHANGELOG.md, src/service-worker.js, src/service-worker.test.js
Instead of catching errors from non-Okapi requests and converting them to rejected promises, just `return fetch()` straight up, whatever that response contains.
h/t @miketaylor for pointing me in this direction, and reading minified code to try to suss the problem. That's dedication!
Refs [STCOR-759](https://issues.folio.org/browse/STCOR-759), [UILDP-129](https://issues.folio.org/browse/UILDP-129)
=> STCOR-759 return non-okapi request fetches as-is

CHANGELOG.md, src/service-worker.js
`@folio/stripes-webpack` still looks for `service-worker.js`, so we provide a dummy function here to keep the API intact. This API is never invoked; this service worker is never registered (though it wouldn't matter since it doesn't listen for any events).
Refs [STCOR-671](https://issues.folio.org/browse/STCOR-671), [FOLIO-3627](https://issues.folio.org/browse/FOLIO-3627)
=> STCOR-671 provide empty service worker

yarn.lock
@adobe/css-tools < 4.3.2 is vulnerable to CVE-2023-48631.
=> CVE-2023-48631 require @adobe/css-tools >= 4.3.2

CHANGELOG.md, index.js
Export `getEventHandler` to be able to create events in other modules.
https://github.com/folio-org/ui-consortia-settings/pull/101
https://github.com/folio-org/ui-inventory/pull/2373
[STCOR-770](https://issues.folio.org/browse/STCOR-770)
=> STCOR-770: Export getEventHandler to be able to create events in other modules.

src/RootWithIntl.js, src/components/PreLoginLanding/PreLoginLanding.js
- When navigating from tenant selection screen to login screen, this allows user to navigate back with the browser back button.
- Removed duplicate `config` propType definition.
- Removed unused `LoginComponent`.
=> Add back button support to multi-tenant workflow

src/Stripes.test.js, src/configureLogger.test.js, test/jest/__mock__/stripesConfig.mock.js
Rescue tests from [STCOR-674](https://issues.folio.org/browse/STCOR-674)/PR #1268. That work is stale/outdated/incomplete/unscheduled, but the tests are still nice.
Refs [STCOR-785](https://issues.folio.org/browse/STCOR-785)
=> STCOR-785 add tests for Stripes, configureLogger

src/discoverServices.js
Previously only showed first application in the list before quietly failing on a null exception. Now shows all applications returned in API response.
=> Graceful handling when provides array is null in API response

src/App.js
Check parsed clientId, if undefined use clientId defined in okapiConfig
=> STCOR-790: fix clientId=undefined on the constructed keycloak url

src/components/CreateResetPassword/CreateResetPasswordControl.js
When the `users-keycloak` interface is available, use the endpoints it provides in place of the legacy endpoints.
Refs [STCOR-795](https://issues.folio.org/browse/STCOR-795), [UIU-3031](https://issues.folio.org/browse/UIU-3031)
=> STCOR-795 optionally use users-keycloak endpoint for password reset

test/bigtest/network/config.js
Provide a fully-populated user object, instead of an empty one, from `/bl-users/_self` in tests. Tests that expect an authenticated user may fail if they end up calling the endpoint and don't receive the expected data. It's unclear exactly why we're hitting this glitch now, but here we are. 🤷 
h/t @JohnC-80 for figuring this out. He deserves the credit here; I'm just the codemonkey who happened to be available to implement his suggested fix.
Refs [STCOR-798](https://issues.folio.org/browse/STCOR-798)
=> STCOR-798 fully populate /bl-users/_self API response in tests

src/components/PreLoginLanding/PreLoginLanding.js
- Fixes [STCOR-794](https://issues.folio.org/browse/STCOR-794)
- Use an element Ref to determine if submit button should be disabled since using `okapi.tenant` retains the previous value when navigating back to the tenant selection screen.
=> STCOR-794: Disable Continue button when no tenant selected

CHANGELOG.md, test/bigtest/helpers/setup-application.js
The call to `localForage.clear` returns a promise, so it's best to handle it within an async call so that tests can wait for it. This seems to explain some difference we're seeing in timing between local test runs and CI such as the test runs from https://github.com/folio-org/stripes-core/pull/1392
=> STCOR-801 Move async localforage.clear to afterEach

.stylelintrc, CHANGELOG.md, package.json, src/components/AppIcon/AppIcon.css, src/components/BadRequestScreen/BadRequestScreen.css, src/components/CreateResetPassword/CreateResetPassword.css, src/components/ForgotPassword/ForgotPasswordForm.css, src/components/ForgotUserName/ForgotUserNameForm.css, src/components/Front.css, src/components/Login/Login.css, src/components/MainNav/MainNav.css, src/components/MainNav/NavButton/NavButton.css, src/components/MainNav/NavDivider/NavDivider.css, src/components/MainNav/NavDropdownMenu/NavDropdownMenu.css, src/components/MainNav/ProfileDropdown/ProfileDropdown.css, src/components/NoPermissionScreen/NoPermissionScreen.css, src/components/Notification/Toast.css, src/components/OrganizationLogo/OrganizationLogo.css, src/components/ResetPasswordNotAvailableScreen/ResetPasswordNotAvailableScreen.css, src/components/SystemSkeleton/SystemSkeleton.css
This PR copies the `stylelint` config from `stripes-components` to apply similar rules.
The changes, in a nutshell:
- Using media-range notation for media queries
- `@media screen and (max-width: 440px)` becomes `@media screen and (width <= 440px)`
- Color function notation - remove commas, represent alpha with percentage proceeded by a slash.
- `rgba(0, 0, 0, 0.75)` becomes `rgba(0 0 0 / 75%)`.
- Consolidating individual properties to single shorthand properties.
- use `inset:` property and shorthand values as opposed to `top`, `left`, `bottom`, and `right`. 
- Some declaration re-arrangement due to descending specificity
- `.navButton::before` being declared before `.navButton` would have to be switched.
=> STCOR-799 Upgrade/configure stylelint.

src/loginServices.js
Optional chaining may return undefined. We fixed this on master in PR #1392 but that fix may not have been cautious enough for the kind of sparse data we may get back when dealing with Keycloak users. When stripes itself handles authentication, it will populate localstorage with permissions derived from that login response, but with keycloak in play that never happens; permissions are only _ever_ read from the response to the `/_self` request and thus never properly initialized.
Refs [STCOR-793](https://issues.folio.org/browse/STCOR-793)
=> STCOR-793 avoid potentially unsafe optional chaining

CHANGELOG.md, src/components/Settings/Settings.js, src/components/Settings/tests/Settings.test.js, test/jest/__mock__/currencies.mock.js, test/jest/__mock__/index.js, test/jest/__mock__/stripesComponents.mock.js
Fix issue with permissions not updating when user changes active affiliation
Issue was caused by `connectedModules` only being create once in the component constructor, and all following renders were using old cached `stripes` object
To fix it I refactored the component to make it functional and used `useMemo` to generate `connectedModules`.
https://github.com/folio-org/stripes-core/assets/19309423/c0a97dcb-6bf1-4f07-9071-ba52b3151d12
[STCOR-797](https://issues.folio.org/browse/STCOR-797)
=> STCOR-797 Make `<Settings>` a functional component. Update connected modules when `stripes` object changes.

src/App.js, src/RootWithIntl.js, src/RootWithIntl.test.js
- Fulfills [STCOR-803](https://folio-org.atlassian.net/browse/STCOR-803).
- If `config.confirmLogout` is truthy and `okapi.authnUrl` is set, then user is brought to confirm logout page, otherwise logout happen immediately.
- Small lint fix.
=> Add opt-in "Really logout?" stripes.config.js option

src/components/About/About.js, src/components/About/About.test.js, src/discoverServices.js
Reverts folio-org/stripes-core#1418
The conditional here checked `okapi.tenantOptions`; it must check `config.tenantOptions`.
=> Revert "STCOR-810 cleanup deprecated entitlement params"

src/components/About/About.js, src/components/About/About.test.js, src/discoverServices.js, src/loginServices.test.js
Remove references to the `stripes.config.js::config` values `tenantManagerUrl` and `applicationManagerUrl`. These were present in early drafts of the new discovery work but have since been deprecated and therefore must be removed from code as well.
Replaces #1418, which did this work incorrectly (referring to `okapi.[...]` instead of `config.[...]`).
Refs [STCOR-810](https://folio-org.atlassian.net/browse/STCOR-810)
=> STCOR-810 CORRECTLY clean up deprecated entitlement params

CHANGELOG.md, src/loginServices.js
The shape of the permissions object differs between responses from calls to `login` and calls to `_self`. This is not awesome. We didn't notice this glitch prior to implementing keycloak because when resuming an existing session (i.e. when calling `_self`), permissions are set as the union of permissions in storage (i.e. stored by a call to `login`) and those from the call to `_self`. We just never noticed that the latter was always empty.
With keycloak handling authentication, however, the _only_ permissions we ever receive are in the response from `_self`, so we noticed this immediately.
Why is this relevant outside a keycloak implementation? If you change your permissions and reload, the new permissions will now take effect (because they'll be correctly read from the response from …
=> STCOR-813 correctly parse .../_self permissions (#1421)

CHANGELOG.md, src/loginServices.js
When restoring an existing session, after discovery, do not fetch from `/saml/check` unless the `login-saml` interface (indicating SSO/SAML is available). The 404 clutters the log.
I don't have tests for this. It's a real simple fix; it's a real PITA to mock, but we can try if that's a deal-breaker.
Refs [STCOR-816](https://folio-org.atlassian.net/browse/STCOR-816)
=> STCOR-816 only fetch /saml/check when login-saml is present

CHANGELOG.md, src/queries/useChunkedCQLFetch.js, src/queries/useChunkedCQLFetch.test.js
- Fulfills [STCOR-821](https://folio-org.atlassian.net/browse/STCOR-821)
- Allow for parameter idName to be overridden to allow for using other IDs when id alone is too ambiguous (such as a case where userId, roleId, etc is needed).
- Allow for parameter limit to be overridden if a different response limit is needed.
=> STCOR-821 Add `idName` and `limit` as passable props to `useChunkedCQLFetch`

CHANGELOG.md, src/components/ForgotPassword/ForgotPasswordForm.js, src/components/ForgotUserName/ForgotUserNameForm.js
https://folio-org.atlassian.net/browse/STCOR-742
For a11y purposes, autocomplete is inadequate for describing the intent of this field. The list of acceptable values for this are across the spectrum, but none capture that of something with such a variable type - an email address or a phone number.
=> STCOR-742 Remove autoComplete attribute from 'forgot' fields.

yarn.lock
`follow-redirects` < `1.15.6` is vulnerable to CVE-2024-28849.
=> CVE-2024-28849 require follow-redirects >= 1.15.6

CHANGELOG.md, src/RootWithIntl.js, src/components/CreateResetPassword/CreateResetPasswordControl.js, src/components/CreateResetPassword/CreateResetPasswordControl.test.js
- Fulfills [STCOR-820](https://folio-org.atlassian.net/browse/STCOR-820)
- Add support for optional URL parameter `resetToken` which allows us to use longer keys since path has a much smaller allowable length than URL params
- Removed token param passed into `<CreateResetPassword>` component since it's not used there.
=> STCOR-820 For the /reset-password route, allow token to be specified in the path or query arguments

src/components/AuthnLogin/AuthnLogin.js, src/components/Root/FFetch.js, src/loginServices.js
Include `/authn/token` on the list of always-permissible API in order to
allow OTP-for-cookie exchange on return from authentication. Without
this allowance in place, stripes will get stuck in a loop bouncing
between the authn-server (which believes, correctly, that the user has
authenticated) and stripes (which believes, wrongly, that the user has
not authenticated because its "valid AT?" check fails). The AT won't be
valid until after we get to exchange the OTP for an AT by visiting
`/authn/token`.
=> STCOR-789-follow-up: Include /authn/token on the list of always-permissible API

yarn.lock
`express` < 4.19.2 is vulnerable to CVE-2024-29041
=> CVE-2024-29041 require express >= 4.19.2

CHANGELOG.md, src/App.js, src/components/Namespace/useNamespace.js
Enable [`<StrictMode>`](https://react.dev/reference/react/StrictMode) by default, allowing it to be turned off via the `stripes.config.js` prop `config.ignoreStrictMode: true`.
Refs [STCOR-841](https://folio-org.atlassian.net/browse/STCOR-841)
=> STCOR-841 enable StrictMode by default

CHANGELOG.md, src/components/CreateResetPassword/CreateResetPasswordControl.js, src/components/CreateResetPassword/components/PasswordSuccessfullyChanged/PasswordSuccessfullyChanged.js
- Fixes [STCOR-845](https://folio-org.atlassian.net/browse/STCOR-845).
- Eureka back-end doesn't recognize `/login` route, so base URL `/` should be used instead.
=> STCOR-845 Redirect correctly after changing password

src/loginServices.test.js
The previous commit re-enabled logout by correctly passing the `x-okapi-tenant` header in the `/authn/logout` request. It turns out that if you want read the tenant from the store in a test, you have to mock the store in your test. WHO KNEW???
Replaces #1478
=> rebase-cleanup: restore logout AND ITS TESTS

CHANGELOG.md, src/components/OIDCLanding.js, src/components/OIDCLanding.test.js
The request to `/authn/token` pulls an OTP from the query string and exchanges it for AT/RT cookies. If, somehow, the browser already has cookies and sends them along on this request, it causes a negative feedback look because the OTP and the cookies are out of sync. The old AT/RT cookies will cause the endpoint to return 4xx, which will result in a redirect back to keycloak, which will find its (still perfectly valid) authentication cookies, which will cause it redirect back to stripes with a new OTP ... and the cycle repeats.
Thus, when we are exchanging an OTP, we don't want to send any cookies. We want the to send the OTP and have new cookies from the response overwrite anything that was previously stored.
Refs [STCOR-853](https://folio-org.atlassian.net/browse/STCOR-853)
Replaces …
=> STCOR-853 do not include credential in /authn/token request

CHANGELOG.md, src/RootWithIntl.test.js, src/Stripes.js, src/components/AuthnLogin/AuthnLogin.js, src/components/OIDCLanding.js, src/components/OIDCLanding.test.js, src/components/OIDCRedirect.test.js, src/components/PreLoginLanding/PreLoginLanding.js, src/loginServices.js
- Fulfills [STCOR-787](https://folio-org.atlassian.net/browse/STCOR-787).
- Removed dependence on `okapi.tenant` and `okapi.clientId` since those same values are now defined in `config.tenantOptions`.
- Removed dependence on `config.isSingleTenant` since a single tenant in `config.tenantOptions` should always caused the tenant selection screen to be skipped.
- Unrelated: add a fallback in `loginServices.js`if user object not returned from local storage, then default to user from `/_self` response. I ran into this issue causing login to crash occasionally on localhost and it was annoying, so adding a graceful fallback here.
=> [STCOR-787] Always retrieve clientId and tenant values from config.tenantOptions in stripes.config.js

CHANGELOG.md, src/components/About/AboutApplicationVersions.js, src/components/About/AboutModules.js, src/discoverServices.js, src/discoverServices.test.js
Follow-up to the original PR (#1385, [STCOR-773](https://folio-org.atlassian.net/browse/STCOR-773)). There were at least two gotchas there:
1. The attribute key in the response changed from `ui-modules` to `uiModules`
2. Since frontend and backend applications are stored under separate keys, the discovery reducer needed to grab values from both keys.
Refs [STCOR-859](https://folio-org.atlassian.net/browse/STCOR-859)
=> STCOR-859 list UI apps under apps/modules/interfaces column

src/components/Root/FFetch.js, src/components/Root/FFetch.test.js, src/components/Root/constants.js, src/loginServices.js
Not all authentication-related responses are created equal. If the response contains AT expiration data, i.e. it is a response from `/bl-users/login-with-expiry`, use that data to configure RTR. If the response does not contain such data, i.e. it is a response from `/bl-users/_self`, pull AT expiration data from the session and use that. If we still don't have any AT expiration data, cross your fingers and try rotating in 10 seconds.
Previously, we did not ever check the session, so RTR always fired 10 seconds into a resumed, which is exactly the situation faced in e2e tests.
This doesn't precisely handle the issue faced by e2e tests that stall when the RTR request fires, but leveraging the session data should push the RTR request far enough into the future that most e2e tests will now …
=> STCOR-776 optionally schedule RTR based on session data

src/components/Root/FFetch.js, src/loginServices.js
There are many small differences in how keycloak and okapi respond to authentication related requests.
* permissions are structured differently in Okapi between `login` and `_self` requests and depending on whether `expandPermissions=true` is present on the request; keycloak always responds with a flattened list.
* token expiration data is nested in the login-response in Okapi but is a root-level element in the `/authn/token` response from keycloak.
Refs [STCOR-776](https://folio-org.atlassian.net/browse/STCOR-776), [STCOR-846](https://folio-org.atlassian.net/browse/STCOR-846)
=> STCOR-776 RTR adjustments for keycloak

CHANGELOG.md, src/loginServices.js
When resuming an existing session, populate `stripes.user.user` exactly the same way as when creating a new session. Principally, this means leveraging the return value from `spreadUserWithPerms` over `user`, instead of using the raw `user` value from the response, which spreads the `user.personal` attributes.
Refs [STCOR-860](https://folio-org.atlassian.net/browse/STCOR-860)
=> STCOR-860 correctly populate stripes.user.user on reload

yarn.lock
`ws` >= 8.0.0 and <= 8.17.0 is vulnerable to CVE-2024-37890.
=> CVE-2024-37890 use ws < 8, >= 8.17.1

src/components/AuthnLogin/AuthnLogin.js, src/components/Root/FFetch.js, src/components/Root/token-util.js, src/components/Root/token-util.test.js, src/components/SSOLanding/useSSOSession.js, src/components/SSOLanding/useSSOSession.test.js, src/discoverServices.js
- Fixes issues introduced in https://github.com/folio-org/stripes-core/pull/1487.
- Fulfills [STCOR-787](https://folio-org.atlassian.net/browse/STCOR-787).
- This ensures that stripes.config.js is only read once on application load. 
- If there is only 1 tenant, it is saved to `okapi.tenant`.
- If there is > 1 tenant, user selects the tenant and then it is saved to `okapi.tenant`.
=> STCOR-787 Fix tenant and clientId references

CHANGELOG.md, src/RootWithIntl.js, src/RootWithIntl.test.js, src/components/AuthnLogin/AuthnLogin.test.js, test/bigtest/helpers/setup-application.js, test/jest/__mock__/stripesComponents.mock.js
Stripes should render `<ModuleContainer>` either when discovery is complete or when okapi isn't present at all, i.e. when `stripes.config.js` doesn't even contain an `okapi` entry. What's most amazing about this bug is not the bug, which is a relatively simple typo, but that it didn't bite us for more than six years.
Ignore the "new" AuthnLogin test file; those tests were previously stashed in `RootWithIntl.test.js` for some reason and have just been relocated.
See also #153, where this bug was introduced, and #1497, where it is fixed on the master branch (yes, we would eventually pick that up via rebasing, but I'm impatient).
Refs [STCOR-864](https://folio-org.atlassian.net/browse/STCOR-864)
=> STCOR-864 correctly evaluate typeof stripes.okapi

src/components/LogoutTimeout/LogoutTimeout.js, src/components/LogoutTimeout/LogoutTimeout.test.js, src/components/MainNav/MainNav.js, src/components/SessionEventContainer/SessionEventContainer.js, src/components/SessionEventContainer/SessionEventContainer.test.js, test/jest/__mock__/stripesComponents.mock.js
Two things happen when idle-session-timeout kicks in:
1. the redux store is updated to clear out the session
2. the URL is updated to `/logout-timeout`
It sounds simple, but it gets messy when `<RootWithIntl>` re-renders when the store updates because that's where routes are defined. Previously, with event-handlers separately calling `logout()` to update the store and `history.push()` to update the URL, you could end up in an unexpected situation such as being logged-out before the URL updated to `/logout-timeout`, causing the default route-match handler to kick in and redirect to the login screen.
The changes here consolidate calls to `logout()` into the components bound to `/logout` (`<Logout>`) and `/logout-timeout` (`<LogoutTimeout>`). Event handlers that previously did things like …
=> STCOR-865 call logout() exclusively from logout-* routes

src/hooks/useUserSelfTenantPermissions.js, src/hooks/useUserSelfTenantPermissions.test.js, src/hooks/useUserTenantPermissionNames.js, src/hooks/useUserTenantPermissionNames.test.js, src/hooks/useUserTenantPermissions.js, src/hooks/useUserTenantPermissions.test.js
Refs [STCOR-834](https://folio-org.atlassian.net/browse/STCOR-834). 
Create separate hooks to retrieve permissions, one for getting okapi permissions, and second getting permissions from users-keycloak/_self endpoint. And depending on if roles interface presented use okapi permissions or users-keycloak permissions.
=> STCOR-834: refactor useUserTenantPermissions to use _self endpoint permissions instead of okapi permissions if roles interface is presented

CHANGELOG.md, src/components/Root/token-util.js
The RTR cycle is kicked off when processing the reponse from an authentication-related request. `/users-keycloak/_self` was missing from the list, which meant that RTR would never kick off when a new tab was opened for an existing session.
Refs [STCOR-866](https://folio-org.atlassian.net/browse/STCOR-866)
=> STCOR-866 include `/users-keycloak/_self` in auth-n requests

src/discoverServices.js, src/discoverServices.test.js
- Fulfills [STCOR-867](https://folio-org.atlassian.net/browse/STCOR-867) which is needed to complete [UID-156](https://folio-org.atlassian.net/browse/UID-156).
- Created lookup table for `permissionDisplayName` which is keyed by `permissionName`.
- Also including `uiModuleDescriptors` since those permissions are relevant.
- Note there is a separate Redux section called `okapi.currentPerms` that I considered building on, but that cannot be reused here since we need all permission names, not just the enabled ones.
=> STCOR-867 Add permission display names lookup table to Redux

CHANGELOG.md, src/components/AuthnLogin/AuthnLogin.js, src/components/Root/Events.js, src/components/Root/FFetch.js, src/components/Root/FFetch.test.js, src/components/Root/Root.js, src/components/Root/constants.js, src/components/Root/token-util.js, src/components/SessionEventContainer/FixedLengthSessionWarning.js, src/components/SessionEventContainer/FixedLengthSessionWarning.test.js, src/components/SessionEventContainer/SessionEventContainer.js, src/components/SessionEventContainer/SessionEventContainer.test.js, src/loginServices.js, src/okapiActions.js, src/okapiReducer.js, src/okapiReducer.test.js, translations/stripes-core/en.json, translations/stripes-core/en_US.json
RTR may be implemented such that each refresh extends the session by a fixed interval, or the session-length may be fixed causing the RT TTL to gradually shrink until the session ends and the user is forced to re-authenticate. This PR implements handling for the latter scenario, showing a non-interactive "this session will expire" banner before the session expires and then redirecting to `/logout` to clear out session data.
By default the warning is visible for one minute. It may be changed at build-time by setting the `stripes.config.js` value `config.rtr.fixedLengthSessionWarningTTL` to any value parseable by `ms()`, e.g. `30s`, `1m`, `1h`.
The "interesting" bits are mostly in `FFetch` where, in addition to scheduling AT rotation, there are two new `setTimer()` calls to dispatch the …
=> STCOR-862 terminate session when fixed-length session expires

src/discoverServices.js
This is so state is not dropped when adding permission display names. The previous code was improper Redux behavior because it overwrote existing state.
=> [STCOR-867] Add back missing reference to state

src/components/Root/FFetch.js, src/loginServices.js, src/okapiActions.js, src/okapiReducer.js
When a session ends due to timeout, the current location is stored in order to allow the subsequent session to begin where the previous one left off. If the "session timeout" event fires more than once, however, this could lead to the `/logout` location being stored as the "return to" location with obvious dire consequences.
There are two changes here:
1. Don't allow locations beginning with `/logout` to be stored. This fixes the symptom, not the root cause, but is still worthwhile.
2. Store the session-timeout interval ID in redux, and manage that timer via a redux action. Even though this _still_ shouldn't fire more than once, if it does, this allows us to cancel the previous timer before adding the next one. This is an attempt to fix the root cause.
Replaces #1508. This is just a …
=> STCOR-869 do not store /logout as a "return-to" URL

yarn.lock
`axios` >= 1.3.2 and <= 1.7.3 is vulnerable to CVE-2024-39338.
=> CVE-2024-39338 use axios >= 1.7.4

CHANGELOG.md, src/queries/useChunkedCQLFetch.js, src/queries/useChunkedCQLFetch.test.js
https://folio-org.atlassian.net/browse/STCOR-873
useChunkedCQLFetch uses the system tenant under the hood to send requests, however, some places in the application (specifically the consortium manager) require sending requests to a tenant other than the system one. Therefore, useChunkedCQLFetch should be updated to support an additional tenantId option, which will be used by the HTTP client. In the absence of this property, the system tenant will be used by default.
**Note:** PR for `keycloak-ramsons` branch - https://github.com/folio-org/stripes-core/pull/1519
=> STCOR-873 Ensure support for the passed `tenantId` value by `useChunkedCQLFetch` for manipulations in the context of a specific tenant

src/queries/useChunkedCQLFetch.js, src/queries/useChunkedCQLFetch.test.js
Sometimes we need to invalidate queries, to be able to do so queryKeys generated in useChunkedCQLFetch should be available. 
**Purpose**
[STCOR-872](https://folio-org.atlassian.net/browse/STCOR-872) - expose query keys from useChunkedCQLFetch.
=> STCOR-872: Return query keys from useChunkedCQLFetch 

CHANGELOG.md, src/components/SessionEventContainer/SessionEventContainer.js
Without a `key` prop to distinguish the elements rendered by `<SessionEventContainer>`, they could interact badly. In particular, if both elements (`<KeepWorkingModal>`, `<FixedLengthSessionWarning>`) were displayed, dismissing the former would cause the latter to remount, thus restarting the timer and putting it out of sync with when the session will actually end.
When React warns you about missing keys, it ain't foolin'!
Refs [STCOR-874](https://folio-org.atlassian.net/browse/STCOR-874)
=> STCOR-874 provide "key" prop to SessionEventContainer elements

CHANGELOG.md, src/components/SessionEventContainer/SessionEventContainer.js
Without a `key` prop to distinguish the elements rendered by `<SessionEventContainer>`, they could interact badly. In particular, if both elements (`<KeepWorkingModal>`, `<FixedLengthSessionWarning>`) were displayed, dismissing the former would cause the latter to remount, thus restarting the timer and putting it out of sync with when the session will actually end.
When React warns you about missing keys, it ain't foolin'!
Refs [STCOR-874](https://folio-org.atlassian.net/browse/STCOR-874)
(cherry picked from commit d4e9f1d2a84a7e6e4039328914303e4f0d15c5d8)
=> STCOR-874 provide "key" prop to SessionEventContainer elements (#1521)

src/RootWithIntl.js, src/components/AuthnLogin/AuthnLogin.js
- Refs [STCOR-876](https://folio-org.atlassian.net/browse/STCOR-876).
- Ensure `setUnauthorizedPathToSession` is called in `AuthnLogin` to remember requested path on login. I added a more explicit default path handler when user is unauthorized. I also switched from `useEffect` to `useLayoutEffect` in `AuthnLogin` so that logic is called before anything on the UI is drawn.
- Also adding `window.location.search` to session storage so URL params are remembered.
=> [STCOR-876] Remember requested URL path on Login (Regression bug) 

CHANGELOG.md, src/loginServices.js
Refs [STCOR-878](https://folio-org.atlassian.net/browse/STCOR-878)
=> STCOR-878 add nl (Dutch, Flemish) to supported locales

.github/workflows/build-npm-release.yml, .github/workflows/build-npm.yml
GitHub recently deprecated v2; v4 is still current. The breaking changes do not impact us.
=> update actions/upload-artifact to v4

src/components/AuthnLogin/AuthnLogin.js, src/components/OIDCRedirect.js, src/loginServices.js
- Fixes [STCOR-885](https://folio-org.atlassian.net/browse/STCOR-885). 
- The issue was that if a user initially navigated to a routed URL such as `/users?search=test` after redirect on login, that route is opened on all consecutive logins. By clearing session storage on logout, subsequent logins go to the default `/` route as expected.
- Cleaned up some redundant code. `setUnauthorizedPathToSession()` was being called with same params as it defaults to. Also cleaned up duplicate code within `setUnauthorizedPathToSession()`
=> [STCOR-885] Clear saved entry path so that subsequent logins will use default base URL.

CHANGELOG.md, src/components/Root/Root.js
https://folio-org.atlassian.net/browse/STCOR-893
Reword misleading error message.
=> STCOR-893: Misleading "server is down"

CHANGELOG.md, src/App.js, src/RootWithIntl.js, src/RootWithIntl.test.js, src/components/SessionEventContainer/FixedLengthSessionWarning.js, src/components/SessionEventContainer/SessionEventContainer.js, src/components/SessionEventContainer/SessionEventContainer.test.js, src/components/SessionEventContainer/style.css, src/constants/eventsPortal.js, src/constants/index.js
**Purpose:** 
[STCOR-883](https://folio-org.atlassian.net/browse/STCOR-883) - fixed-length session timeout banner may scroll off-screen or otherwise be hidden.
**Approach:** 
Place session timeout banner at the bottom of the page.
=> STCOR-883: fixed-length session timeout banner may scroll off-screen or otherwise be hidden

CHANGELOG.md, src/components/Root/token-util.js, src/components/Root/token-util.test.js
As part of the RTR lifecyle, we write a rotation timestamp to local storage when the process starts and then remove it when it ends. This is a cheap way of making the rotation request visible across tabs, because all tabs read the same shared storage.
To avoid the problem of a cancelled request leaving cruft in storage, we inspect that timestamp and consider a request "stale" if it's too old. That was the problem here: our "too old" timeout was too short; on a busy server, or on a slow connection, or on a client far from its host (say, in New Zealand), two seconds was not long enough. The rotation request would still be active when stripes considered it "stale", allowing a second request to go through. But since the first request was just slow, not dead, the second one is treated as a …
=> STCOR-895 wait a loooong time for a "stale" rotation request

CHANGELOG.md, src/App.js, src/loginServices.js, src/loginServices.test.js
[STCOR-900](https://folio-org.atlassian.net/browse/STCOR-900)  - (ECS) Automatically logged into Central tenant after logging out from Member tenant.
On login, we store tenant data in localStorage and use it as the initial state of the Redux store for okapi.tenant. When the affiliation changes, okapi.tenant updates, but the tenant in localStorage does not. As a result, the updated okapi.tenant is sent on logout. Since the tenant in the x-okapi-token and the x-okapi-tenant header on logout should match, use the tenant data stored in localStorage for the x-okapi-tenant header.
https://folio-org.atlassian.net/browse/STCOR-900
=> STCOR-900: (ECS) Automatically logged into Central tenant after logging out from Member tenant

.github/workflows/ui.yml, yarn.lock
* Bump to v1.5 to get correct snapshot version numbers
* Avoid running actions twice on push (a push triggers 2 events, but we only need to run the actions once)
* Update `yarn.lock` since v1.5 installs deps with `--frozen-lockfile`
=> use current shared workflows, current yarn.lock

src/components/Logout/Logout.js, src/components/Logout/Logout.test.js, test/jest/__mock__/stripesComponents.mock.js
PR #1551 introduced a regression to the functionality added in STCOR-849/PR #1523. The correct behavior is for the logout button on the timeout page to point to the previous location, but after #1551 the button always pointed to `/`.
Refs [STCOR-882](https://folio-org.atlassian.net/browse/STCOR-882), [STCOR-849](https://folio-org.atlassian.net/browse/STCOR-849)
=> STCOR-882 return to previous location on logout-timeout

CHANGELOG.md, index.js, src/Stripes.js, src/Stripes.test.js, src/components/IfAnyPermission/IfAnyPermission.js, src/components/IfAnyPermission/IfAnyPermission.test.js, src/components/IfAnyPermission/index.js, src/components/IfAnyPermission/readme.md, src/components/IfPermission/IfPermission.test.js
`<IfPermission>` and `stripes.ifPerm()` return `true` when the user has ALL the given permissions. `<IfAnyPermission>` and `stripes.ifAnyPerm()` return `true` when the user has ANY of the given permission.
Refs [STCOR-910](https://folio-org.atlassian.net/browse/STCOR-910)
=> STCOR-910 provide IfAnyPermission, stripes.ifAnyPerm

CHANGELOG.md, src/App.js, test/bigtest/helpers/setup-application.js
Updating `stripes-core` in SSC causes 30+ tests to fail. https://github.com/folio-org/stripes-smart-components/pull/1538
This PR addresses some issues which cause these failures.
1. StrictMode. Using StrictMode makes components render twice to check for mutation, which makes some components receive test data twice, render twice etc. **For now the fix is only hardcoded. Need to be able to pass `disableStrictMode` flag to karma tests**
2. Overwriting of initial okapi and discovery data in `setupApplication` helper. Some tests require custom okapi data, but `setupApplication` in some cases can overwrite that data which makes those tests fail.
3. ? Still investigating a few failing tests so maybe there's something else that needs to be fixed.
=> STCOR-913 Don't override initial discovery and okapi data in test mocks

CHANGELOG.md, src/components/Root/Root.js, src/components/Root/token-util.test.js, src/loginServices.js, src/loginServices.test.js
Be thorough when evaluating data from localforage to determine whether a session exists by checking for `user.id`, `tenant`, and `isAuthenticated` values rather than accepting the existence of a (possibly empty, or mostly empty) object as proof of life. Without these more thorough checks, a sparsely-populated value may be passed to `validateUser()`, causing it to throw when evaluating `user.id`, and misleadingly dispatching a server-down message.
It is likely that a rogue RTR process is responsible for writing this garbled/sparse session data. We need to research that and resolve that problem too, but at least we have a handle on this from the other end.
Refs [STCOR-907](https://folio-org.atlassian.net/browse/STCOR-907)
=> STCOR-907 cautiously evaluate localforage data

CHANGELOG.md, src/components/Logout/Logout.js, src/components/Logout/Logout.test.js, src/loginServices.js, src/loginServices.test.js
Correctly pass all three required arguments from `<Logout>` to `loginServices::logout()`: gateway URL, redux store, react-query QueryClient. The third was missing, resulting in an NPE during `logout()` that caused flow to skip to the `finally` clause, skipping the code that cleared localforage. Sometimes localforage appears to get cleared anyway, but sometimes not, in which case the session may fail to terminate even when the fixed-length session timer reaches 00:00.
This is one of those "How did this ever work?!? And how did we not notice?!?" situations.
Refs [STCOR-906](https://folio-org.atlassian.net/browse/STCOR-906)
=> STCOR-906 consume react-query QueryClient in <Logout>

CHANGELOG.md, src/loginServices.js, src/loginServices.test.js
Spread together existing session data with the response data from the `_self` endpoint. The latter may contain updated information such as new permissions, but it may also be sparsely populated, e.g. if the user has not selected a default service point but the active service point has been saved to the session.
We take the union of the data, with the `_self` data overwriting matching values. Think of it like a bitwise-or.
Refs [STCOR-912](https://folio-org.atlassian.net/browse/STCOR-912)
=> STCOR-912 spread session, _self data when resuming session

CHANGELOG.md, src/okapiActions.js
`setRtrFlsWarningTimeout()` now sends `rtrFlsWarningTimeout` rather than `rtrFlsTimeout`. This bug was introduced in PR #1511 (onto `keycloak-quesnelia`), which looks like a bad copy-pasta from PR #1510 (onto `keycloak-ramsons`). 
When RTR is correctly configured such that sessions end at a fixed (static) datestamp, this change will have no effect: the original timer will not be canceled when the tokens rotate, but it won't matter because the end-point isn't moving, meaning the original timer will remain accurate.
When RTR is incorrectly configured, however, and a session's end-point is extended on rotation as in a sliding window, this change resolves a bug that would cause the session-timeout banner to display a "Time remaining: 00:00" message without actually ending the session. This …
=> STCOR-930 correctly dispatch rtrFlsWarningTimeout

CHANGELOG.md, src/loginServices.js
This is a follow-up to the botched implementation of [STCOR-816](https://folio-org.atlassian.net/browse/STCOR-816) in PR #1432. The description there is "When restoring an existing session..." but in fact the implementation is "When starting a new session or restoring an existing one...". When starting a new session, however, discovery has not happened yet, so there is no information about what interfaces are present, and the conditional would always return false.
The implementation here corrects the conditional:
1. if we are starting a new session
2. if we are resuming an existing session and the `login-saml` interface is present.
Refs [STCOR-933](https://folio-org.atlassian.net/browse/STCOR-933)
=> STCOR-933 fetch /saml/check when starting a new session

CHANGELOG.md, package.json, yarn.lock
* Update react-intl
* Use stripes-cli to compile translations, allowing us to eliminate the `@formatjs/cli-lib` dep
Refs [STCOR-945](https://folio-org.atlassian.net/browse/STCOR-945)
=> STCOR-945 update react-intl to v7

CHANGELOG.md, src/components/MainNav/MainNav.js, translations/stripes-core/en.json
https://folio-org.atlassian.net/browse/STCOR-931
Here we changed the `aria-label` in `MainNav` component from "Help button" to "Help" regarding screen-reader recommendations.
=> STCOR-931: Change Help icon aria label to just Help in MainNav component

CHANGELOG.md, src/RootWithIntl.js, src/components/Login/LoginCtrl.js, src/components/Root/Root.js, src/components/SSOLanding/useSSOSession.js, src/components/SSOLanding/useSSOSession.test.js, src/components/SessionEventContainer/SessionEventContainer.js, src/components/SessionEventContainer/SessionEventContainer.test.js, src/loginServices.js, src/loginServices.test.js, test/bigtest/network/config.js
https://folio-org.atlassian.net/browse/STCOR-918
https://folio-org.atlassian.net/browse/STCOR-922
Here we removed token-based authentication endpoints. Also, removed `useSecureTokens` logic part.
=> STCOR-918: *BREAKING* remove token-based authentication code

src/components/Login/LoginCtrl.js
- Revert login control changes from https://github.com/folio-org/stripes-core/pull/1589 so localstorage is not used determine Tenant ID and Okapi URL values.
- Previously, login was looking at props passed in, which would default to localstorage. This makes builds unable to run with different tenant IDs or Okapi URL values without manually clearing localstorage in the browser.
=> [STCOR-942] Partial revert which prevents login screen from using localstorage on login screen

CHANGELOG.md, src/hooks/useModuleInfo.js
Whoops, `ky` doesn't want a leading slash when using the `prefixUrl` property and whines about it in the console.
Refs [STCOR-949](https://folio-org.atlassian.net/browse/STCOR-949)
=> STCOR-949 omit leading slash in useModuleInfo's ky path

CHANGELOG.md, src/components/MainNav/MainNav.js
After the switch to hooks, in [stripes-core/src/components/MainNav/MainNav.js at 3570eea0bca50bb0abb0cc0e52db3ae4bc3a792e · folio-org/stripes-core](https://github.com/folio-org/stripes-core/blob/3570eea0bca50bb0abb0cc0e52db3ae4bc3a792e/src/components/MainNav/MainNav.js#L46)  `location` object is not updated, and so `store.subscribe` callback always uses an old value.
When `updateLocation` compares `cleanStateQuery` and `cleanLocationQuery` objects, they are always different because we’re comparing to an old `location`
This caused a bug in Inventory, where when a user opens a shared record - the page reloads and user is taken back to search results. This happens because when a user opens a shared record we append `shared=true` to the url. And because `<MainNav>` doesn't compare to a …
=> STCOR-950 Added `location` to a hook in `<MainNav>` to fix comparing old `location` value

CHANGELOG.md, src/components/Login/LoginCtrl.js
Refs [STCOR-942](https://folio-org.atlassian.net/browse/STCOR-942). 
Previously, changes were partially reverted because the tenant was stored in localStorage after login, and that tenant was then set in the stripes store. The okapi.url is set in the store—not from localStorage or other external sources—but from stripes-config, making it safe to use from the store.
I would like to leave the rest of the functionality as it is for now, but we definitely need to refine our login handling strategies for the cases listed below.
1. single tenant;
2. multi-tenant with multi-select option;
3. multi-tenant, ECS - [Single tenant UX](https://folio-org.atlassian.net/browse/STCOR-946).
=> STCOR-942: get okapi url from the store, not directly from config in LoginCtrl.js

src/components/Root/constants.js
Correct a typo in a comment; the build-time config file is typically named `stripes.config.js`.
=> correctly specify stripes.config.js in config documentation

CHANGELOG.md, src/components/ModuleContainer/ModuleContainer.css
Small but necessary PR. enables changes in https://github.com/folio-org/stripes-components/pull/2438 to work!
=> STCOR-956 printing styles for full result listings.

CHANGELOG.md, package.json, src/constants/index.js, src/constants/settings.js, src/hooks/useQueryLimit.js, src/hooks/useQueryLimit.test.js, src/hooks/useTenantPreferences.js, src/hooks/useTenantPreferences.test.js
The `useQueryLimit()` hook returns a number which can be used in a query's limit clause when retrieving entries from a lookup table and you want _all_ the records.
```
const limit = useQueryLimit();
```
`useQueryLimit()` first looks for a tenant-level mod-settings entry, then for `stripes.config.maxUnpagedResourceCount` from `stripes.config.js`, and then finally gives up and returns the value of the constant `MAX_UNPAGED_RESOURCE_COUNT`, currently set to 2000.
`userTenantPreferences` was shamelessly copied from `usePreferences`; both should be rewritten to share common code. Probably we want `usePreferences` to be the top-level, which looks up a value in user-settings, then tenant-settings.
Refs [STCOR-957](https://folio-org.atlassian.net/browse/STCOR-957)
=> STCOR-957 provide useQueryLimit hook

CHANGELOG.md, src/components/MainNav/AppOrderProvider.js, src/components/MainNav/AppOrderProvider.test.js
Currently, apps order defaults to the order from stripes-config. This is not-as-nice for users when they reset defaults and expect to have a predictable time finding their app's name in the list so that they can move it to it's preferred position.
This PR sorts them by localized `displayName` to save their eyes.
=> STCOR-964: Sort app navigation by localized displayName by default.

src/components/MainNav/AppOrderProvider.js, src/components/MainNav/AppOrderProvider.test.js
Use `localeCompare` to perform case-insensitive sort (if that's what a locale expects) of application names, instead of using lodash's `sortBy` which sorts strings by their unicode code points.
This will give us lists like "Data Import, eHoldings, Finance" rather than "Data Import, Finance, eHoldings".
Refs [STCOR-964](https://folio-org.atlassian.net/browse/STCOR-964)
=> STCOR-964 (again) compare app-names with localeCompare

CHANGELOG.md, src/components/Root/constants.js, src/components/Root/token-util.test.js
Change the default idle session timeout to `4h` from the arbitrary, insufficient, and inconvenient `1h` value that was set in PR #1463.
Refs [STCOR-962](https://folio-org.atlassian.net/browse/STCOR-962)
=> STCOR-962 set default idle session timeout to 4h

CHANGELOG.md, src/components/SessionEventContainer/FixedLengthSessionWarning.js, src/components/SessionEventContainer/FixedLengthSessionWarning.test.js, src/components/SessionEventContainer/SessionEventContainer.js, src/components/SessionEventContainer/SessionEventContainer.test.js
[STCOR-884](https://folio-org.atlassian.net/browse/STCOR-884) - IST modal with long TTL shows even when FLST warning with short TTL is already displayed
The issue was that the `fixedLengthSessionTimeout` timer had a life of its own, and we didn’t have access to it in `SessionEventContainer` to determine whether we could trigger the keepWorking modal.
Just lift the fls timer state up and check if it is less than `idleModalTTL`. If so, don’t show the keepWorking modal; otherwise, show it.
=> STCOR-884: IST modal with long TTL shows even when FLST warning with short TTL is already displayed

CHANGELOG.md, src/useOkapiKy.js, src/useOkapiKy.test.js
Refs [STCOR-967](https://folio-org.atlassian.net/browse/STCOR-967).
=> STCOR-967: allow customizing request timeout in useOkapiKy

CHANGELOG.md, src/components/SSOLogin/SSOLogin.js, src/loginServices.js, src/loginServices.test.js
`validateUser()` is expected to return session data on success or null on failure. Previously, it wrongly returned an error message on failure, causing its calling function (`checkOkapiSession()`) to act as though an existing session were being restored (which of course is not the case given that session restoration had just failed...) and skip the SSO-check that happens only once, when stripes is initializing.
Related, restore the CSS for the "Log in via SSO" button so it remains prominently visible when it is present.
If cookies are revoked for any reason -- maybe a user deletes them, maybe the backend revokes them -- then the UI will be in a state where it has valid session data in redux and in localstorage, but it no longer has the corresponding cookies. This is an awkward state for …
=> STCOR-970 validateUser should return null on failure

CHANGELOG.md, src/App.js, src/components/AuthnLogin/AuthnLogin.js, src/components/Login/LoginCtrl.js, src/components/OIDCLanding.js, src/components/OIDCLanding.test.js, src/components/PreLoginLanding/PreLoginLanding.js, src/loginServices.js, src/loginServices.test.js
I'm going to use @zburke explanation on this because I couldn't have explained the issue better myself
> In an ECS setup, there are three required steps to authentication; keycloak is step-2, and skipping step-1 causes step-3 to fail:
> 1. choose a tenant and save it to local-storage, then redirect to keycloak
> 2. authenticate in keycloak, then redirect to stripes with an OTP in the URL
> 3. make an API request to trade the OTP for AT/RT cookies, /authn/token?otp=${OTP from step-2} with the X-Okapi-Tenant header set to the tenant from step-1
>
> Bookmarking the authentication URL in step-2 means the tenant is never stored to local-storage, thus causing step-3 to fail. 
IIRC, we can pass values to Keycloak in the URL and it will include them along with the OTP when it redirects back to …
=> STCOR-972 passing tenant as a URL param to keycloak redirect_uri

CHANGELOG.md, src/components/Root/FFetch-activeWindow.test.js, src/components/Root/FFetch.js, src/components/Root/FFetch.test.js, src/components/Root/Root.js, src/components/Root/constants.js, src/components/Root/token-util.js
Refs [STCOR-978](https://folio-org.atlassian.net/browse/STCOR-978) (Sunflower backport: [STCOR-84](https://folio-org.atlassian.net/browse/STCOR-984))
This PR resolves an issue where users experienced an abrupt logout due
to failures in token rotation across multiple tabs of usage - one bad
apple among all of their open tabs spoiled it for the rest.
Only a single, active tab is able to actually rotate. The rest just
schedule their next rotation and *don't* actually rotate. This will be
the last tab that the user interacted with and will persist through
usage of other applications.
With this approach, each new tab (single `FFetch` instance) creates a
unique id for the tab and sets up a `focusin` handler so that when a new
tab is focused, it will broadcast the focused tab's unique id so that …
=> STCOR-978 Use BroadcastChannel to isolate token to last-focused window.

CHANGELOG.md, src/components/OIDCLanding.js, src/components/OIDCLanding.test.js, src/components/OIDCLandingError.js, src/components/OIDCLandingError.test.js, src/loginServices.js, src/loginServices.test.js
Effects run twice in `<StrictMode>`, but OTP must only happen once; make it so.
This PR changes the way OIDCLanding handles OTP exchange, moving it from an effect (which will run x2 in development when `<StrictMode>` is turned on, which of course we want it to be), [outside the component lifecycle](https://react.dev/learn/synchronizing-with-effects#not-an-effect-initializing-the-application) so it only runs once no matter how many times the component is [mounted/unmounted/remounted in development-mode](https://react.dev/learn/synchronizing-with-effects#how-to-handle-the-effect-firing-twice-in-development).
It may bother you that there is both an event-handler and an effect to handle the same thing, and that's fair. The problem is, there is a race condition between the OTP-exchange request …
=> STCOR-986 handle OTP in StrictMode

CHANGELOG.md, src/RootWithIntl.js
Provide `attach` to `<HotKeys>` to avoid it falling back on its default using the deprecated `findDOMNode`.
Refs [STCOR-996](https://folio-org.atlassian.net/browse/STCOR-996)
=> STCOR-996 provide `attach` to HotKeys
