- devServer.js
Not sure if this is the right approach, please feel free to correct or refine.
> Add support for environment variables to devServer.js (STRIPES-124)

- src/components/Login/LoginCtrl.js
Added the Content-Type appliaction/json as the new version of mod-auth did not like text/plain
> Added content-type appliaction/json header to login

- src/components/MainNav/MainNav.js
Cannot log into UI. It seems the line resets UI during the log in process.
> Remove a line that disrupts the log in

- src/configureStore.js
- src/connectErrorEpic.js
...is adequately handled by the actions in STCON-20 + redux-observable.
> Show alert on stripes-connect errors, demonstrates STCON-25

- src/components/Front.js
May I suggest to change the welcome message from "Welcome to whatever this is!" to "Welcome, the Future Of Libraries Is OPEN!"? Thanks.
> Change the welcome message

- src/Root.js
- src/components/Login/LoginCtrl.js
- src/components/SSOLanding.js
- src/loginServices.js
The PR should handle login via SSO when both `ssoToken` and `userId` are provided via query params or cookies.
> Handle login via SSO. Fixes STCOR-43

- doc/dev-guide.md
- package.json
- src/configureStore.js
- src/index.js
Adding back the redux logger to the store and updating the read me about the redux dev tools extension.
> Adding back the redux-logger

- src/components/ModuleContainer/ModuleContainer.css
> Hide focus outline for moduleContainer

- index.html
Resolves https://issues.folio.org/browse/UIEH-24
> Explicitly declare UTF-8 character encoding

- Jenkinsfile
- package.json
- src/Stripes.js
- src/components/MainNav/MainNav.js
This was the same approach taken for `stripes-components` - I assume it applies here too.
> Run lint on PRs

- examples/.eslintrc
- examples/trivial-okapi/TenantEdit.js
- examples/trivial-okapi/TenantList.js
- examples/trivial-okapi/index.js
- package.json
- stripes.js
- util/package2md.js
- util/perm-tree.js
- util/test-regexp.js
- webpack.config.base.js
- webpack.config.cli.dev.js
- webpack.config.cli.js
- webpack.config.cli.prod.js
- webpack.config.prod.js
- webpack/stripes-config-plugin.js
Gets `stripes-core` to 100% lint coverage.
I'm a little hesitant to merge this without any `stripes-core` test coverage, but I've pretty extensively tested these changes against https://github.com/thefrontside/ui-eholdings.
> Lint entire repo

- util/pull-stripes
* stripes-loader
* stripes-smart-components
* ui-instances
* ui-requests
> Add support for several other git repos to pull-stripes

- doc/release-procedure.md
Add notes on handling breaking changes to release documentation
Related to STCOR-89
> STCOR-89 pre-release

- CHANGELOG.md
- doc/dev-guide.md
- src/Stripes.js
Also, update documentation and change-log.
Fixes STCOR-98.
> Extend hasPermission to accept a list of permissions.

- webpack/stripes-config-plugin.js
This enables serving an app module from within a cli generated platform without linking
> Add support for resolving module aliases to stripes config plugin

- CHANGELOG.md
- src/components/MainNav/MainNav.js
> Setting a special query parameter to null removes it from the URL

- webpack.config.cli.dev.js
Did not get caught by Jenkins as part of this PR: https://github.com/folio-org/stripes-core/pull/99
> Fix eslint error in webpack config

- CHANGELOG.md
- doc/adding-permissions.md
> Add new document, doc/adding-permissions.md

- doc/adding-permissions.md
> One-character typo

- CHANGELOG.md
- doc/adding-permissions.md
> FOLIO-398 doc tweaks 1

- CHANGELOG.md
- doc/dev-guide.md
> Write documentation for URL navigation by anointed resource

- CHANGELOG.md
- src/components/Login/Login.js
- src/components/Login/LoginCtrl.js
- src/loginServices.js
- src/okapiActions.js
- src/okapiReducer.js
> Report login errors (other than u/p mismatch) to user

- src/components/About.js
- src/components/AboutEnabledModules.js
Fixed styling by adding <List>-component for lists and <Headline> for all headlines.
> Updated about page

- CHANGELOG.md
- webpack.config.base.js
> Support loading SVG images via WebPack

- src/components/MainNav/MainNav.js
resolves [UIU-357](https://issues.folio.org/browse/UIU-357)
> subscribe to query when module location changes

- CHANGELOG.md
- src/components/MainNav/MainNav.js
> Push new URLs onto history instead of replacing old one

- CHANGELOG.md
- src/components/MainNav/MyProfile/MyProfile.js
- translations/da.json
- translations/de.json
- translations/en.json
- translations/fr.json
Also provides translations in our four main languages.
Fixes STCOR-130.
> Add "Home" link to user menu

- CHANGELOG.md
- doc/dev-guide.md
- src/components/MainNav/MyProfile/MyProfile.js
> Show "Home" link only when "showHomeLink" developer option is on

- CHANGELOG.md
- README.md
- doc/app-metadata.md
Fixes STCOR-117 and STCOR-129.
> Add new document, "Stripes application metadata bundles"

- doc/app-metadata.md
- doc/branding.md
- doc/release-procedure.md
> FOLIO-398 doc tweaks 2

- package.json
Accidentally closed https://github.com/folio-org/stripes-core/pull/159 while trying to trigger a new Jenkins build; this replaces it.
> Upgrade localforage

- package.json
https://github.com/webpack-contrib/uglifyjs-webpack-plugin/issues/217
> Lock uglifyjs-webpack-plugin version due to error in latest

- webpack.config.base.js
- webpack.config.cli.prod.js
This enables the plugin for both dev and prod builds
> Move duplicate check to base config

- CHANGELOG.md
- util/pull-stripes
> Add `-c` (clone git repositories) mode to `pull-stripes`

- util/pull-stripes
How has it been missing all this time?!
This is not really part of STCOR-135, but I'm sick of making a new
branch every time I fix a typo, so I'm re-using its branch. No-one can
stop me! Bwahahaha!
> Add ui-search to pull-stripes

- doc/new-development-setup.md
> Add "troubleshooting" section to new-stripes-setup doc

- src/components/MainNav/MainNav.js
This is the correct implementation/fix of this issue: https://issues.folio.org/browse/STRIPES-498
> Removed href from the selected NavButton

- CHANGELOG.md
- doc/release-procedure.md
- package.json
> Release v2.9.0

- CHANGELOG.md
- doc/new-development-setup.md
- util/pull-stripes
> Update docs for `stripes-cli`-based workflow

- CHANGELOG.md
- doc/new-development-setup.md
> FOLIO-398 doc tweaks 4

- CHANGELOG.md
- README.md
- doc/depending-on-unreleased-features.md
> New document, "Depending on unreleased features"

- doc/depending-on-unreleased-features.md
> FOLIO-398 doc tweaks 5

- CHANGELOG.md
- doc/new-development-setup.md
- util/configure
Refs [STCLI-11](https://issues.folio.org/browse/STCLI-11).
> stripescli is now stripes. Refs STCLI-11

- CHANGELOG.md
- doc/new-development-setup.md
Fixes [STCOR-154](https://issues.folio.org/browse/STCOR-154).
> add notes about stripes-cli install troubleshooting. Fixes STCOR-154

- CHANGELOG.md
- examples/trivial-okapi/TenantList.js
- src/components/Notification/ToastNotification.js
- src/components/Root/Root.js
Fixes [STCOR-157](https://issues.folio.org/browse/STCOR-157)
> Lint. Fixes STCOR-157

- CHANGELOG.md
- util/pull-stripes
Refs [UIIN-18](https://issues.folio.org/browse/UIIN-18)
> deprecating ui-items. Refs UIIN-18

- util/pull-stripes
When there's a bunch of output from this script it's sometimes hard to see the "not doing anything" warnings at a glance. Hopefully this helps others like it's helped me. 😄
> Add emoji to pull-stripes to more easily see warnings

- src/components/MainNav/MainNav.js
- src/components/Root/Root.js
- src/locationActions.js
- src/locationService.js
This is still a WIP so please don't merge it.
> WIP: An attempt to cleanup query resource. Part of STCOR-134

- CHANGELOG.md
- doc/new-development-setup.md
Fixes [STCOR-160](https://issues.folio.org/browse/STCOR-160).
> add vagrant doc to getting-started doc. Fixes STCOR-160

- webpack/module-paths.js
Options are then passed to require.resolve via tryResolve()
When successful, tryResolve returns the resolved path rather true.  This will continue to satisfy existing truthy checks.
> STCOR-163 Define tryPaths as array of objects to support require.resolve options

- webpack/module-paths.js
Previous fix for STCOR-163 overlooked these conditions due to lack of test!
Fixes STCLI-32
> Update items in the tryPaths array to be the same structure

- package.json
After updates to platforms and CI are complete, "stripes" will be removed.  STCOR-153
> Add "stripescore" as an alias for "stripes"

- CHANGELOG.md
- package.json
This completes the STCOR-153 rename of "stripes" to "stripescore".
> Remove "stripes" from bin

- CHANGELOG.md
- src/components/Root/Root.js
> Guard against absence of icons and other metadata

- CHANGELOG.md
- package.json
- util/pull-stripes
add dash-ell support to pull-stripes instead of always iterating over a hard-coded list of modules. Fixes [STCOR-166](https://issues.folio.org/browse/STCOR-166).
> add dash-ell support to pull-stripes. STCOR-166. 

- src/components/MainNav/MainNav.js
- src/components/ModuleContainer/ModuleContainer.js
Top navigation bar to use <header>, and ModuleContainer to <main>, add heading to navigation as beseeched by the <nav> sectioning tag.
> STCOM-215 follow-up: Semantic elements

- CHANGELOG.md
- test/webpack/stripes-module-parser.spec.js
- webpack/stripes-module-parser.js
> Do not emit "no icons defined in stripes.icons" warning for non-app modules

- doc/new-development-setup.md
> Push headings of new section down a level

- doc/quick-start.md
Help point new developers to Stripes CLI and more current builds using npm-folioci
> Update quick start

- CHANGELOG.md
- package.json
- webpack/stripes-translations-plugin.js
Fixes [STCOR-178](https://issues.folio.org/browse/STCOR-178)
> Stcor 178 library translation prefix

- package.json
- src/RootWithIntl.js
- src/components/Root/Root.js
- src/loginServices.js
- src/okapiActions.js
- src/okapiReducer.js
- util/dateUtil.js
> Stcor time zone

- examples/trivial-okapi/TenantList.js
- src/loginServices.js
- webpack.config.base.js
"Foolish goblins wrote ESLint."
-- Ralph, Waldo, Emerson, Lake, and Palmer
> lint: use quotes consistently

- CHANGELOG.md
- package.json
- webpack/stripes-translations-plugin.js
Fixes [STCOR-183](https://issues.folio.org/browse/STCOR-183)
> don't error when searching for translations in stripes- libraries. Fixes STCOR-183

- CHANGELOG.md
- webpack.config.base.js
[https://issues.folio.org/browse/STCOR-184](https://issues.folio.org/browse/STCOR-184)
> Add support for audio files. Fixes STCOR-184

- CHANGELOG.md
- util/configure
> Update "configure" script to use a Yarn workspace

- CHANGELOG.md
- doc/new-development-setup.md
> Fix typos in workspace-creation section

- translations/en.json
https://issues.folio.org/browse/STSMACOM-76
> add translation strings

- CHANGELOG.md
- doc/i18n.md
Fixes [STCOR-182](https://issues.folio.org/browse/STCOR-182)
> i18n doc. Fixes STCOR-182

- CHANGELOG.md
- package.json
> Upgrade react-apollo dependency to v2.1.3

- CHANGELOG.md
- package.json
- util/configure
Fixes [STCOR-193](https://issues.folio.org/browse/STCOR-193)
> set folio's NPM repository before using it. Fixes STCOR-193

- doc/new-development-setup.md
- doc/quick-start.md
Update quick start and dev setup docs to include reference to workspace command available in CLI v.1.1.0
> STCLI-41 workspace command

- CHANGELOG.md
- stripes.js
- webpack/build.js
When not specified, the default is to minify.  STCOR-197
> Add --no-minify option to disable minification

- CHANGELOG.md
- package.json
... and thereby of leveldown. Fixes STCOR-210.
> Upgrade required version of hard-source-webpack-plugin

- CHANGELOG.md
- src/components/Root/Root.js
- src/components/SystemSkeleton/SystemSkeleton.css
- src/components/SystemSkeleton/SystemSkeleton.js
- src/components/SystemSkeleton/index.js
We will be adding skeleton loading to various parts of the system to improve perceived performance when fetching data. 
This PR adds a general system skeleton that will be rendered until the app is ready to be shown.
This replaces the "Loading translations..."-text.
> Adding system skeleton loading

- webpack/stripes-translations-plugin.js
https://issues.folio.org/browse/STRIPES-524
> STRIPES-524: add stripes-form to included stripes-* translations

- package.json
- test/webpack/stripes-branding-plugin.spec.js
- test/webpack/stripes-config-plugin.spec.js
- test/webpack/stripes-translations-plugin.spec.js
- test/webpack/stripes-webpack-plugin.spec.js
- webpack.config.base.js
- webpack/build.js
- webpack/serve.js
- webpack/stripes-branding-plugin.js
- webpack/stripes-config-plugin.js
- webpack/stripes-translations-plugin.js
- webpack/stripes-webpack-plugin.js
This PR serves as a reference to the stripes webpack plugin-specific changes described within STCOR-217.  The complete work towards Weback 4 will be captured under STCOR-175.
> STCOR-217 plugins

- CHANGELOG.md
- doc/release-procedure.md
Update release procedure to guard against publishing with unreleased dependencies
> STCOR-225 update release procedure

- src/discoverServices.js
See [FOLIO-1059](https://issues.folio.org/browse/FOLIO-1059) for details
> send x-okapi-tenant: supertenant when getting version and enabled mods

- CHANGELOG.md
- doc/dev-guide.md
> Fix typo in doc/dev-guide.md

- examples/trivial-okapi/TenantList.js
- package.json
- src/components/About/AboutEnabledModules.js
- src/components/Login/LoginCtrl.js
- src/components/MainNav/MainNav.js
- src/components/MainNav/MyProfile/MyProfile.js
- src/components/MainNav/Notifications/NotificationsMenu.js
Code changes reflect new styles from the `react/sort-comp` rule. 
With https://github.com/folio-org/eslint-config-stripes/pull/30, future rule changes should be less surprising.
> Use eslint-config-stripes 2.0

- src/RootWithIntl.js
- src/StripesContext.js
- src/moduleRoutes.js
https://issues.folio.org/browse/STCOR-208
Add StripesProvider
> STCOR-208: new context api

- CHANGELOG.md
- package.json
Forgot to update it in the last PR
> Updated version and changelog

- src/loginServices.js
Just adding on the ID and username to the `user` object we store in Redux. We need this to track what user is doing actions like cancelling requests in UIREQ-67.
> Store current user ID in Redux & Stripes Context

- src/locationActions.js
I initially wanted to clean it up a bit but it looks like this is causing issues in SearchAndSort. So just reverting this for now.
> Revert payload change in query resource action. Part of STCOR-231

- util/pull-stripes
https://issues.folio.org/browse/FOLIO-1302
> Add ui-tags to stripes list. Part of FOLIO-1302

- src/RootWithIntl.js
- src/components/Root/Root.js
- src/components/Settings/Settings.js
- src/moduleRoutes.js
This reverts commit 71a1a6308f5663b20909ec6d855de7c9f1037aa6.
> Revert "pass redux args to stripes-connect"

- doc/dev-guide.md
- src/components/MainNav/MyProfile/MyProfile.js
- src/userDropdownLinksService.js
* modified user profile pop-up to include "Change Password" item
* added function to check user credentials exists in local storage
> UIU-563 - Access Change my password from Folio Top Toolbar

- util/pull-stripes
https://issues.folio.org/browse/STRIPES-541
> Add My Profile to pull script. Part of STRIPES-541

- CHANGELOG.md
- src/Stripes.js
> Add ALL properties to stripesShape

- CHANGELOG.md
- src/components/MainNav/MyProfile/MyProfile.css
- src/components/MainNav/MyProfile/MyProfile.js
- src/loginServices.js
- src/okapiActions.js
- src/okapiReducer.js
- translations/stripes-core/en.json
https://issues.folio.org/browse/STCOR-235
Guys this is kind of a continuation of work @doytch did in `ui-users` in https://github.com/folio-org/ui-users/pull/451
I'm currently adding the preferred service point to `currentUser` but perhaps this should be available directly from `stripes`. What do you think?
> Select service point preference when logging in. Fixes STCOR-235

- CHANGELOG.md
- doc/dev-guide.md
> In the Developer's Guide, document the pattern for specifying limits

- src/RootWithIntl.js
- src/components/Handlers/Handlers.js
- src/components/Handlers/index.js
- src/components/ModuleTranslator/ModuleTranslator.js
- src/components/Modules/withModule.js
- src/events.js
@MikeTaylor this is a first piece which executes handler modules after login. Please let me know what you think. This should be close to what we were discussing (I hope) and what you have outlined in the email. 
I'm also in the process of creating a first handler module called `ui-servicepoints` It would be nice to get this merged so we can move forward with the service points work.
> Introduce handler modules. Part of STCOR-240

- CHANGELOG.md
- package.json
- src/components/MainNav/ProfileDropdown/ProfileDropdown.js
> Support link-checking functions that are actual functions, as well as names

- src/components/MainNav/ProfileDropdown/ProfileDropdown.js
@MikeTaylor this approach solves the issue with the nav bar being open (when we open a SP modal). It also aligns with what you had in mind yesterday and actually cleans up the handler component implementation. 
Here are the changes for the handler:
https://github.com/folio-org/ui-servicepoints/pull/2/files
> Refactor handler component creation. Part of STCOR-237

- CHANGELOG.md
- doc/dev-guide.md
Also, some restructuring.
Fixes STCOR-246.
> Update the Developer's Guide with new sections on handlers and links

- CHANGELOG.md
- doc/settings-and-preferences.md
Discusses the distinction and outlining implementation options.
Addresses the concerns of UIP-1.
Now to wait half an hour while Jenkins runs regression-tests on my addition of a human-readable document that doesn't change the code in any way. _sigh_.
> Add new document, "Settings and Preferences"

- src/loginServices.js
https://issues.folio.org/browse/STCOR-237
> Select SP automatically when no SP present and only one available. Part of STCOR-237

- doc/release-procedure.md
> More rigorous check for unreleased dependencies

- doc/release-procedure.md
Update the release procedure to include information on building and releasing artifacts via FOLIO Jenkins.
> Update release procedure

- doc/dev-guide.md
Updated part about events being strings instead of numeric values.
> Update handler doc

- CHANGELOG.md
- package.json
- src/discoverServices.js
- test/core/isVersionCompatible.js
Available from v2.11.2.
Fixes STCOR-249.
> `isVersionCompatible` accepts a space-separated list of wanted versions

- src/components/Front.js
https://issues.folio.org/browse/STCOM-331
Overlooked in https://github.com/folio-org/stripes-core/pull/403
> STCOM-331 Use local Pluggable

- examples/trivial-okapi/TenantEdit.js
- examples/trivial-okapi/TenantList.js
- package.json
- src/components/About/About.js
- src/components/About/AboutEnabledModules.js
- src/components/HandlerManager/HandlerManager.js
- src/components/Login/index.js
- src/components/MainNav/NavGroup/index.js
- src/components/MainNav/Notifications/NotificationsMenu.js
- src/components/MainNav/ProfileDropdown/ProfileDropdown.js
- src/components/Modules/withModule.js
- src/components/Modules/withModules.js
- src/components/Notification/Toast.js
- src/components/Notification/ToastNotification.js
- src/components/Notification/index.js
- src/components/SSOLanding.js
- src/configureEpics.js
- src/enhanceReducer.js
- src/initialReducers.js
- src/loginServices.js
- src/moduleRoutes.js
- util/dateUtil.js
- webpack/stripes-config-plugin.js
Includes upgrades for `eslint` and `babel-eslint`.
> Use eslint-config-stripes 3.2

- doc/component-example.md
- src/AddContext.js
- src/App.js
- src/ModulesContext.js
- src/Pluggable.js
- src/components/About/About.js
- src/components/About/AboutEnabledModules.js
- src/components/Front.js
- src/components/Login/Login.js
- src/components/Login/LoginCtrl.js
- src/components/MainNav/Breadcrumbs/Breadcrumbs.js
- src/components/MainNav/MainNav.js
- src/components/MainNav/NavDropdownMenu/NavDropdownMenu.js
- src/components/MainNav/NavGroup/NavGroup.js
- src/components/Notification/Toast.js
- src/components/Notification/ToastNotification.js
- src/components/Root/Root.js
- src/components/SSOLanding.js
- src/components/SSORedirect.js
- src/gatherActions.js
- src/loginServices.js
- stripes.js
- test/bigtest/network/config.js
- webpack/build.js
- webpack/serve.js
- webpack/stripes-module-parser.js
Most of these were just cruft from rules that have since been turned off.
Now every `eslint-disable-line` specifically states which rules are being ignored.
> Reduce eslint disables

- CHANGELOG.md
- src/components/MainNav/CurrentApp/CurrentApp.js
- src/components/MainNav/MainNav.js
Resolves https://issues.folio.org/browse/STCOR-255
> STCOR-255 Make current app clickable

- CHANGELOG.md
- package.json
* Add `react-hot-loader` to development environment
* Remove notifications, STCOR-257
* Use new type stack
* Make current app clickable, STCOR-255
* Create `setupStripesCore()` test helper
> Release v2.14.0

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/STRIPES-561
> STRIPES-561 Release v2.15.0

- CHANGELOG.md
- package.json
* Remove HMR router hack
* Fix currentUser error in tests
> Release v2.15.1

- src/components/About/About.css
- src/components/MainNav/AppList/AppList.css
Missed a couple of these.
https://github.com/folio-org/stripes-components/pull/629
> Update CSS vars to kebab-case

- CHANGELOG.md
- package.json
* Prevent mirage from auto-loading fixtures
* Update CSS vars to kebab-case
> Release v2.15.2

- CHANGELOG.md
- package.json
- src/components/About/About.css
- src/components/MainNav/AppList/AppList.css
- src/components/MainNav/MainNav.css
- src/components/MainNav/NavDivider/NavDivider.css
- src/components/MainNav/NavDropdownMenu/NavDropdownMenu.css
- src/components/MainNav/NavGroup/NavGroup.css
- src/components/SystemSkeleton/SystemSkeleton.css
Related to https://issues.folio.org/browse/FOLIO-1547
Includes `v2.15.3` release.
> Fix CSS variable naming for breakpoints

- util/pull-stripes
Updated the `pull-stripes` script to include `ui-erm`
> Added ui-erm to pull-stripes

- CHANGELOG.md
- package.json
* Increase login form input font size
* Slim down skeleton loader
* Update CSS for hidden navigation headline
* Lean on react-intl FormattedTime for datetime construction
> Release v2.15.4

- CHANGELOG.md
- src/components/MainNav/NavButton/NavButton.js
Issue: https://issues.folio.org/browse/STCOR-274
> Set alt="" on app icons in MainNav

- CHANGELOG.md
- src/components/MainNav/ProfileDropdown/ProfileDropdown.css
Issue: https://issues.folio.org/browse/STCOM-377
> Updated color of profile dropdown to fix part of STCOM-377.

- src/components/About/About.js
- src/components/Login/Login.js
- src/components/Login/LoginCtrl.js
- src/components/TitledRoute/TitledRoute.js
Sequel to https://github.com/folio-org/stripes-core/pull/461.
Upcoming PR will completely remove `stripes.intl`.
> Remove uses of stripes.intl

- src/components/MainNav/MainNav.js
- src/components/MainNav/ProfileDropdown/ProfileDropdown.js
- src/components/Notification/ToastNotification.js
Resolves https://issues.folio.org/browse/STCOR-259
> STCOR-259 Remove title attributes

- src/components/ForgotPassword/ForgotPasswordForm.css
- src/components/ForgotPassword/ForgotPasswordForm.js
- src/components/ForgotUserName/ForgotUserNameForm.css
- src/components/ForgotUserName/ForgotUserNameForm.js
Stylesheets added to both of Forgot Form components to make them more independent and extendable. Import paths fixed.
> Styles added to each forgot form component

- test/bigtest/interactors/StatusPage.js
Causes test suite to fail in Safari: https://circleci.com/gh/frontside-folio/stripes-core/1028
> Fix incomplete interactor selector

- package.json
- src/components/MainNav/AppList/AppList.js
- src/components/Notification/ToastNotification.js
See https://github.com/folio-org/stripes-components/pull/743
> Update deprecated icon names

- CHANGELOG.md
- package.json
* Keep all stripes attributes up to date after login. Refs STCOR-273, STRIPES-578, STCOR-283.
* Move `<IfInterface>` from `stripes-components`, STCOM-357
* Move `<IfPermission>` from `stripes-components`, STCOM-357
> Release 2.17.0

- src/RootWithIntl.js
- src/components/CreateResetPasswordLoader/CreateResetPasswordLoaderCtrl.js
- test/bigtest/network/scenarios/changePasswordValidateClientError.js
- test/bigtest/tests/createResetPassword-test.js
<li>To update the BE contracts</li>
<h1>Approach</h1>
<li>To change routes to match the BE-generated link</li>
<li>To add a scenario when token of improper type was passed</li>
> STCOR-284: BE contracts updated

- src/components/CreateResetPassword/CreateResetPasswordControl.js
- src/components/CreateResetPasswordLoader/CreateResetPasswordLoaderCtrl.js
- src/constants/defaultErrors/defaultErrors.js
- src/constants/defaultErrors/index.js
- src/constants/index.js
- src/processBadResponse.js
- test/bigtest/network/scenarios/changePasswordClientError.js
- test/bigtest/tests/createResetPassword-test.js
<li>To replace token used for /bl-users/password-reset/reset endpoint with the one received from  
/bl-users/password-reset/validate</li>
<h1>Approach</h1>
<li>To form an appropriate server request</li>
<li>To write additional tests</li>
<li>Clean up code</li>
> Token replaced during change password authentication

- translations/stripes-core/en.json
<li>To add a link.used translation</li>
> link.used translation added

- translations/stripes-core/pt_PT.json
> Update translation strings as of 20181228T143605

- package.json
<li>To add the required permissions for reset password flow</li>
> Validation rules and reset password permissions added

- translations/stripes-core/en_SE.json
> Update translation strings as of 20190110T173959

- translations/stripes-core/ar.json
- translations/stripes-core/ca.json
- translations/stripes-core/da.json
- translations/stripes-core/de.json
- translations/stripes-core/en_GB.json
- translations/stripes-core/en_SE.json
- translations/stripes-core/en_US.json
- translations/stripes-core/es.json
- translations/stripes-core/es_ES.json
- translations/stripes-core/fr.json
- translations/stripes-core/fr_FR.json
- translations/stripes-core/hu.json
- translations/stripes-core/it_IT.json
- translations/stripes-core/pt_BR.json
- translations/stripes-core/pt_PT.json
- translations/stripes-core/zh_CN.json
> Update translation strings as of 20190113T223639

- src/components/CreateResetPassword/CreateResetPassword.css
- src/components/Front.css
- src/components/Login/Login.css
In this PR I updated the remaining hardcoded font-sizes to use variables.
**Ticket:** https://issues.folio.org/browse/STCOR-302
> STCOR-302: Replaced hardcoded font sizes with variables

- CHANGELOG.md
- package.json
- webpack/module-paths.js
https://issues.folio.org/browse/STCOR-320
> Add workspace path to stripes alias resolution. Part of STCOR-320

- CHANGELOG.md
* Add workspace path to stripes alias resolution. Part of STCOR-320.
> Release v3.0.2

- src/components/Settings/Settings.js
- translations/stripes-core/en.json
This PR is  the fix for https://issues.folio.org/browse/STCOR-313.
Added hardcoded strings in settings to translations.
> STCOR-313: Fixed settings translations

- translations/stripes-core/it_IT.json
- translations/stripes-core/pt_PT.json
> Update translation strings as of 20190213T024543

- translations/stripes-core/en.json
Refs [STSMACOM-175](https://issues.folio.org/browse/STSMACOM-175)
> add missing translation pair

- translations/stripes-core/ar.json
- translations/stripes-core/ca.json
- translations/stripes-core/da.json
- translations/stripes-core/de.json
- translations/stripes-core/en_GB.json
- translations/stripes-core/en_SE.json
- translations/stripes-core/en_US.json
- translations/stripes-core/es.json
- translations/stripes-core/es_ES.json
- translations/stripes-core/fr.json
- translations/stripes-core/fr_FR.json
- translations/stripes-core/hu.json
- translations/stripes-core/it_IT.json
- translations/stripes-core/pt_BR.json
- translations/stripes-core/pt_PT.json
- translations/stripes-core/zh_CN.json
> Update translation strings as of 20190312T123958

- src/components/MainNav/CurrentApp/AppContextDropdown.js
So says my UX conscience, played in this episode by Kimie Kester.
> "Move caret to end of context dropdown"

- CHANGELOG.md
- webpack.config.base.js
- Re-enabling lodash feature sets since impact to UI modules is uncertain in present and future development.
- Updated CHANGELOG.
Before:
After:
> Stcor 285 apply lodash plugins to build

- translations/stripes-core/ar.json
- translations/stripes-core/ca.json
- translations/stripes-core/da.json
- translations/stripes-core/de.json
- translations/stripes-core/en_GB.json
- translations/stripes-core/en_SE.json
- translations/stripes-core/en_US.json
- translations/stripes-core/es.json
- translations/stripes-core/es_ES.json
- translations/stripes-core/fr.json
- translations/stripes-core/fr_FR.json
- translations/stripes-core/hu.json
- translations/stripes-core/it_IT.json
- translations/stripes-core/pt_BR.json
- translations/stripes-core/pt_PT.json
- translations/stripes-core/zh_CN.json
> Update translation strings as of 20190415T231934

- translations/stripes-core/es_ES.json
> Update translation strings as of 20190429T154045

- translations/stripes-core/zh_CN.json
> Update translation strings as of 20190517T183537

- translations/stripes-core/ar.json
> Update translation strings as of 20190520T224011

- translations/stripes-core/ar.json
- translations/stripes-core/ca.json
- translations/stripes-core/da.json
- translations/stripes-core/de.json
- translations/stripes-core/en_GB.json
- translations/stripes-core/en_SE.json
- translations/stripes-core/en_US.json
- translations/stripes-core/es.json
- translations/stripes-core/es_419.json
- translations/stripes-core/es_ES.json
- translations/stripes-core/fr.json
- translations/stripes-core/fr_FR.json
- translations/stripes-core/hu.json
- translations/stripes-core/it_IT.json
- translations/stripes-core/pt_BR.json
- translations/stripes-core/pt_PT.json
- translations/stripes-core/zh_CN.json
> Update translation strings as of 20190729T163855

- translations/stripes-core/ar.json
- translations/stripes-core/ca.json
- translations/stripes-core/da.json
- translations/stripes-core/de.json
- translations/stripes-core/en_GB.json
- translations/stripes-core/en_SE.json
- translations/stripes-core/en_US.json
- translations/stripes-core/es.json
- translations/stripes-core/es_419.json
- translations/stripes-core/es_ES.json
- translations/stripes-core/fr.json
- translations/stripes-core/fr_FR.json
- translations/stripes-core/hu.json
- translations/stripes-core/it_IT.json
- translations/stripes-core/pt_BR.json
- translations/stripes-core/pt_PT.json
- translations/stripes-core/zh_CN.json
> Update translation strings as of 20190815T130307

- src/components/MainNav/AppList/AppList.js
- src/components/MainNav/MainNav.js
If a user clicks on an _active menu item_ they will go to the home page of the current app.
**Ticket:** https://issues.folio.org/browse/STRIPES-643
> STRIPES-643

- webpack.config.base.js
Many thanks for @zburke for providing me with all the information I needed to make this simple change.
> Allow platforms to provide index.html overriding Stripes default

- translations/stripes-core/fr_FR.json
- translations/stripes-core/zh_CN.json
> Update translation strings as of 20190909T193700

- test/bigtest/network/scenarios/changePasswordClientError.js
- test/bigtest/tests/createResetPassword-test.js
Increase test coverage for ForgotUserName form
https://issues.folio.org/browse/STCOR-371
> STCOR-371 - Increase test coverage to 80% | Forgot User Name

- src/components/Login/Login.js
@zburke this should make sure the error message stays the same after we try to login with incorrect username second time.
> Fix error message after second unsuccessful login. Part of STCOR-395

- package.json
- webpack.config.base.js
This turned out to be delightfully trivial.
> Add support for handlebars-loader in WebPack config

- translations/stripes-core/fr_FR.json
> Update translation strings as of 20191118T154404

- translations/stripes-core/fr_FR.json
> Update translation strings as of 20191119T231120

- src/components/MainNav/ProfileDropdown/ProfileDropdown.js
**Ticket:** https://issues.folio.org/browse/STCOR-404
> STCOR-404: Re-added the current service name in the profile dropdown

- test/bigtest/tests/login-test.js
- translations/stripes-core/en.json
Update username not found error message
https://issues.folio.org/browse/UIU-1387
> UIU-1387 - User Login: Update username not found error message

- translations/stripes-core/ar.json
> Update translation strings as of 20200106T223901

- index.js
- src/StripesContext.js
An alternative to the withStripes() HoC for when a hook API is preferable.
> useStripes hook

- translations/stripes-core/ca.json
> Update translation strings as of 20200224T151433

- src/components/MainNav/ProfileDropdown/ProfileDropdown.js
#817 added many proptypes (yay!) but one was incorrect (whoops).
[STCOR-412](https://issues.folio.org/browse/STCOR-412)
> STCOR-412 correct stripes.hasPerm proptype

- translations/stripes-core/ru.json
> Update translation strings as of 20200317T123814

- translations/stripes-core/zh_CN.json
> Update translation strings as of 20200413T183215

- translations/stripes-core/ja.json
> Update translation strings as of 20200421T180634

- translations/stripes-core/zh_TW.json
> Update translation strings as of 20200423T142657

- src/components/OverlayContainer/OverlayContainer.css
Fixed minor issue with OverlayContainer that caused odd placement of the action dropdown.
https://issues.folio.org/browse/STCOR-429
> STCOR-429: Minor fix for <OverlayContainer> CSS

- translations/stripes-core/fr_FR.json
> Update translation strings as of 20200519T123842

- translations/stripes-core/fr_FR.json
> Update translation strings as of 20200526T141248

- translations/stripes-core/zh_CN.json
> Update translation strings as of 20200615T161518

- CHANGELOG.md
- src/components/MainNav/AppList/components/AppListDropdown/AppListDropdown.js
purpose: https://issues.folio.org/browse/STCOR-453 the options in the "apps" menu voice as actionable
approach: "button" role is used
> STCOR-453 The options in the "Apps" menu do not voice as actionable

- CHANGELOG.md
- package.json
- src/components/CreateResetPassword/CreateResetPassword.js
[[STCOR-466]](https://issues.folio.org/browse/STCOR-466)
We inadvertently created a circular dependency between stripes-core and stripes-final-form in PR #910 for STCOR-441. This prevents the release of stripes-core v6.0.0 and stripes v5.0.0.
> STCOR-466: Refactor CreateResetPassword to use vanilla react-final-form

- translations/stripes-core/es.json
- translations/stripes-core/es_419.json
- translations/stripes-core/es_ES.json
> Update translation strings as of 20201102T140138

- translations/stripes-core/fr_FR.json
> Update translation strings as of 20201105T151643

- translations/stripes-core/ar.json
- translations/stripes-core/ber.json
- translations/stripes-core/ca.json
- translations/stripes-core/da.json
- translations/stripes-core/de.json
- translations/stripes-core/en_GB.json
- translations/stripes-core/en_SE.json
- translations/stripes-core/en_US.json
- translations/stripes-core/es.json
- translations/stripes-core/es_419.json
- translations/stripes-core/es_ES.json
- translations/stripes-core/fr.json
- translations/stripes-core/fr_FR.json
- translations/stripes-core/he.json
- translations/stripes-core/hi_IN.json
- translations/stripes-core/hu.json
- translations/stripes-core/it_IT.json
- translations/stripes-core/ja.json
- translations/stripes-core/ko.json
- translations/stripes-core/pl.json
- translations/stripes-core/pt_BR.json
- translations/stripes-core/pt_PT.json
- translations/stripes-core/ru.json
- translations/stripes-core/ur.json
- translations/stripes-core/zh_CN.json
- translations/stripes-core/zh_TW.json
> Update translation strings as of 20201124T212804

- CHANGELOG.md
- src/components/About/About.js
- src/components/About/WarningBanner.js
https://issues.folio.org/browse/STCOR-479
Before merging this PR, please go through the following list and take appropriate actions.
- Does this PR meet or exceed the expected quality standards?
- [] Code coverage on new code is 80% or greater
- [] Duplications on new code is 3% or less
- [] There are no major code smells or security issues
- Does this introduce breaking changes?
If there are breaking changes, please **STOP** and consider the following:
- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
- Are the JIRAs under active development?
- Do PRs exist for these changes?
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that …
> STCOR-479 Settings > Software version > Display a loading indicator when querying for missing/incompatible modules

- package.json
- src/components/AppIcon/AppIcon.js
- src/components/HandlerManager/HandlerManager.js
- src/components/LastVisited/withLastVisited.js
- src/components/MainNav/AppList/components/AppListDropdown/AppListDropdown.js
- src/components/MainNav/CurrentApp/AppContextDropdown.js
- src/components/MainNav/MainNav.js
- src/components/MainNav/ProfileDropdown/ProfileDropdown.js
- src/components/Root/Root.js
- src/components/Settings/Settings.js
- src/components/TitledRoute/TitledRoute.js
In the great stripes-core
There was a bad prop-type
And a conflicting scope
And ESLint --
It totally went apeshit about this.
And there were legit uses of `for (const ... in ...)`
And there was a bogus ESLint warning about this
And there was an irritated developer whispering, "STFU ESLint. If I
could reach through the internet and stab you I would totally do that."
The End.
> Goodnight lint

- CHANGELOG.md
- package.json
Refs [STCOR-519](https://issues.folio.org/browse/STCOR-519)
> STCOR-519 increment lodash for security reasons

- src/loginServices.js
Minor change. Please see https://issues.folio.org/browse/STRIPES-683 Set credentials: include on fetch to /saml/login.
> STRIPES-683 Set credentials: include

- CHANGELOG.md
- src/Stripes.js
`PropTypes.stripes` is not a prop-type. Alphabetize props because it
looks so pretty that way.
> use correct prop-types

- src/configureEpics.js
[STCOR-592](https://issues.folio.org/browse/STCOR-592)
> STCOR-592 shout out to STCOR-592 for the next passerby

- CHANGELOG.md
- src/components/Settings/Settings.js
https://issues.folio.org/browse/STCOR-604
> STCOR-604 Add id to Settings navigation pane

- CHANGELOG.md
- src/moduleRoutes.js
- translations/stripes-core/en.json
https://issues.folio.org/browse/STCOR-619
> STCOR-619 Add message user cannot access app

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
https://issues.folio.org/browse/STCOR-623
> STCOR-623: Update NodeJS to v16 in GitHub Actions

- CHANGELOG.md
- index.js
- src/CalloutContext.js
- src/RootWithIntl.js
- src/useCallout.js
- test/bigtest/tests/callout-context-test.js
Added `useCallout` hook for easier mocking in tests
[STCOR-631](https://issues.folio.org/browse/STCOR-631)
> STCOR-631 Added useCallout hook

- CHANGELOG.md
- src/components/Login/Login.js
See https://issues.folio.org/browse/STCOR-633
Assistive technology prefers semantic landmarks. Axe dev tools flags that no landmarks are found on the FOLIO log-in screen.
> STCOR-644 - Login page requires main landmark.

- CHANGELOG.md
- src/components/Login/Login.js
[STCOR-648](https://issues.folio.org/browse/STCOR-648)
> STCOR-648 - Move SSO logon above Login text

- index.js
Expose additional functionality so it can be consumed via other modules.
https://issues.folio.org/browse/STCOR-711
> STCOR-711: Expose additional functionality so it can be consumed via other modules

- src/loginServices.js
https://issues.folio.org/browse/STCOR-690
basically it's a fix of original request, one place was missed
> STCOR-690 Support switch consortium active affiliation

- doc/adding-permissions.md
since calling from stripes-core is deprecated.
> Use Stripes CLI command

- yarn.lock
follow-redirects < 1.15.4 is vulnerable to CVE-2023-26159
> CVE-2023-26159 require follow-redirects >= 1.15.4

- .gitignore
- src/RootWithIntl.js
- src/RootWithIntl.test.js
- src/components/AuthnLogin/AuthnLogin.js
- src/components/AuthnLogin/index.js
- src/components/OIDCRedirect.js
- src/components/OIDCRedirect.test.js
- src/loginServices.js
Use session to restore unauthorized url pathname. 
Refs [STCOR-789](https://folio-org.atlassian.net/browse/STCOR-789).
> STCOR-789: Restore original URL on login

- src/components/LogoutTimeout/LogoutTimeout.js
- src/components/LogoutTimeout/LogoutTimeout.test.js
Whoops, missed this in #1463
Refs [STCOR-776](https://folio-org.atlassian.net/browse/STCOR-776)
> STCOR-776 correctly format logout-timeout translation IDs

- .github/workflows/ui.yml
Replace local workflow templates. Replaces #1475 
Refs [STCOR-852](https://folio-org.atlassian.net/browse/STCOR-852)
> STCOR-852 run CI with centralized workflows (round 2)

- src/components/SessionEventContainer/FixedLengthSessionWarning.js
Refs [STCOR-921](https://folio-org.atlassian.net/browse/STCOR-921)
> STCOR-921 typo: add missing whitespace

- .github/CODEOWNERS
Refs [STCOR-924](https://folio-org.atlassian.net/browse/STCOR-924)
> STCOR-924 implement CODEOWNERS

- translations/stripes-core/en.json
Whoops, missed this in PR #1463
Refs [STCOR-943](https://folio-org.atlassian.net/browse/STCOR-943)
> STCOR-943 provide title.logoutTimeout translation

- src/loginServices.js
**Approach**: fix updateTenant function by providing fetchUserWithPerms `isKeycloak` parameter.
Refs: [STCOR-947](https://folio-org.atlassian.net/browse/STCOR-947).
> STCOR-947: Cannot switch affiliations
